module.exports=[43946,a=>a.a(async(b,c)=>{try{var d=a.i(47818),e=a.i(98357),f=b([d,e]);[d,e]=f.then?(await f)():f,a.s([]),c()}catch(a){c(a)}},!1),42361,a=>a.a(async(b,c)=>{try{var d=a.i(43946),e=a.i(47818),f=a.i(98357),g=b([d,e,f]);[d,e,f]=g.then?(await g)():g,a.s(["40511040dfe83339012bc733f4f1c1e51418bf3961",()=>e.setInterfaceLanguage,"40d7335918eafee35dcb980c3997c242e435fdfbb7",()=>f.submitFeedback]),c()}catch(a){c(a)}},!1),98357,a=>a.a(async(b,c)=>{try{var d=a.i(37936);a.i(70396);var e=a.i(73727),f=a.i(53112),g=a.i(94758),h=a.i(81260),i=a.i(40815),j=a.i(58840),k=a.i(13095),l=b([g,i,j]);[g,i,j]=l.then?(await l)():l;let n=f.z.object({email:f.z.string().trim().email().max(254),category:f.z.enum(["TECHNICAL","CONTENT","PAYMENT","SUGGESTION","OTHER"]),subject:f.z.string().trim().min(4).max(120),message:f.z.string().trim().min(20).max(4e3),pageUrl:f.z.string().trim().max(500).url().refine(a=>["http:","https:"].includes(new URL(a).protocol)).optional(),website:f.z.string().max(0)});async function m(a){let b=await (0,j.getCurrentUser)(),c=n.safeParse({email:a.get("email"),category:a.get("category"),subject:a.get("subject"),message:a.get("message"),pageUrl:a.get("pageUrl")||void 0,website:a.get("website")??""});c.success||(0,e.redirect)("/support?error=invalid#feedback");try{await (0,i.enforceRateLimit)("support_feedback",b?.id??c.data.email),await g.db.insert(h.supportTickets).values({userId:b?.id,email:c.data.email.toLowerCase(),category:c.data.category,subject:c.data.subject,message:c.data.message,pageUrl:c.data.pageUrl||null})}catch(a){(0,e.redirect)(`/support?error=${a instanceof Error&&"RATE_LIMITED"===a.message?"rate":"failed"}#feedback`)}(0,e.redirect)("/support?sent=1#feedback")}(0,k.ensureServerEntryExports)([m]),(0,d.registerServerReference)(m,"40d7335918eafee35dcb980c3997c242e435fdfbb7",null),a.s(["submitFeedback",0,m]),c()}catch(a){c(a)}},!1),40815,a=>a.a(async(b,c)=>{try{var d=a.i(51674),e=a.i(94758),f=a.i(81260),g=a.i(90083),h=b([e]);[e]=h.then?(await h)():h;let j={signup:{attempts:5,windowMs:36e5},login:{attempts:10,windowMs:9e5},forgot_password:{attempts:5,windowMs:36e5},reset_password:{attempts:8,windowMs:36e5},verify_email:{attempts:12,windowMs:9e5},activate_account:{attempts:6,windowMs:36e5},resend_verification:{attempts:5,windowMs:36e5},google_oauth:{attempts:20,windowMs:9e5},guest_practice:{attempts:20,windowMs:9e5},product_analytics:{attempts:60,windowMs:9e5},support_feedback:{attempts:5,windowMs:36e5}};async function i(a,b){let c=j[a],h=(0,g.hashToken)(`${a}:${b.toLowerCase()}`),i=(await e.db.execute(d.sql`
    insert into ${f.authRateLimits} (key_hash, action, window_started_at, attempts, updated_at)
    values (${h}, ${a}, now(), 1, now())
    on conflict (key_hash) do update set
      attempts = case when ${f.authRateLimits.windowStartedAt} < now() - (${c.windowMs} * interval '1 millisecond') then 1 else ${f.authRateLimits.attempts} + 1 end,
      window_started_at = case when ${f.authRateLimits.windowStartedAt} < now() - (${c.windowMs} * interval '1 millisecond') then now() else ${f.authRateLimits.windowStartedAt} end,
      blocked_until = case
        when ${f.authRateLimits.windowStartedAt} < now() - (${c.windowMs} * interval '1 millisecond') then null
        when ${f.authRateLimits.attempts} + 1 > ${c.attempts} then coalesce(${f.authRateLimits.blockedUntil}, ${f.authRateLimits.windowStartedAt} + (${c.windowMs} * interval '1 millisecond'))
        else ${f.authRateLimits.blockedUntil}
      end,
      updated_at = now()
    returning attempts, blocked_until`)).rows[0];if(i&&(Number(i.attempts)>c.attempts||i.blocked_until&&new Date(i.blocked_until)>new Date))throw Error("RATE_LIMITED")}a.s(["enforceRateLimit",0,i]),c()}catch(a){c(a)}},!1)];

//# sourceMappingURL=_0hmkcqk._.js.map