import Link from "next/link";
import { AdminNav } from "@/components/admin/admin-nav";
import { requireAdmin } from "@/lib/admin/authorization";
import { listAdminPosts, listAdminPostTags } from "@/lib/blog/service";
import { CATEGORY_LABELS, POST_CATEGORIES, STATUS_LABELS, type PostCategory, type PostStatus } from "@/lib/blog/core";
import { getPreferences } from "@/lib/i18n/get-translations";
export default async function PostsPage({searchParams}:{searchParams:Promise<{q?:string;status?:string;category?:string;issues?:string}>}){
  const actor=await requireAdmin("CONTENT_READ"),prefs=await getPreferences(actor.id),[rows,tagRows]=await Promise.all([listAdminPosts(),listAdminPostTags()]),filters=await searchParams;
  const q=(filters.q||"").trim().toLocaleLowerCase();
  const tagMap=new Map<string,string[]>();for(const row of tagRows)tagMap.set(row.postId,[...(tagMap.get(row.postId)??[]),row.name]);
  const visible=rows.filter(x=>(!q||`${x.title} ${x.slug} ${(tagMap.get(x.id)??[]).join(" ")}`.toLocaleLowerCase().includes(q))&&(!filters.status||x.status===filters.status)&&(!filters.category||x.category===filters.category)&&(!filters.issues||(filters.issues==="yes"?(!x.seoDescription||!x.coverMediaId):Boolean(x.seoDescription&&x.coverMediaId))));
  return <main className="min-h-screen bg-slate-50 px-4 py-6"><div className="mx-auto max-w-7xl"><AdminNav locale={prefs.interfaceLanguage}/><div className="mt-8 flex flex-wrap items-center justify-between gap-4"><div><h1 className="text-3xl font-black">Bài viết SEO</h1><p className="mt-2 text-slate-600">Soạn, xem trước và xuất bản nội dung TOEIC.</p></div><Link className="rounded-xl bg-teal-700 px-5 py-3 font-black text-white" href="/admin/content/posts/new">Bài viết mới</Link></div>
    <form className="mt-6 grid gap-3 rounded-2xl border bg-white p-4 sm:grid-cols-4" action="/admin/content/posts"><label className="text-sm font-bold">Tìm tiêu đề hoặc slug<input className="mt-1 w-full rounded-lg border p-2" name="q" defaultValue={filters.q}/></label><label className="text-sm font-bold">Trạng thái<select className="mt-1 w-full rounded-lg border p-2" name="status" defaultValue={filters.status}><option value="">Tất cả</option>{Object.entries(STATUS_LABELS).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label className="text-sm font-bold">Danh mục<select className="mt-1 w-full rounded-lg border p-2" name="category" defaultValue={filters.category}><option value="">Tất cả</option>{POST_CATEGORIES.map(x=><option key={x} value={x}>{CATEGORY_LABELS[x].vi}</option>)}</select></label><label className="text-sm font-bold">Gợi ý SEO<select className="mt-1 w-full rounded-lg border p-2" name="issues" defaultValue={filters.issues}><option value="">Tất cả</option><option value="yes">Có gợi ý</option><option value="no">Không có gợi ý cơ bản</option></select></label><button className="rounded-lg bg-slate-900 px-4 py-2 font-bold text-white sm:col-span-4" type="submit">Lọc bài viết</button></form>
    <div className="mt-5 overflow-x-auto rounded-2xl border bg-white"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-100"><tr>{["Bài viết","Trạng thái","Danh mục","Cập nhật","SEO","Thao tác"].map(x=><th className="p-4" key={x}>{x}</th>)}</tr></thead><tbody>{visible.map(x=>{const issueCount=Number(!x.seoDescription)+Number(!x.coverMediaId);return <tr className="border-t" key={x.id}><td className="p-4"><Link className="font-bold text-teal-700" href={`/admin/content/posts/${x.id}`}>{x.title}</Link><p className="mt-1 font-mono text-xs text-slate-500">/blog/{x.slug}</p></td><td className="p-4 font-bold">{STATUS_LABELS[x.status as PostStatus]}</td><td className="p-4">{CATEGORY_LABELS[x.category as PostCategory]?.vi??x.category}</td><td className="p-4">{x.updatedAt.toLocaleDateString("vi-VN")}</td><td className="p-4">{issueCount?<Link className="text-amber-800 underline" href={`/admin/content/posts/${x.id}`}>{issueCount} gợi ý cơ bản</Link>:"Không có gợi ý cơ bản"}</td><td className="p-4"><Link className="text-teal-700 underline" href={`/admin/content/posts/${x.id}/preview`}>Xem trước</Link></td></tr>;})}</tbody></table>{!visible.length&&<p className="p-10 text-center text-slate-500">Không tìm thấy bài viết.</p>}</div></div></main>;
}
