"use client";
/* Signed private R2 URLs have dynamic hosts; native img avoids widening image allowlists. */
/* eslint-disable @next/next/no-img-element */
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState, useTransition } from "react";
import { ListeningAudioPlayer } from "@/components/listening/listening-audio-player";
import type { InterfaceLanguage } from "@/lib/i18n/config";
import { getTranslations } from "@/lib/i18n/runtime";
import type { PracticeSession } from "@/lib/practice/types";
import { submitReadingPractice } from "../actions";

export function ListeningPracticeClient({ session, locale }: { session: PracticeSession; locale: InterfaceLanguage }) {
  const t = getTranslations(locale); const router = useRouter(); const [index, setIndex] = useState(0); const [answers, setAnswers] = useState<Record<string,string>>({}); const [error, setError] = useState(""); const [pending, startTransition] = useTransition(); const question = session.questions[index]; const audio = question.media?.find((m) => m.kind === "AUDIO"); const image = question.media?.find((m) => m.kind === "IMAGE");
  function submit() { startTransition(async () => { const result = await submitReadingPractice(session.id, session.questions.map((q) => ({ questionId: q.id, selectedOptionId: answers[q.id] ?? null }))); if (!result.ok) { setError(t.practice.submitError); return; } router.push(`/practice/${session.id}/results`); }); }
  return <main className="min-h-screen bg-slate-50 px-4 py-5 text-slate-900"><div className="mx-auto max-w-2xl"><header className="flex items-center justify-between"><Link className="font-semibold text-teal-700" href="/practice">{t.practice.exit}</Link><span className="text-sm font-semibold">{t.practice.question} {index + 1} {t.practice.of} {session.questionCount}</span></header><section className="mt-6 rounded-3xl border border-slate-200 bg-white p-5 sm:p-8"><p className="text-sm font-black uppercase tracking-wider text-teal-700">{t.listening.title} · Part {question.part} · {question.part === 1 ? t.listening.photographs : t.listening.questionResponse}</p>{image ? <img alt={image.alt} className="mt-5 max-h-[55vh] w-full rounded-2xl object-contain" onError={() => setError(t.listening.imageUnavailable)} src={image.url} /> : null}<div className="mt-5">{audio ? <ListeningAudioPlayer assetId={audio.id} initialUrl={audio.url} labels={t.listening.audio} questionId={question.id} sessionId={session.id} /> : null}</div><fieldset className="mt-6"><legend className="font-bold">{t.listening.choose}</legend><div className={`mt-3 grid gap-3 ${question.part === 1 ? "grid-cols-2 sm:grid-cols-4" : "grid-cols-3"}`}>{question.options.map((option) => <label className={`flex min-h-14 cursor-pointer items-center justify-center rounded-xl border text-xl font-black ${answers[question.id] === option.id ? "border-teal-600 bg-teal-50 ring-1 ring-teal-600" : "border-slate-300"}`} key={option.id}><input className="sr-only" name={question.id} onChange={() => setAnswers((value) => ({ ...value, [question.id]: option.id }))} type="radio" />{option.key}</label>)}</div></fieldset></section>{error ? <p className="mt-4 rounded-xl bg-red-50 p-4 text-red-700" role="alert">{error}</p> : null}<div className="mt-5 flex gap-3"><button className="min-h-12 rounded-xl border bg-white px-5 font-bold disabled:opacity-40" disabled={index === 0} onClick={() => setIndex(index - 1)} type="button">{t.practice.previous}</button>{index + 1 < session.questionCount ? <button className="ml-auto min-h-12 rounded-xl bg-slate-900 px-5 font-bold text-white" onClick={() => setIndex(index + 1)} type="button">{t.practice.next}</button> : <button className="ml-auto min-h-12 rounded-xl bg-teal-700 px-5 font-bold text-white disabled:opacity-50" disabled={pending} onClick={submit} type="button">{pending ? t.practice.submitting : t.practice.submit}</button>}</div></div></main>;
}
