"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useRef, useState, useTransition } from "react";
import { PassageDocuments } from "@/components/practice/passage-documents";
import { QuestionBlock } from "@/components/practice/question-block";
import type { InterfaceLanguage } from "@/lib/i18n/config";
import { formatMessage, getTranslations } from "@/lib/i18n/runtime";
import { modeLabel } from "@/lib/i18n/labels";
import type { PracticeQuestion, PracticeSession, SubmittedAnswer } from "@/lib/practice/types";
import { submitReadingPractice } from "../actions";

export function ReadingPracticeClient({ session, locale, challenge = false }: { session: PracticeSession; locale: InterfaceLanguage; challenge?: boolean }) {
  const t = getTranslations(locale); const router = useRouter();
  const [groupIndex, setGroupIndex] = useState(0); const [answers, setAnswers] = useState<Record<string, string>>({}); const [responseTimes, setResponseTimes] = useState<Record<string, number>>({}); const [error, setError] = useState<string | null>(null); const [isPending, startTransition] = useTransition(); const enteredAt = useRef<number | null>(null);
  const group = session.groups[groupIndex]; const answeredCount = Object.keys(answers).length; const firstNumber = group.questions[0].number; const lastNumber = group.questions.at(-1)!.number; const hasPassage = group.passages.length > 0;
  useEffect(() => { enteredAt.current = Date.now(); }, [groupIndex]);
  function moveTo(index: number) { setGroupIndex(index); window.scrollTo({ top: 0, behavior: "smooth" }); }
  function choose(question: PracticeQuestion, optionId: string) { setAnswers((current) => ({ ...current, [question.id]: optionId })); setResponseTimes((current) => current[question.id] === undefined && enteredAt.current !== null ? { ...current, [question.id]: Date.now() - enteredAt.current } : current); }
  function submit() { if (isPending) return; const unanswered = session.questionCount - answeredCount; if (unanswered > 0 && !window.confirm(formatMessage(t.practice.remaining, { count: unanswered }))) return; const payload: SubmittedAnswer[] = session.questions.map((question) => ({ questionId: question.id, selectedOptionId: answers[question.id] ?? null, responseTimeMs: responseTimes[question.id] })); setError(null); startTransition(async () => { const result = await submitReadingPractice(session.id, payload); if (!result.ok) { setError(result.error === "session_expired" ? t.practice.sessionExpired : t.practice.submitError); return; } router.push(challenge ? `/challenge/part-5/${result.sessionId}/result` : `/practice/${result.sessionId}/results`); }); }
  const range = firstNumber === lastNumber ? `${t.practice.question} ${firstNumber}` : `${t.practice.questions} ${firstNumber}–${lastNumber}`;
  return <main className="min-h-screen overflow-x-hidden bg-slate-50 px-4 py-4 pb-32 text-slate-900 sm:px-6 lg:pb-10"><div className="mx-auto max-w-7xl">
    <header className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:p-5"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[0.16em] text-teal-700">{challenge ? "TOEIC GYM / PART 5 CHALLENGE" : `Part ${group.part} · ${modeLabel(group.setType, locale)}`}</p><h1 className="mt-1 text-2xl font-black">{range} <span className="text-slate-400">{t.practice.of} {session.questionCount}</span></h1></div><Link className="rounded-lg px-2 py-1 text-sm font-semibold text-slate-600 underline-offset-4 hover:text-teal-800 hover:underline focus-visible:outline-2 focus-visible:outline-teal-700" href={challenge ? "/challenge/part-5" : "/dashboard"}>{t.practice.exit}</Link></div><div className="mt-4 flex items-center justify-between gap-3 text-sm font-bold"><span>{t.practice.answered} {answeredCount} / {session.questionCount}</span><span className="text-slate-500">{Math.round(answeredCount / session.questionCount * 100)}%</span></div><div className="mt-2 h-2.5 overflow-hidden rounded-full bg-slate-200" aria-label={`${t.practice.answered} ${answeredCount}/${session.questionCount}`} role="progressbar" aria-valuemax={session.questionCount} aria-valuemin={0} aria-valuenow={answeredCount}><div className="h-full rounded-full bg-teal-600 transition-all" style={{ width: `${answeredCount / session.questionCount * 100}%` }} /></div>{session.requestedQuestionCount !== session.questionCount ? <p className="mt-3 text-xs text-slate-500">{formatMessage(t.practice.targetActual, { target: session.requestedQuestionCount, actual: session.questionCount })}</p> : null}</header>
    {hasPassage ? <div className="sticky top-2 z-20 mt-3 flex justify-center gap-2 lg:hidden"><a className="rounded-full bg-slate-900 px-4 py-2 text-sm font-bold text-white shadow-lg focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-teal-600" href="#passage">{t.practice.viewPassage}</a><a className="rounded-full border border-slate-300 bg-white px-4 py-2 text-sm font-bold shadow-lg focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-teal-600" href={`#question-${firstNumber}`}>{t.practice.backToQuestions}</a></div> : null}
    <div className={`mt-5 grid min-w-0 gap-6 ${hasPassage ? "lg:grid-cols-[minmax(20rem,0.95fr)_minmax(25rem,1.05fr)] lg:items-start" : "mx-auto max-w-4xl"}`}>{hasPassage ? <div className="min-w-0 scroll-mt-24 lg:sticky lg:top-5 lg:max-h-[calc(100vh-2.5rem)] lg:overflow-y-auto lg:pr-1" id="passage" lang="en"><PassageDocuments passages={group.passages} /></div> : null}<div className="min-w-0 space-y-4">{group.questions.map((question) => <QuestionBlock key={question.id} locale={locale} onChoose={(id) => choose(question, id)} question={question} selectedId={answers[question.id]} />)}</div></div>
    {error ? <p className="mt-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800" role="alert">{error}</p> : null}
    <section className="mt-6 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm" aria-label={t.practice.navigation}><div className="overflow-x-auto pb-2"><div className="flex w-max min-w-full justify-center gap-2">{session.groups.map((item, index) => { const complete = item.questions.every((question) => answers[question.id]); const label = item.questions.length === 1 ? `${item.questions[0].number}` : `${item.questions[0].number}–${item.questions.at(-1)!.number}`; return <button aria-current={index === groupIndex ? "step" : undefined} aria-label={`${t.practice.set} ${index + 1}, ${complete ? t.practice.answered : t.practice.unanswered}`} className={`h-11 min-w-11 shrink-0 rounded-lg border px-3 text-sm font-bold focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-teal-700 ${index === groupIndex ? "border-slate-900 bg-slate-900 text-white" : complete ? "border-teal-300 bg-teal-50 text-teal-900" : "border-slate-300 bg-white text-slate-700"}`} key={item.id} onClick={() => moveTo(index)} type="button"><span aria-hidden="true">{complete && index !== groupIndex ? "✓ " : ""}{label}</span></button>; })}</div></div></section>
    <div className="fixed inset-x-0 bottom-0 z-30 border-t border-slate-200 bg-white/95 px-4 pb-[max(0.75rem,env(safe-area-inset-bottom))] pt-3 shadow-[0_-8px_30px_rgba(15,23,42,0.12)] backdrop-blur lg:sticky lg:bottom-3 lg:mt-4 lg:rounded-2xl lg:border lg:px-5 lg:shadow-lg"><div className="mx-auto flex max-w-7xl items-center gap-2"><button className="min-h-12 rounded-xl border border-slate-300 bg-white px-4 font-bold disabled:cursor-not-allowed disabled:opacity-40" disabled={groupIndex === 0 || isPending} onClick={() => moveTo(groupIndex - 1)} type="button">{group.questions.length > 1 ? t.practice.previousSet : t.practice.previous}</button><p className="hidden flex-1 text-center text-sm font-bold text-slate-600 sm:block">{range} · {t.practice.answered} {answeredCount}/{session.questionCount}</p>{groupIndex < session.groups.length - 1 ? <button className="min-h-12 rounded-xl border border-slate-300 bg-white px-4 font-bold disabled:opacity-40" disabled={isPending} onClick={() => moveTo(groupIndex + 1)} type="button">{group.questions.length > 1 ? t.practice.nextSet : t.practice.next}</button> : <span className="flex-1 sm:hidden" />}<button className="ml-auto min-h-12 rounded-xl bg-teal-700 px-5 font-bold text-white shadow-sm hover:bg-teal-800 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-teal-700 disabled:opacity-50" disabled={isPending} onClick={submit} type="button">{isPending ? t.practice.submitting : t.practice.submit}</button></div></div>
  </div></main>;
}
