export type MiniQuestion = {
  id: string;
  text: string;
  options: [string, string, string, string];
  answer: number;
  explanation: string;
  // Review records explain why every distractor fails in this exact sentence.
  distractors: [string, string, string, string];
  origin: "TOEICGYM_ORIGINAL";
};

function question(id: string, text: string, options: MiniQuestion["options"], answer: number, explanation: string, distractors: MiniQuestion["distractors"]): MiniQuestion {
  return { id, text, options, answer, explanation, distractors, origin: "TOEICGYM_ORIGINAL" };
}

// Written for this release; independent of ETS/IIG material and the learner question bank.
export const MINI_PRACTICE: Record<string, MiniQuestion[]> = {
  "cau-bi-dong-toeic-part-5": [
    question("passive-1", "The access cards _____ by the security officer before the visitors arrived yesterday.", ["had checked", "had been checked", "have been checking", "will check"], 1,
      "Had been checked diễn tả thẻ được kiểm tra trước một sự kiện quá khứ khác: the visitors arrived yesterday.", ["Had checked là chủ động; thẻ không tự kiểm tra thứ khác.", "Đúng: quá khứ hoàn thành bị động.", "Have been checking là chủ động hiện tại hoàn thành tiếp diễn, sai cả thể và mốc quá khứ.", "Will check là chủ động tương lai, không khớp yesterday."]),
    question("passive-2", "All expense claims must _____ by a department manager before payment.", ["approve", "approved", "be approved", "approving"], 2,
      "Must be approved là modal + be + V3: các yêu cầu hoàn phí phải được quản lý phê duyệt.", ["Approve làm claims thành người phê duyệt; câu cần bị động.", "Approved thiếu be sau must.", "Đúng: must be approved.", "Approving không theo trực tiếp must trong cấu trúc này."]),
    question("passive-3", "The damaged monitors _____ by the repair team last Thursday.", ["were replaced", "was replaced", "have replaced", "are replacing"], 0,
      "Were replaced là bị động quá khứ đơn, hòa hợp với monitors số nhiều và last Thursday.", ["Đúng: monitors were replaced.", "Was không hòa hợp với monitors số nhiều.", "Have replaced là chủ động; monitors không tự thay thiết bị khác.", "Are replacing là chủ động hiện tại tiếp diễn, không khớp nghĩa và last Thursday."]),
    question("passive-4", "Please use the side entrance; the main staircase _____ by contractors right now.", ["renovates", "renovated", "has renovating", "is being renovated"], 3,
      "Is being renovated diễn tả cầu thang đang được sửa ngay lúc này: hiện tại tiếp diễn bị động.", ["Renovates là chủ động; staircase không thực hiện việc sửa.", "Renovated thiếu trợ động từ bị động trong câu này.", "Has renovating sai cấu trúc; has không nối trực tiếp với renovating ở đây.", "Đúng: is being renovated."]),
    question("passive-5", "The replacement printer will _____ to the branch tomorrow morning.", ["deliver", "be delivered", "delivering", "been delivered"], 1,
      "Be delivered kết hợp với will thành will be delivered: máy in sẽ được giao vào sáng mai.", ["Deliver là chủ động; máy in là vật được giao.", "Đúng: will be delivered.", "Delivering không đi trực tiếp sau will.", "Been delivered không đi trực tiếp sau will; phải là be delivered."]),
    question("passive-6", "The maintenance crew _____ the backup generator every Monday.", ["is inspected", "was inspected", "inspects", "be inspected"], 2,
      "Inspects là chủ động hiện tại đơn: maintenance crew thực hiện kiểm tra generator theo lịch every Monday.", ["Is inspected làm crew thành đối tượng được kiểm tra và không nối được tân ngữ generator như ở đây.", "Was inspected sai cấu trúc với tân ngữ generator, đồng thời không diễn tả lịch hiện tại.", "Đúng: crew inspects the generator.", "Be inspected chưa chia thì và không phù hợp với tân ngữ generator."]),
  ],
  "ving-va-to-infinitive-toeic": [
    question("verb-pattern-1", "The purchasing team agreed _____ the supplier's revised delivery terms.", ["accepting", "accepted", "accept", "to accept"], 3,
      "To accept theo mẫu agree to do something: nhóm mua hàng đồng ý chấp nhận điều khoản mới.", ["Accepting không theo trực tiếp agreed trong mẫu này.", "Accepted không làm động từ thứ hai sau agreed ở đây.", "Accept thiếu to sau agreed.", "Đúng: agreed to accept."]),
    question("verb-pattern-2", "The supervisor reminded the technicians _____ their tools before leaving the site.", ["to collect", "collecting", "collected", "collect"], 0,
      "To collect theo mẫu remind + người + to V: nhắc các kỹ thuật viên thu dọn dụng cụ.", ["Đúng: reminded the technicians to collect.", "Collecting không theo mẫu remind + người đang dùng ở đây.", "Collected không tạo được cấu trúc sau reminded the technicians.", "Collect thiếu to trong mẫu remind + người + to V."]),
    question("verb-pattern-3", "Before _____ the equipment, read the safety instructions carefully.", ["operate", "to operate", "operating", "operated"], 2,
      "Operating là V-ing sau giới từ before; chủ thể ngầm của operating cũng là người được yêu cầu đọc hướng dẫn.", ["Operate không theo trực tiếp giới từ before trong cụm này.", "To operate không theo before ở đây.", "Đúng: before operating.", "Operated không diễn tả người đọc chủ động vận hành thiết bị trong cụm này."]),
    question("verb-pattern-4", "We look forward to _____ your design proposal at next week's review.", ["discuss", "discussing", "to discuss", "discussed"], 1,
      "Discussing theo look forward to + V-ing; to là giới từ dù buổi thảo luận diễn ra tuần tới.", ["Discuss không theo giới từ to trong look forward to.", "Đúng: look forward to discussing.", "To discuss tạo thêm to và dùng sai dạng sau giới từ.", "Discussed không tạo được cụm chỉ hành động sau look forward to ở đây."]),
    question("verb-pattern-5", "To prevent duplicate orders, please avoid _____ the request more than once.", ["submitting", "to submit", "submit", "submitted"], 0,
      "Submitting theo mẫu avoid + V-ing: tránh gửi yêu cầu nhiều lần.", ["Đúng: avoid submitting.", "To submit không theo avoid trong mẫu này.", "Submit là nguyên mẫu thiếu cấu trúc sau avoid.", "Submitted không làm danh động từ sau avoid."]),
    question("verb-pattern-6", "The courier paused at reception in order _____ the package tracking number before continuing upstairs.", ["checking", "checked", "to check", "check"], 2,
      "To check hoàn tất mẫu in order to + V, diễn tả mục đích dừng lại để kiểm tra mã kiện hàng.", ["Checking không hoàn tất mẫu in order to + V.", "Checked không theo in order để diễn tả mục đích.", "Đúng: in order to check.", "Check thiếu to sau in order."]),
  ],
  "loai-tu-trong-toeic-part-5": [
    question("form-1", "The design team explained the changes _____ during the briefing.", ["clear", "clearly", "clarity", "clarify"], 1,
      "Clearly bổ nghĩa cho động từ explained: nhóm thiết kế giải thích một cách rõ ràng.", ["Clear là tính từ, không bổ nghĩa cho explained ở vị trí này.", "Đúng: trạng từ chỉ cách giải thích.", "Clarity là danh từ; câu không thiếu tân ngữ.", "Clarify là động từ nguyên mẫu, không nối trực tiếp sau the changes."]),
    question("form-2", "Visitors need written _____ before entering the laboratory.", ["permit", "permitted", "permissible", "permission"], 3,
      "Written permission là sự cho phép bằng văn bản. Permission là danh từ không đếm được nên không cần mạo từ.", ["Permit là danh từ đếm được số ít trong nghĩa giấy phép; phải có a written permit.", "Permitted là phân từ, không làm danh từ chỉ sự cho phép.", "Permissible là tính từ, chưa có danh từ để bổ nghĩa.", "Đúng: written permission."]),
    question("form-3", "The supplier offered a _____ solution to the packaging problem.", ["practical", "practically", "practice", "practices"], 0,
      "A practical solution là một giải pháp thiết thực: tính từ practical bổ nghĩa cho solution.", ["Đúng: tính từ trước danh từ.", "Practically là trạng từ; không dùng để mô tả danh từ solution trực tiếp.", "Practice không diễn tả tính thiết thực trong cụm này.", "Practices là danh từ số nhiều hoặc động từ, không phù hợp vị trí này."]),
  ],
  "thi-va-dang-dong-tu-toeic": [
    question("tense-1", "The courier _____ the signed contract to our office yesterday.", ["delivers", "will deliver", "delivered", "is delivering"], 2,
      "Yesterday xác định một thời điểm quá khứ đã kết thúc, nên dùng delivered.", ["Delivers là hiện tại đơn.", "Will deliver là tương lai.", "Đúng: quá khứ đơn.", "Is delivering diễn tả hiện tại đang diễn ra."]),
    question("tense-2", "By the time the workshop began, the technician _____ all the microphones.", ["tests", "had tested", "will test", "is testing"], 1,
      "Việc kiểm tra hoàn tất trước một sự kiện quá khứ khác (began): had tested.", ["Tests là hiện tại đơn.", "Đúng: quá khứ hoàn thành.", "Will test nói tương lai.", "Is testing là hiện tại tiếp diễn, không khớp mốc began."]),
    question("tense-3", "Please lower your voice; the director _____ a client on the phone right now.", ["called", "calls", "will call", "is calling"], 3,
      "Right now cùng lời đề nghị giữ yên lặng cho thấy hành động đang diễn ra: is calling.", ["Called chỉ việc đã qua.", "Calls mô tả thói quen, không diễn tả cuộc gọi đang diễn ra ở đây.", "Will call chỉ tương lai.", "Đúng: hiện tại tiếp diễn."]),
  ],
  "hoa-hop-chu-ngu-dong-tu-toeic": [
    question("agreement-1", "The list of approved suppliers _____ on the reception desk.", ["is", "are", "have", "were"], 0,
      "Chủ ngữ chính là list (số ít), không phải suppliers trong cụm of approved suppliers.", ["Đúng: list is.", "Are đi với chủ ngữ số nhiều.", "Have không tạo được vị ngữ với on the desk.", "Were đi với chủ ngữ số nhiều trong câu trần thuật này."]),
    question("agreement-2", "Each of the conference rooms _____ a projector.", ["contain", "contains", "containing", "have contained"], 1,
      "Each là chủ ngữ số ít, nên động từ hiện tại đơn thêm -s: contains.", ["Contain thiếu -s với each.", "Đúng: each contains.", "Containing chưa phải động từ chia thì.", "Have contained không hòa hợp với each; phải là has contained."]),
    question("agreement-3", "The number of online orders _____ increased this month.", ["have", "are", "has", "were"], 2,
      "The number là chủ ngữ số ít. Has increased diễn tả số lượng đã tăng trong tháng này.", ["Have không hòa hợp với the number.", "Are increased không diễn tả sự tăng số lượng và không hòa hợp.", "Đúng: the number has increased.", "Were không hòa hợp với the number."]),
  ],
  "gioi-tu-toeic-trong-cong-viec": [
    question("preposition-1", "The new coordinator is responsible _____ arranging airport transfers.", ["at", "with", "for", "of"], 2,
      "Responsible for + danh từ/V-ing diễn tả chịu trách nhiệm về một việc.", ["Responsible at không phải cụm phù hợp.", "Responsible with không diễn tả trách nhiệm về việc này.", "Đúng: responsible for arranging.", "Responsible of không đúng cụm."]),
    question("preposition-2", "All contractors must comply _____ the building's safety rules.", ["for", "with", "at", "to"], 1,
      "Comply with nghĩa là tuân thủ quy định.", ["Comply for không đi với rules.", "Đúng: comply with the rules.", "Comply at không đúng cụm.", "Comply to không đúng; đừng nhầm với adhere to."]),
    question("preposition-3", "The design team is interested _____ testing the new software.", ["on", "for", "under", "in"], 3,
      "Interested in + danh từ/V-ing diễn tả hứng thú với việc gì.", ["Interested on không đúng cụm.", "Interested for không đúng cấu trúc này.", "Interested under không dùng để chỉ mong muốn tham gia việc testing ở đây.", "Đúng: interested in testing."]),
  ],
  "lien-tu-va-tu-noi-toeic": [
    question("conjunction-1", "The reception desk was moved _____ the main entrance was being repaired.", ["because of", "because", "despite", "during"], 1,
      "Sau chỗ trống là mệnh đề có chủ ngữ the main entrance và động từ was being repaired, nên chọn because.", ["Because of cần cụm danh từ.", "Đúng: because + mệnh đề.", "Despite không nối trực tiếp mệnh đề này.", "During cần cụm danh từ chỉ thời gian."]),
    question("conjunction-2", "_____ the heavy rain, the delivery team completed all scheduled stops.", ["Although", "Because", "Despite", "Unless"], 2,
      "The heavy rain là cụm danh từ; despite diễn tả sự tương phản giữa mưa lớn và việc vẫn giao xong.", ["Although cần mệnh đề.", "Because cần mệnh đề.", "Đúng: despite + cụm danh từ.", "Unless cần mệnh đề điều kiện."]),
    question("conjunction-3", "Please email the invoice _____ the customer can arrange payment.", ["so that", "because of", "in spite of", "during"], 0,
      "So that + mệnh đề diễn tả mục đích: gửi hóa đơn để khách có thể thanh toán.", ["Đúng: so that + chủ ngữ + động từ.", "Because of cần cụm danh từ.", "In spite of cần cụm danh từ hoặc V-ing.", "During cần cụm danh từ."]),
    question("conjunction-4", "The outdoor demonstration was canceled _____ a severe storm warning.", ["although", "because", "however", "because of"], 3,
      "A severe storm warning là cụm danh từ chỉ nguyên nhân hủy buổi trình diễn, nên dùng because of.", ["Although không nối trực tiếp cụm danh từ này và không thể hiện nguyên nhân.", "Because cần mệnh đề có chủ ngữ và động từ.", "However không nối canceled với cụm danh từ chỉ nguyên nhân.", "Đúng: because of + cụm danh từ."]),
    question("conjunction-5", "_____ the new printer costs more, it uses less electricity than the old model.", ["Although", "Despite", "Because of", "During"], 0,
      "Although + mệnh đề the new printer costs more diễn tả sự nhượng bộ: giá mua cao hơn nhưng tiêu thụ ít điện hơn.", ["Đúng: although + chủ ngữ + động từ.", "Despite không đi trực tiếp với mệnh đề the new printer costs more.", "Because of cần cụm danh từ, không phải mệnh đề costs more.", "During cần cụm danh từ chỉ một khoảng thời gian."]),
    question("conjunction-6", "The warehouse is closed today; _____, online orders will still be processed.", ["although", "however", "despite", "because"], 1,
      "However nối hai ý tương phản; dấu chấm phẩy trước và dấu phẩy sau phù hợp với hai mệnh đề độc lập trong câu này.", ["Although mở mệnh đề phụ; không đứng trước dấu phẩy theo cấu trúc này.", "Đúng: however với dấu câu nối hai mệnh đề độc lập.", "Despite cần cụm danh từ hoặc V-ing, không đứng độc lập trước dấu phẩy ở đây.", "Because cần mệnh đề ngay sau, không tách khỏi chủ ngữ bằng dấu phẩy này."]),
  ],
  "menh-de-quan-he-toeic": [
    question("relative-1", "The consultant _____ report won the award will speak at Friday's meeting.", ["who", "whom", "whose", "which"], 2,
      "Sau chỗ trống là danh từ report; cần whose để diễn tả báo cáo của chuyên gia.", ["Who làm chủ ngữ, không đứng trước report theo nghĩa sở hữu.", "Whom làm tân ngữ, không chỉ sở hữu.", "Đúng: whose report.", "Which không chỉ sở hữu của consultant ở đây."]),
    question("relative-2", "The employee _____ organized the workshop received a thank-you letter.", ["who", "whose", "where", "whom"], 0,
      "Mệnh đề organized the workshop thiếu chủ ngữ chỉ người, nên dùng who.", ["Đúng: who làm chủ ngữ của organized.", "Whose cần danh từ sau nó.", "Where chỉ nơi chốn, không làm chủ ngữ.", "Whom làm tân ngữ, không làm chủ ngữ của organized."]),
    question("relative-3", "The office _____ we held the interview is on the second floor.", ["whose", "where", "who", "whom"], 1,
      "We held the interview đã có chủ ngữ và tân ngữ; where bổ sung địa điểm tổ chức.", ["Whose không bổ nghĩa cho we.", "Đúng: where tương đương in which.", "Who chỉ người.", "Whom chỉ người làm tân ngữ."]),
    question("relative-4", "The training room, _____ was renovated last month, now has adjustable desks.", ["where", "whose", "that", "which"], 3,
      "Which làm chủ ngữ của was renovated và thay cho the training room trong mệnh đề bổ sung có dấu phẩy.", ["Where chỉ địa điểm, không làm chủ ngữ của was renovated.", "Whose cần danh từ theo sau để chỉ sở hữu.", "That không mở mệnh đề quan hệ không xác định có dấu phẩy.", "Đúng: which làm chủ ngữ thay cho vật."]),
    question("relative-5", "The specialist to _____ we sent the technical drawings will visit on Tuesday.", ["who", "whom", "whose", "that"], 1,
      "Whom là tân ngữ chỉ người sau giới từ to được đặt trước từ quan hệ: to whom we sent the technical drawings.", ["Who không dùng sau giới từ to đặt trước từ quan hệ trong cấu trúc trang trọng này.", "Đúng: to whom.", "Whose diễn tả sở hữu, không làm tân ngữ của to ở đây.", "That không đứng ngay sau giới từ đưa lên trước mệnh đề quan hệ."]),
    question("relative-6", "The storage facility _____ the company leased last year is near the airport.", ["which", "where", "whose", "who"], 0,
      "Which làm tân ngữ của leased: the company leased the storage facility. Dù facility là địa điểm, câu thiếu vật được thuê nên không chọn where.", ["Đúng: which thay cho tân ngữ của leased.", "Where chỉ nơi diễn ra hành động, không điền được tân ngữ còn thiếu của leased.", "Whose cần danh từ theo sau, không phải the company leased trong câu này.", "Who chỉ người, không thay cho storage facility."]),
  ],
  "tu-vung-toeic-theo-chu-de-cong-so": [
    question("vocab-1", "Please keep the receipt so that you can request _____ for your travel expenses.", ["attendance", "reimbursement", "recruitment", "maintenance"], 1,
      "Receipt và travel expenses gợi việc hoàn lại khoản tiền đã chi: reimbursement.", ["Attendance là sự có mặt.", "Đúng: reimbursement là hoàn tiền chi phí.", "Recruitment là tuyển dụng.", "Maintenance là bảo trì."]),
    question("vocab-2", "The supplier cannot ship the goods until it receives a signed purchase _____.", ["weather", "journey", "order", "traffic"], 2,
      "Purchase order là đơn đặt hàng, phù hợp với supplier, ship the goods và signed.", ["Weather không kết hợp với purchase trong ngữ cảnh này.", "Journey là chuyến đi.", "Đúng: purchase order.", "Traffic là giao thông hoặc lưu lượng."]),
    question("vocab-3", "The supervisor asked us to _____ the deadline by submitting the report before noon.", ["meet", "attend", "participate", "arrive"], 0,
      "Meet a deadline nghĩa là hoàn thành đúng hạn. Before noon giải thích hạn nộp báo cáo.", ["Đúng: meet the deadline.", "Attend dùng với sự kiện, không dùng với deadline.", "Participate cần in và một hoạt động.", "Arrive là nội động từ, không nhận deadline làm tân ngữ."]),
    question("vocab-4", "The accounting team will _____ an invoice after verifying the order.", ["issue", "attend", "meet", "board"], 0,
      "Issue an invoice là xuất hóa đơn; accounting team là chủ thể phù hợp với hành động này.", ["Đúng: issue an invoice.", "Attend đi với sự kiện hoặc cuộc họp.", "Meet đi với deadline hoặc người, không phải invoice trong câu này.", "Board là lên tàu hoặc hội đồng, không phù hợp ngữ cảnh."]),
    question("vocab-5", "The manager asked us to _____ the deadline because the supplier needs two more days.", ["track", "extend", "reserve", "recruit"], 1,
      "Supplier cần thêm thời gian nên deadline được gia hạn: extend the deadline.", ["Track thường đi với shipment hoặc order.", "Đúng: extend a deadline.", "Reserve đi với chỗ, bàn hoặc lịch đặt trước.", "Recruit đi với nhân sự cần tuyển."]),
    question("vocab-6", "Please _____ the shipment online so we know when it will arrive.", ["track", "issue", "meet", "make"], 0,
      "Track a shipment là theo dõi lô hàng; mệnh đề sau hỏi thời điểm hàng đến.", ["Đúng: track the shipment.", "Issue an invoice hoặc issue a notice, không issue shipment trong câu này.", "Meet đi với deadline hoặc người, không phải shipment.", "Make cần một cụm khác như make a reservation; make the shipment không diễn tả theo dõi."]),
  ],
  "collocation-la-gi-cum-tu-toeic-thong-dung": [
    question("collocation-1", "The negotiation team hopes to _____ an agreement with the supplier by Friday.", ["reach", "attend", "arrive", "meet"], 0,
      "Reach an agreement là đạt được thỏa thuận; negotiation team và supplier tạo đúng ngữ cảnh đàm phán.", ["Đúng: reach an agreement.", "Attend dùng với cuộc họp hoặc sự kiện, không dùng với agreement.", "Arrive là nội động từ và thường cần at/in trước địa điểm.", "Meet an agreement không phải collocation phù hợp; meet thường đi với deadline, requirement hoặc người."]),
    question("collocation-2", "Please _____ an update on the installation before tomorrow's meeting.", ["make", "provide", "reach", "perform"], 1,
      "Provide an update là cung cấp thông tin cập nhật; câu yêu cầu thông tin trước cuộc họp.", ["Make an update có thể gặp trong ngữ cảnh kỹ thuật nhưng không tự nhiên bằng provide an update khi báo cáo tình hình.", "Đúng: provide an update.", "Reach an update không phải collocation.", "Perform an update thường nói về thao tác cập nhật hệ thống, không phải cung cấp báo cáo tình hình."]),
    question("collocation-3", "The accounting department will _____ an invoice after confirming the order.", ["issue", "meet", "raise", "conduct"], 0,
      "Issue an invoice là xuất hóa đơn; accounting department là chủ thể tự nhiên của hành động này.", ["Đúng: issue an invoice.", "Meet không kết hợp với invoice trong nghĩa xuất hóa đơn.", "Raise an invoice có thể xuất hiện trong một số biến thể Anh-Anh, nhưng issue là lựa chọn chuẩn và rõ nhất trong câu này.", "Conduct thường đi với interview, survey hoặc inspection, không đi với invoice."]),
    question("collocation-4", "Because two figures are still missing, we may need to _____ the deadline.", ["extend", "attend", "track", "fill"], 0,
      "Extend the deadline là gia hạn thời hạn; dữ liệu còn thiếu giải thích vì sao cần thêm thời gian.", ["Đúng: extend the deadline.", "Attend dùng với sự kiện, không dùng với deadline.", "Track a deadline có thể là theo dõi hạn, nhưng không diễn tả việc cần thêm thời gian.", "Fill không kết hợp với deadline trong nghĩa gia hạn."]),
  ],
  "phrasal-verbs-toeic-theo-chu-de-cong-viec": [
    question("phrasal-1", "Please _____ the attached form and return it to Human Resources.", ["fill out", "run out of", "call off", "take over"], 0,
      "Fill out a form là điền thông tin vào biểu mẫu; attached form và return it là hai tín hiệu trực tiếp.", ["Đúng: fill out the form.", "Run out of nghĩa là dùng hết một thứ gì đó.", "Call off nghĩa là hủy một sự kiện hoặc kế hoạch.", "Take over nghĩa là tiếp quản công việc hoặc quyền kiểm soát."]),
    question("phrasal-2", "The outdoor product demonstration was _____ because of the storm warning.", ["looked into", "called off", "taken over", "sent out"], 1,
      "Was called off là bị hủy; cảnh báo bão là nguyên nhân hợp lý để hủy buổi trình diễn ngoài trời.", ["Looked into nghĩa là được điều tra hoặc xem xét, không phù hợp với sự kiện ngoài trời ở đây.", "Đúng: was called off.", "Taken over nghĩa là được tiếp quản, không diễn tả việc sự kiện không diễn ra.", "Sent out nghĩa là được gửi đi hoặc phát đi."]),
    question("phrasal-3", "Our support team is _____ the billing error and will contact you tomorrow.", ["looking into", "running out of", "turning down", "handing in"], 0,
      "Is looking into the billing error nghĩa là đang điều tra hoặc xem xét lỗi thanh toán; lời hứa liên hệ lại cho thấy nhóm đang kiểm tra vấn đề.", ["Đúng: is looking into the billing error.", "Run out of nghĩa là cạn một nguồn lực và không phù hợp với billing error.", "Turn down nghĩa là từ chối hoặc giảm âm lượng.", "Hand in nghĩa là nộp một tài liệu hoặc vật."]),
    question("phrasal-4", "The assistant printed the report and _____ to the manager before noon.", ["handed it in", "handed in it", "ran it out of", "looked it into"], 0,
      "Với đại từ it, phrasal verb tách được hand in đặt đại từ ở giữa: handed it in.", ["Đúng: handed it in.", "Handed in it sai vị trí đại từ với phrasal verb tách được này.", "Run out of nghĩa là dùng hết và không thể nhận report theo cấu trúc này.", "Look into nghĩa là điều tra; looked it into vừa sai trật tự vừa sai nghĩa."]),
  ],
  "tu-de-nham-trong-tieng-anh-toeic-part-5": [
    question("confusing-1", "The new inspection procedure will _____ that every emergency exit is clearly marked.", ["assure", "ensure", "insure", "securely"], 1,
      "Ensure + mệnh đề nghĩa là bảo đảm một kết quả xảy ra: mọi lối thoát được đánh dấu rõ.", ["Assure thường nhận người làm tân ngữ, như assure employees that..., nên không phù hợp trực tiếp trước mệnh đề này.", "Đúng: ensure that...", "Insure chủ yếu nói về bảo hiểm trước rủi ro tài chính.", "Securely là trạng từ, không thể làm động từ sau will."]),
    question("confusing-2", "Higher shipping costs have _____ the price of imported equipment.", ["effect", "affected", "effects", "effective"], 1,
      "Have affected là hiện tại hoàn thành: chi phí vận chuyển đã tác động đến giá thiết bị.", ["Effect thường là danh từ; nếu dùng làm động từ mang nghĩa tạo ra thì cũng phải ở dạng effect sau have been hoặc effected sau have.", "Đúng: have affected.", "Effects không đi sau trợ động từ have trong cấu trúc này.", "Effective là tính từ, không làm động từ chính sau have."]),
    question("confusing-3", "The company plans to _____ prices after the warranty period ends.", ["rise", "raise", "arise", "rose"], 1,
      "Raise là ngoại động từ và nhận prices làm tân ngữ; công ty chủ động tăng giá.", ["Rise là nội động từ nên không nhận prices làm tân ngữ.", "Đúng: raise prices.", "Arise nghĩa là phát sinh và không nhận prices làm tân ngữ.", "Rose là dạng quá khứ của rise, không theo sau plans to."]),
    question("confusing-4", "Before approving the loan, the bank will _____ the applicant's financial risk.", ["access", "assess", "excess", "accept"], 1,
      "Assess risk là đánh giá rủi ro; đây là việc ngân hàng cần làm trước khi phê duyệt khoản vay.", ["Access nghĩa là truy cập hoặc quyền truy cập, không phải đánh giá.", "Đúng: assess the risk.", "Excess là danh từ hoặc tính từ chỉ phần vượt quá.", "Accept nghĩa là chấp nhận, không diễn tả bước đánh giá trước quyết định."]),
  ],
  "cach-viet-email-tieng-anh-cong-viec-mau": [
    question("email-1", "Which subject line is clearest for an email asking a manager to approve the travel budget by Friday?", ["Hello", "Important request", "Action required: Approve travel budget by Friday", "A question"], 2,
      "Action required: Approve travel budget by Friday nêu hành động, đối tượng và thời hạn; người nhận hiểu yêu cầu trước khi mở email.", ["Hello không cho biết chủ đề hoặc việc cần làm.", "Important request vẫn mơ hồ về nội dung và hạn xử lý.", "Đúng: dòng chủ đề có hành động, đối tượng và hạn Friday.", "A question không giúp người nhận ưu tiên hoặc đoán nội dung."]),
    question("email-2", "Could you please _____ the revised schedule by 3:00 p.m. today?", ["review", "reviewing", "reviewed", "to review"], 0,
      "Sau could you please dùng động từ nguyên mẫu không to: review.", ["Đúng: could you please review.", "Reviewing không theo trực tiếp could you please.", "Reviewed là dạng quá khứ/phân từ, không đứng sau could trong câu hỏi này.", "To review thừa to sau modal could."]),
    question("email-3", "Which opening most clearly follows up on a proposal sent on 5 October?", ["I hope you are fine.", "I am following up on the proposal I sent on 5 October.", "Why haven't you replied?", "This is very urgent."], 1,
      "I am following up on the proposal I sent on 5 October. Câu này nêu đúng mục đích, tài liệu và mốc thời gian nên người nhận xác định được email trước đó.", ["Lời chào chung không nói email đang theo dõi việc gì.", "Đúng: câu mở đầu xác định proposal và ngày gửi.", "Câu hỏi trách móc không chuyên nghiệp và vẫn thiếu ngữ cảnh cụ thể.", "Câu báo khẩn cấp không nêu đối tượng cần xử lý."]),
    question("email-4", "Which sentence makes a clear, polite rescheduling request?", ["Change the meeting.", "I cannot come.", "Would it be possible to move Thursday's meeting to Friday morning?", "The meeting time is bad."], 2,
      "Would it be possible to move Thursday's meeting to Friday morning? là lời đề nghị lịch sự, nêu cả lịch cũ lẫn phương án mới.", ["Mệnh lệnh trực tiếp không lịch sự và không cho thời gian thay thế.", "Câu này chỉ nêu vấn đề, chưa đề nghị lịch mới.", "Đúng: yêu cầu rõ, lịch sự và có phương án cụ thể.", "Câu đánh giá mơ hồ, không chỉ ra thời gian thay thế."]),
  ],
  "am-cuoi-tieng-anh-cach-phat-am-khong-them-am": [
    question("final-sound-1", "Which pair mainly contrasts the final sounds /s/ and /z/?", ["rice – rise", "desk – desks", "need – needed", "plan – planned"], 0,
      "Rice – rise mainly contrasts the voiceless final /s/ with the voiced final /z/.", ["Đúng: rice – rise khác nhau ở /s/ và /z/ cuối.", "Desk – desks thêm dấu hiệu số nhiều và tạo cụm phụ âm /sks/.", "Need – needed thay đổi cả đuôi và số âm tiết.", "Plan – planned thêm đuôi quá khứ /d/."]),
    question("final-sound-2", "In “The manager needs the revised files,” which words carry grammatical information in their final sounds?", ["needs, revised, files", "the, manager, the", "manager, the, files", "the, revised, the"], 0,
      "Needs, revised, files carry the third-person, participle and plural signals in their final sounds.", ["Đúng: cả needs, revised và files đều có âm cuối mang thông tin ngữ pháp.", "The không mang ba dấu hiệu mục tiêu; manager không có hậu tố ngữ pháp trong câu này.", "Manager không mang dấu hiệu số/ngôi cần tìm và lựa chọn bỏ sót needs, revised.", "Hai từ the không phải dấu hiệu số nhiều, quá khứ hay ngôi thứ ba."]),
    question("final-sound-3", "What is the best way to finish the word “back” without creating an extra syllable?", ["Close at /k/ without adding a vowel", "Add /ə/ after /k/", "Remove /k/ completely", "Change /k/ to /g/"], 0,
      "Close at /k/ without adding a vowel keeps the final consonant but does not create an extra syllable.", ["Đúng: giữ vị trí /k/ cuối và không thêm nguyên âm.", "Thêm /ə/ tạo một âm tiết không có trong back.", "Bỏ /k/ làm mất tín hiệu phân biệt từ.", "Đổi /k/ thành /g/ có thể làm người nghe nhận sang một từ khác."]),
    question("final-sound-4", "Which word ends with a voiced consonant?", ["save", "safe", "back", "seat"], 0,
      "Save ends with voiced /v/; the other choices end with voiceless consonants.", ["Đúng: save kết thúc bằng /v/ hữu thanh.", "Safe kết thúc bằng /f/ vô thanh.", "Back kết thúc bằng /k/ vô thanh.", "Seat kết thúc bằng /t/ vô thanh."]),
  ],
  "cach-phat-am-s-es-tieng-anh": [
    question("s-es-1", "How is the -s ending in “reports” pronounced?", ["/s/", "/z/", "/ɪz/", "It is silent"], 0,
      "/s/ follows the voiceless final /t/ in report.", ["Đúng: reports kết thúc /ts/ với đuôi /s/.", "/z/ dùng sau nguyên âm hoặc âm hữu thanh không xì.", "/ɪz/ dùng sau âm xì và tạo thêm âm tiết.", "Đuôi không câm; nó mang dấu hiệu số nhiều."]),
    question("s-es-2", "Which plural has an extra syllable compared with its singular form?", ["offices", "plans", "reports", "files"], 0,
      "Offices adds /ɪz/ after final /s/, so it has an extra syllable.", ["Đúng: office → offices thêm /ɪz/.", "Plans thêm /z/ nhưng không thêm âm tiết.", "Reports thêm /s/ nhưng không thêm âm tiết.", "Files thêm /z/ nhưng không thêm âm tiết."]),
    question("s-es-3", "How is the final -s in “plans” pronounced?", ["/s/", "/z/", "/ɪz/", "/t/"], 1,
      "/z/ follows the voiced final /n/ in plan.", ["/s/ theo âm vô thanh, trong khi /n/ hữu thanh.", "Đúng: plans kết thúc /nz/.", "/ɪz/ chỉ theo nhóm âm xì.", "/t/ không phải cách đọc đuôi -s trong từ này."]),
    question("s-es-4", "Which group has the -s ending pronounced /s/ in every word?", ["reports, desks, graphs", "plans, calls, files", "offices, changes, watches", "employees, meetings, receives"], 0,
      "Reports, desks, graphs all add /s/ after voiceless final sounds.", ["Đúng: /t/, /k/ và /f/ đều dẫn tới đuôi /s/.", "Ba từ này có đuôi /z/.", "Ba từ này có đuôi /ɪz/.", "Ba từ này có đuôi /z/."]),
  ],
  "cach-phat-am-ed-tieng-anh": [
    question("ed-1", "How is the -ed ending in “checked” pronounced?", ["/t/", "/d/", "/ɪd/", "It is silent"], 0,
      "/t/ follows the voiceless final /k/ in check.", ["Đúng: checked kết thúc bằng cụm /kt/.", "/d/ theo nguyên âm hoặc âm hữu thanh còn lại.", "/ɪd/ chỉ theo /t/ hoặc /d/.", "Đuôi không câm; /t/ mang dấu hiệu quá khứ/phân từ."]),
    question("ed-2", "Which word gains an extra syllable when -ed is added?", ["needed", "planned", "checked", "shipped"], 0,
      "Needed adds /ɪd/ after /d/, creating an extra syllable.", ["Đúng: need → needed thêm âm tiết /ɪd/.", "Planned thêm /d/ nhưng không thêm âm tiết.", "Checked thêm /t/ nhưng không thêm âm tiết.", "Shipped thêm /t/ nhưng không thêm âm tiết."]),
    question("ed-3", "How is the -ed ending in “planned” pronounced?", ["/t/", "/d/", "/ɪd/", "/z/"], 1,
      "/d/ follows the voiced final /n/ in plan.", ["/t/ dùng sau phụ âm vô thanh.", "Đúng: planned kết thúc /nd/.", "/ɪd/ chỉ dùng sau /t/ hoặc /d/.", "/z/ là một cách đọc của -s, không phải -ed trong planned."]),
    question("ed-4", "Which group has -ed pronounced /ɪd/ in every word?", ["wanted, needed, updated", "checked, shipped, laughed", "planned, called, approved", "worked, agreed, started"], 0,
      "Wanted, needed, updated all have base verbs ending in /t/ or /d/, so -ed is /ɪd/.", ["Đúng: cả ba từ thêm /ɪd/.", "Ba từ này có đuôi /t/.", "Ba từ này có đuôi /d/.", "Worked là /t/, agreed là /d/, còn started là /ɪd/ nên nhóm không đồng nhất."]),
  ],
  "trong-am-tu-tieng-anh-quy-tac-cach-tra": [
    question("stress-1", "In a dictionary transcription, which symbol normally appears immediately before the primary stressed syllable?", ["ˈ", "ˌ", ".", "/"], 0,
      "ˈ appears immediately before the primary stressed syllable in IPA transcriptions used by learner dictionaries.", ["Đúng: ˈ đánh dấu trọng âm chính.", "ˌ thường đánh dấu trọng âm phụ.", "Dấu chấm có thể phân tách âm tiết nhưng không đánh dấu trọng âm chính.", "Dấu gạch chéo bao quanh toàn bộ phiên âm."]),
    question("stress-2", "In the common pronunciation /ɪmˈplɔɪ.iː/, which part of “employee” carries primary stress?", ["em", "ploy", "ee", "All are equal"], 1,
      "Ploy carries primary stress in /ɪmˈplɔɪ.iː/, although another accepted variant stresses the final syllable.", ["Em đứng trước dấu trọng âm và là âm tiết yếu trong biến thể này.", "Đúng: dấu ˈ đứng trước ploy.", "Ee có thể được nhấn trong một biến thể khác, nhưng không trong phiên âm đã cho.", "Các âm tiết không được nhấn đều nhau trong phiên âm này."]),
    question("stress-3", "What is the usual stress contrast between the noun and verb forms of “record”?", ["Noun: first; verb: second", "Noun: second; verb: first", "Both always stress the first", "Both always stress the second"], 0,
      "Noun: first; verb: second describes the usual contrast between REcord and reCORD.", ["Đúng: danh từ thường nhấn âm đầu, động từ nhấn âm sau.", "Lựa chọn này đảo ngược pattern thông dụng.", "Động từ record thường không nhấn âm đầu.", "Danh từ record thường không nhấn âm sau."]),
    question("stress-4", "Which part carries primary stress in “presentation” /ˌprez.ənˈteɪ.ʃən/?", ["pre", "sen", "ta", "tion"], 2,
      "Ta carries primary stress because ˈ appears before /teɪ/ in presentation.", ["Pre có trọng âm phụ trong phiên âm này.", "Sen không đứng sau dấu trọng âm chính.", "Đúng: phần ta tương ứng /teɪ/ được nhấn chính.", "Âm tiết cuối /ʃən/ không mang trọng âm chính."]),
  ],
  "toeic-speaking-la-gi-cau-truc-11-cau": [
    question("speaking-format-1", "How many questions are in the TOEIC Speaking test format described by ETS?", ["8", "10", "11", "12"], 2,
      "11 is the number of questions in the current TOEIC Speaking format described by ETS.", ["8 là số câu của TOEIC Writing, không phải Speaking.", "Bài Speaking có nhiều hơn 10 câu.", "Đúng: TOEIC Speaking có 11 câu.", "12 không phải số câu trong format được dẫn nguồn."]),
    question("speaking-format-2", "Which task is used for Questions 3–4?", ["Describe a picture", "Write an email", "Express a written opinion", "Complete a sentence"], 0,
      "Describe a picture is the task used for Questions 3–4.", ["Đúng: câu 3–4 yêu cầu mô tả tranh.", "Write an email thuộc TOEIC Writing.", "Written opinion thuộc TOEIC Writing câu 8.", "Complete a sentence không phải task câu 3–4 Speaking."]),
    question("speaking-format-3", "What should a 15-second response normally do first?", ["Answer the question directly", "Repeat the entire prompt", "Give three long examples", "Explain the test format"], 0,
      "Answer the question directly first, then add one useful detail if time allows.", ["Đúng: phản hồi trực tiếp bảo đảm relevance trước.", "Lặp prompt không cung cấp câu trả lời.", "Ba ví dụ dài không phù hợp giới hạn 15 giây.", "Giải thích format không trả lời nội dung được hỏi."]),
    question("speaking-format-4", "Which self-review label best fits an answer that is clear but does not answer the prompt?", ["Task fulfillment", "Pronunciation only", "Microphone volume only", "Typing speed"], 0,
      "Task fulfillment is the relevant label because the response does not complete the requested task.", ["Đúng: câu rõ nhưng lệch yêu cầu là lỗi task fulfillment.", "Pronunciation không phải vấn đề chính nếu lời nói đã rõ.", "Âm lượng không giải quyết việc trả lời lệch prompt.", "Typing speed không liên quan bài Speaking."]),
  ],
  "toeic-speaking-mo-ta-tranh-khung-tra-loi": [
    question("speaking-picture-1", "Which opening is safest when the location is clearly an office?", ["This picture was taken in an office.", "These people are definitely executives.", "Everyone is feeling stressed.", "The company is losing money."], 0,
      "This picture was taken in an office. Câu này nêu bối cảnh nhìn thấy được mà không bịa chi tiết.", ["Đúng: câu mở nêu bối cảnh nhìn thấy được.", "Chức vụ executives có thể không có bằng chứng.", "Cảm xúc stressed là suy diễn.", "Tình hình tài chính không thể xác định từ ảnh."]),
    question("speaking-picture-2", "Which phrase most clearly organizes a detail by position?", ["In the foreground", "Maybe successful", "Very interesting", "In my opinion"], 0,
      "In the foreground clearly tells the listener where a detail appears in the picture.", ["Đúng: cụm này tổ chức mô tả theo không gian.", "Maybe successful là suy đoán, không chỉ vị trí.", "Very interesting là đánh giá chung.", "In my opinion không giúp định vị vật hoặc người."]),
    question("speaking-picture-3", "What is the best preparation note for a 30-second picture response?", ["place – people – actions – positions", "a complete memorized paragraph", "every object in alphabetical order", "only difficult vocabulary"], 0,
      "Place – people – actions – positions provides compact cues for an organized response.", ["Đúng: từ khóa ngắn giúp tự tạo câu.", "Viết cả đoạn tốn thời gian và dễ làm câu trả lời cứng.", "Thứ tự alphabet không tạo mô tả tự nhiên.", "Chỉ ghi từ khó không bảo đảm đủ ý chính."]),
    question("speaking-picture-4", "Which sentence uses cautious inference appropriately?", ["They may be preparing a shipment.", "They are certainly the company owners.", "They hate their jobs.", "The business will close tomorrow."], 0,
      "They may be preparing a shipment. Cụm may be đánh dấu một suy luận hợp lý nhưng chưa chắc chắn.", ["Đúng: may be báo hiệu suy luận thận trọng.", "Danh tính chủ sở hữu không có bằng chứng.", "Cảm xúc tiêu cực không thể khẳng định.", "Tương lai doanh nghiệp không thể suy ra từ ảnh."]),
  ],
  "toeic-writing-email-cach-viet-bai-mau": [
    question("writing-email-1", "What should you identify before drafting a TOEIC Writing email response?", ["Your role and every requested action", "A rare idiom to include", "The longest possible greeting", "A personal story unrelated to the request"], 0,
      "Your role and every requested action should be identified before drafting the response.", ["Đúng: vai và checklist yêu cầu quyết định nội dung email.", "Idiom hiếm không bảo đảm hoàn thành task.", "Greeting dài làm mất thời gian phần thân.", "Chuyện ngoài yêu cầu làm email kém liên quan."]),
    question("writing-email-2", "If the prompt says “make two requests,” what must the response contain?", ["Two distinct requested actions", "One request written twice", "Two greetings", "Two signatures"], 0,
      "Two distinct requested actions are needed to satisfy an instruction to make two requests.", ["Đúng: hai hành động khác nhau mới xử lý đủ yêu cầu.", "Lặp một request không tạo yêu cầu thứ hai.", "Greeting không phải request.", "Signature không phải request."]),
    question("writing-email-3", "Which sentence creates the clearest next action?", ["Please send the order number by 3:00 p.m.", "Something should happen soon.", "This situation is interesting.", "I have many thoughts."], 0,
      "Please send the order number by 3:00 p.m. Câu này cho biết hành động, đối tượng và thời hạn.", ["Đúng: người nhận biết phải làm gì và khi nào.", "Something và soon đều mơ hồ.", "Câu này không tạo hành động tiếp theo.", "Câu này không xử lý yêu cầu công việc."]),
    question("writing-email-4", "Which final review is most important for task completion?", ["Check every prompt requirement has a response", "Replace every common word", "Add another unrelated paragraph", "Remove all simple sentences"], 0,
      "Check every prompt requirement has a response before spending time on stylistic changes.", ["Đúng: bỏ sót yêu cầu là lỗi task quan trọng.", "Từ thông dụng chính xác không cần thay hết.", "Đoạn ngoài đề làm giảm relevance.", "Câu đơn rõ vẫn hữu ích trong email."]),
  ],
  "toeic-writing-opinion-essay-cach-viet": [
    question("writing-opinion-1", "Which thesis answers the remote-work prompt most directly?", ["Remote work benefits both sides when expectations are clear.", "Remote work is a topic with many words.", "People have worked for a long time.", "There are several office buildings."], 0,
      "Remote work benefits both sides when expectations are clear. Thesis này nêu lập trường và một điều kiện hữu ích.", ["Đúng: thesis trả lời trực tiếp và xác định lập trường.", "Câu này không có quan điểm.", "Câu lịch sử chung không xử lý prompt.", "Office buildings không liên quan lập luận chính."]),
    question("writing-opinion-2", "What should normally follow a body paragraph's main reason?", ["An explanation and relevant example", "A new unrelated thesis", "A copied version of the prompt", "A list of difficult words"], 0,
      "An explanation and relevant example show how the reason supports the essay's position.", ["Đúng: giải thích và ví dụ phát triển claim.", "Thesis mới làm lập luận mâu thuẫn.", "Chép prompt không tạo hỗ trợ.", "Danh sách từ không phải lập luận."]),
    question("writing-opinion-3", "Which example avoids an unsupported statistic?", ["A coordinator could finish a report during saved commuting time.", "Exactly 97% of all workers become productive.", "A secret study proves every company saves money.", "Remote work always solves every problem."], 0,
      "A coordinator could finish a report during saved commuting time. Đây là ví dụ giả định cụ thể không dùng dữ liệu bịa.", ["Đúng: ví dụ giả định cụ thể và được báo hiệu bằng could.", "Con số tuyệt đối không có nguồn.", "Secret study là bằng chứng bịa và không kiểm chứng.", "Always/every problem là khẳng định quá mức."]),
    question("writing-opinion-4", "What is the best use of the conclusion?", ["Restate the position and main consequence", "Introduce a completely new reason", "Copy the full introduction", "Apologize for the essay"], 0,
      "Restate the position and main consequence closes the argument without adding an undeveloped idea.", ["Đúng: kết luận khẳng định lại lập trường và hệ quả.", "Lý do mới chưa được phát triển.", "Chép nguyên mở bài gây lặp máy móc.", "Không cần xin lỗi về bài viết."]),
  ],
  "lo-trinh-toeic-450-len-550": [
    question("score-450-550-1", "Which starting record gives the most useful evidence for planning a 450-to-550 study cycle?", ["A recent result with separate Listening and Reading data", "A friend's total score", "A remembered score from an unknown quiz", "The number of books owned"], 0,
      "A recent result with separate Listening and Reading data gives the clearest starting evidence for choosing a weak section.", ["Đúng: dữ liệu gần đây theo từng phần giúp chọn ưu tiên.", "Điểm của người khác không mô tả lỗi của bạn.", "Bài không rõ nguồn và điều kiện là đường cơ sở yếu.", "Số sách không đo năng lực hay loại lỗi."]),
    question("score-450-550-2", "You understand every word after opening the transcript but missed them in the audio. What is the primary error label?", ["Sound recognition", "Unknown vocabulary", "Reading inference", "Typing speed"], 0,
      "Sound recognition is the primary label because the words are known in print but were not recognized in speech.", ["Đúng: biết chữ nhưng không nhận ra âm là lỗi nhận diện âm.", "Unknown vocabulary không phù hợp vì người học đã hiểu mọi từ.", "Reading inference không giải thích việc bỏ lỡ audio.", "Typing speed không liên quan tới Listening."]),
    question("score-450-550-3", "What should normally happen before reducing the time limit for a new question type?", ["Explain why the correct and incorrect options work", "Memorize the option letters", "Read the answer key first", "Skip all review"], 0,
      "Explain why the correct and incorrect options work before adding speed pressure to a new question type.", ["Đúng: thao tác đúng phải có trước tốc độ.", "Nhớ chữ cái không chuyển giao sang câu mới.", "Xem đáp án trước làm sai dữ liệu chẩn đoán.", "Bỏ review khiến lỗi tiếp tục lặp lại."]),
    question("score-450-550-4", "Which Part 7 habit creates the strongest review evidence?", ["Mark the line or lines that support each answer", "Choose the option sharing one word with the text", "Translate every word before reading the question", "Count only the final percentage"], 0,
      "Mark the line or lines that support each answer so that correct choices and guesses can be separated.", ["Đúng: bằng chứng giúp kiểm tra cả đáp án đúng do đoán.", "Từ trùng có thể là bẫy và chưa chứng minh cùng nghĩa.", "Dịch mọi từ thường không cần thiết để tìm bằng chứng.", "Tỷ lệ tổng không cho biết vì sao đúng hoặc sai."]),
  ],
  "lo-trinh-toeic-550-len-650": [
    question("score-550-650-1", "Which option best paraphrases “The shipment has been postponed”?", ["The delivery has been delayed.", "The order has been canceled permanently.", "The package has already arrived.", "The invoice has been paid."], 0,
      "The delivery has been delayed. This preserves both the shipment/delivery idea and the postponed/delayed relationship.", ["Đúng: delivery tương ứng shipment và delayed tương ứng postponed.", "Postponed không có nghĩa hủy vĩnh viễn.", "Already arrived trái với việc bị hoãn.", "Thanh toán hóa đơn là một sự kiện khác."]),
    question("score-550-650-2", "A learner knows the grammar but repeatedly runs out of time in Part 7. Which audit label is most useful?", ["Timing", "Pronunciation", "Handwriting", "Speaking fluency"], 0,
      "Timing is the most useful audit label when knowledge is available but the section is not completed.", ["Đúng: vấn đề được quan sát là không hoàn thành trong thời gian.", "Pronunciation không được đánh giá trong Part 7.", "Handwriting không phải thao tác làm bài đọc này.", "Speaking fluency không giải thích tốc độ Reading."]),
    question("score-550-650-3", "What makes a mixed Part 5 set useful after a labeled grammar lesson?", ["It tests whether you can identify the rule without being told", "It guarantees the same questions on test day", "It removes the need to review mistakes", "It converts raw answers directly into an official score"], 0,
      "It tests whether you can identify the rule without being told, which is closer to transfer than another labeled set.", ["Đúng: bài trộn kiểm tra khả năng tự nhận dạng.", "Không thể bảo đảm câu giống ngày thi.", "Bài trộn vẫn cần review lỗi.", "Câu luyện không quy đổi trực tiếp thành điểm chính thức."]),
    question("score-550-650-4", "During a Listening simulation, you miss one answer. What is the best next action?", ["Mark a provisional choice and re-enter at the next question", "Pause the audio until you recover every word", "Keep thinking about the missed item through the next passage", "Open the transcript immediately"], 0,
      "Mark a provisional choice and re-enter at the next question to prevent one missed item from causing more losses.", ["Đúng: chuyển tiếp bảo vệ các câu tiếp theo.", "Pause audio không mô phỏng điều kiện nghe liên tục.", "Giữ chú ý ở câu cũ dễ làm lỡ thêm nội dung.", "Transcript chỉ nên dùng ở bước chữa sau lượt nghe."]),
  ],
  "lo-trinh-toeic-650-len-800": [
    question("score-650-800-1", "What is the safest method for an inference question across two documents?", ["Combine explicit evidence from both sources", "Add a likely fact from personal experience", "Choose the longest option", "Rely on one repeated word"], 0,
      "Combine explicit evidence from both sources and make only the conclusion that the evidence supports.", ["Đúng: suy luận phải nối bằng chứng có trong tài liệu.", "Kinh nghiệm ngoài bài có thể tạo kết luận không được hỗ trợ.", "Độ dài đáp án không chứng minh tính đúng.", "Một từ lặp lại có thể là bẫy."]),
    question("score-650-800-2", "Easy errors rise sharply only near the end of a long mock. Which priority does this pattern suggest?", ["Stamina and end-of-test routines", "Learning the alphabet", "Speaking pronunciation", "Memorizing that mock's answers"], 0,
      "Stamina and end-of-test routines are the priority when accuracy drops mainly late in a long session.", ["Đúng: vị trí lỗi cho thấy chất lượng giảm theo thời lượng.", "Alphabet không giải thích lỗi tăng về cuối.", "Pronunciation không phải kỹ năng được đo ở bài L&R.", "Nhớ đáp án không sửa sức bền trên bài mới."]),
    question("score-650-800-3", "Which error note is more actionable than writing “careless”?", ["Missed “instead” and kept the original plan", "Need to be more careful", "Bad luck", "The question was annoying"], 0,
      "Missed “instead” and kept the original plan identifies the exact signal and processing error to practise.", ["Đúng: ghi chú nêu tín hiệu bị bỏ lỡ và hậu quả.", "More careful không chỉ ra hành vi cần đổi.", "Bad luck không tạo bài luyện tiếp theo.", "Cảm giác về câu hỏi không phân loại lỗi."]),
    question("score-650-800-4", "Which result is the strongest evidence that a skill transferred?", ["Fewer repeat errors on unseen questions", "A perfect score after repeating the same set", "Remembering all option letters", "Finishing a familiar passage faster"], 0,
      "Fewer repeat errors on unseen questions is the strongest evidence that the improved process works beyond memorized material.", ["Đúng: câu mới kiểm tra khả năng chuyển giao.", "Làm lại cùng bộ dễ đo trí nhớ.", "Nhớ chữ cái không chứng minh hiểu.", "Đoạn quen nhanh hơn có thể do đã thuộc nội dung."]),
  ],
  "thi-toeic-tren-may-tinh-hay-tren-giay": [
    question("exam-format-choice-1", "What is the most reliable way to choose between computer and paper delivery?", ["Compare two rehearsals using unseen, similar material", "Choose the format a friend prefers", "Assume computer delivery is easier", "Repeat one familiar set in both formats"], 0,
      "Compare two rehearsals using unseen, similar material to measure accuracy, unfinished items, fatigue and handling errors.", ["Đúng: hai lượt với câu mới tạo dữ liệu sát với thao tác của bạn.", "Sở thích của bạn bè không đo trải nghiệm của bạn.", "Hình thức không tự quyết định độ dễ.", "Bộ quen đo cả trí nhớ nên làm sai so sánh."]),
    question("exam-format-choice-2", "A score appears after a computer-based test. What should you verify next for a job application?", ["Which official document the employer accepts and when it is available", "Whether a handwritten note is enough", "Whether friends believe the score", "How to publish the score publicly"], 0,
      "Which official document the employer accepts and when it is available must be verified because a displayed score is not automatically the required document.", ["Đúng: nơi nhận quyết định loại giấy tờ và deadline.", "Ghi tay không phải mặc nhiên là tài liệu hợp lệ.", "Ý kiến bạn bè không thay quy định hồ sơ.", "Đăng công khai vừa không cần thiết vừa có thể lộ dữ liệu."]),
    question("exam-format-choice-3", "Which measurement is useful in a screen-versus-paper Reading rehearsal?", ["Correct answers, unfinished items and times you lose your place", "The color of the desk", "The number of tabs open for answer keys", "How quickly you remember familiar answers"], 0,
      "Correct answers, unfinished items and times you lose your place capture both performance and format-specific handling costs.", ["Đúng: ba số này phản ánh chất lượng và thao tác.", "Màu bàn không giúp chọn hình thức.", "Không nên mở đáp án trong lượt mô phỏng.", "Nhớ câu quen không đo khả năng xử lý câu mới."]),
    question("exam-format-choice-4", "Before paying for a test slot, which source should control the delivery format and location?", ["The current registration record and confirmation", "An old blog screenshot", "A rumor in a study group", "A different test center's schedule"], 0,
      "The current registration record and confirmation should control because availability and arrangements can vary by slot and location.", ["Đúng: đơn hiện tại gắn với ca bạn chọn.", "Ảnh cũ có thể đã hết hiệu lực.", "Tin truyền miệng không xác nhận ca cụ thể.", "Lịch nơi khác không quyết định đơn của bạn."]),
  ],
  "thi-toeic-bao-lau-co-ket-qua": [
    question("result-timeline-1", "Which three milestones should be separated when planning a TOEIC application deadline?", ["Score known, document ready, document received", "Study started, book bought, pen chosen", "Account made, password changed, browser closed", "Breakfast, lunch, dinner"], 0,
      "Score known, document ready, document received are distinct milestones and may occur on different dates.", ["Đúng: biết điểm và có giấy trong tay không luôn cùng lúc.", "Các hoạt động học không tạo timeline nhận hồ sơ.", "Thao tác tài khoản không phải ba mốc kết quả.", "Ba bữa ăn không liên quan quy trình trả điểm."]),
    question("result-timeline-2", "If IIG states five working days, what should you exclude when the notice says so?", ["Weekends and public holidays", "Every afternoon", "All weekdays", "The test date plus every calendar day"], 0,
      "Weekends and public holidays should be excluded when the notice defines the period in working days that way.", ["Đúng: ngày làm việc khác ngày lịch.", "Buổi chiều không tự bị loại khỏi cách tính.", "Loại mọi ngày trong tuần khiến không thể tính.", "Cộng ngày lịch bỏ qua định nghĩa ngày làm việc."]),
    question("result-timeline-3", "A computer screen shows your score immediately, but the university asks for a hard-copy score report. What controls the deadline?", ["When the accepted hard-copy document can reach the university", "The moment the number appeared", "When you tell a friend", "When you take a screenshot"], 0,
      "When the accepted hard-copy document can reach the university controls completion of that application requirement.", ["Đúng: deadline gắn với giấy tờ được chấp nhận đến nơi.", "Điểm hiện chưa chắc hoàn tất yêu cầu bản cứng.", "Nói với bạn không nộp hồ sơ.", "Ảnh chụp không tự trở thành phiếu điểm được chấp nhận."]),
    question("result-timeline-4", "Which details make a result-status inquiry easier to resolve?", ["Registration code, test date, location and delivery method", "Your study playlist", "A public photo of your identity document", "Only the words “Where is it?”"], 0,
      "Registration code, test date, location and delivery method identify the relevant test record without relying on a vague question.", ["Đúng: dữ liệu ca thi giúp hỗ trợ tìm đúng hồ sơ.", "Playlist không liên quan trạng thái kết quả.", "Không nên đăng công khai giấy tờ tùy thân.", "Câu hỏi quá mơ hồ không xác định được hồ sơ."]),
  ],
  "lich-thi-toeic-cach-tra-cuu-chon-ngay": [
    question("exam-schedule-1", "Where should you check which TOEIC slots are currently open in your area?", ["The current official registration portal", "A saved screenshot from last year", "A friend's calendar", "An unrelated test provider"], 0,
      "The current official registration portal is the appropriate source for live area, test and slot availability.", ["Đúng: lịch còn chỗ là dữ liệu thay đổi theo thời điểm.", "Ảnh năm trước không phản ánh chỗ hiện tại.", "Lịch cá nhân của bạn bè không phải lịch thi.", "Nhà cung cấp khác không quản lý ca IIG đang chọn."]),
    question("exam-schedule-2", "What is the safest direction for choosing a test date for an application?", ["Work backward from the document deadline", "Choose the nearest date without checking readiness", "Start from a random weekend", "Ignore result delivery time"], 0,
      "Work backward from the document deadline, subtracting result and delivery time and adding a safety margin.", ["Đúng: deadline hồ sơ là mốc quyết định cuối.", "Ngày gần nhất có thể không đủ chuẩn bị hoặc nhận giấy.", "Cuối tuần ngẫu nhiên không phản ánh lịch còn chỗ.", "Bỏ thời gian trả giấy tạo nguy cơ nộp muộn."]),
    question("exam-schedule-3", "What should you do if a desired slot does not appear after applying the correct filters?", ["Recheck later or contact the official support channel", "Assume TOEIC has been permanently canceled", "Pay a stranger to create a slot", "Register for a different test by mistake"], 0,
      "Recheck later or contact the official support channel because open slots are updated and vary by area and test.", ["Đúng: lịch có thể được cập nhật thêm.", "Một ca không hiện không chứng minh bài thi bị dừng.", "Không nên đưa tiền hoặc dữ liệu cho người lạ.", "Đăng ký nhầm bài không giải quyết nhu cầu hồ sơ."]),
    question("exam-schedule-4", "Which item belongs in a pre-payment check?", ["Test name, location, date, services and total amount", "Only the page color", "A predicted score from a ten-question quiz", "Another candidate's identity number"], 0,
      "Test name, location, date, services and total amount should all be checked before payment is finalized.", ["Đúng: đây là các trường quyết định đơn đăng ký và chi phí.", "Màu giao diện không xác nhận ca thi.", "Quiz ngắn không thay thông tin đơn.", "Số giấy tờ của người khác không liên quan và là dữ liệu nhạy cảm."]),
  ],
};

export function practiceForSlug(slug: string): MiniQuestion[] {
  if (slug === "seo-word-form") return MINI_PRACTICE["loai-tu-trong-toeic-part-5"];
  if (slug === "seo-tenses") return MINI_PRACTICE["thi-va-dang-dong-tu-toeic"];
  // This published seven-question sample has a fixed syllabus. Adding a topic
  // exercise must not silently change its question count or advertised scope.
  if (slug === "seo-part5-practice") return [
    "loai-tu-trong-toeic-part-5", "thi-va-dang-dong-tu-toeic", "hoa-hop-chu-ngu-dong-tu-toeic",
    "gioi-tu-toeic-trong-cong-viec", "lien-tu-va-tu-noi-toeic", "menh-de-quan-he-toeic", "tu-vung-toeic-theo-chu-de-cong-so",
  ].map(topic => MINI_PRACTICE[topic][0]);
  return MINI_PRACTICE[slug] ?? [];
}
