import { useState } from "react";
import { KeyboardAvoidingView, Platform, StyleSheet, Text, TextInput, View } from "react-native";
import { Redirect } from "expo-router";
import { useAuth } from "@/auth/auth-context";
import { ErrorBanner, PrimaryButton, Screen, Title } from "@/components/ui";
import { colors, radius, space } from "@/theme";
export default function SignIn() {
  const auth = useAuth(); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  if (!auth.loading && auth.token) return <Redirect href="/(tabs)" />;
  async function submit() { setBusy(true); setError(null); try { await auth.signIn(email.trim(), password); } catch (cause) { setError(cause instanceof Error ? cause.message : "Không thể đăng nhập."); } finally { setBusy(false); } }
  return <KeyboardAvoidingView behavior={Platform.OS === "ios" ? "padding" : undefined} style={styles.flex}><Screen contentContainerStyle={styles.screen}><View style={styles.brand}><Text style={styles.eyebrow}>TOEIC GYM</Text><Title>Luyện đúng phần cần cải thiện.</Title><Text style={styles.copy}>Đăng nhập bằng cùng tài khoản trên web để tiếp tục lịch sử học tập của bạn.</Text></View>{error ? <ErrorBanner message={error} /> : null}<View style={styles.form}><Text style={styles.label}>Email</Text><TextInput accessibilityLabel="Email" autoCapitalize="none" autoComplete="email" inputMode="email" onChangeText={setEmail} placeholder="ban@example.com" style={styles.input} value={email} /><Text style={styles.label}>Mật khẩu</Text><TextInput accessibilityLabel="Mật khẩu" autoCapitalize="none" autoComplete="current-password" onChangeText={setPassword} onSubmitEditing={() => void submit()} secureTextEntry style={styles.input} value={password} /><PrimaryButton busy={busy} disabled={!email.trim() || !password} label="Đăng nhập" onPress={() => void submit()} /><Text style={styles.note}>Google trên mobile sẽ được bổ sung sau khi backend PKCE exchange sẵn sàng. Ứng dụng không dùng WebView hay lấy cookie trình duyệt.</Text></View></Screen></KeyboardAvoidingView>;
}
const styles = StyleSheet.create({ flex: { flex: 1, backgroundColor: colors.paper }, screen: { flexGrow: 1, justifyContent: "center", width: "100%", maxWidth: 520, alignSelf: "center", padding: space.lg, gap: space.xl }, brand: { gap: space.md }, eyebrow: { color: colors.forest, fontWeight: "800", letterSpacing: 2, fontSize: 13 }, copy: { color: colors.muted, fontSize: 17, lineHeight: 26 }, form: { gap: space.sm }, label: { color: colors.ink, fontSize: 16, fontWeight: "700", marginTop: space.sm }, input: { minHeight: 52, borderWidth: 1, borderColor: colors.rule, borderRadius: radius.md, backgroundColor: colors.surface, color: colors.ink, fontSize: 16, paddingHorizontal: space.md }, note: { color: colors.muted, fontSize: 14, lineHeight: 21, marginTop: space.sm } });
