var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/test/payments/confirm/route.js")
R.c("server/chunks/[root-of-the-server]__1u17ts2._.js")
R.c("server/chunks/_11tqc4z._.js")
R.c("server/chunks/node_modules_next_1zdbrne._.js")
R.c("server/chunks/[root-of-the-server]__00_hq9v._.js")
R.c("server/chunks/_0zicn60._.js")
R.c("server/chunks/_0pq3p4i._.js")
R.c("server/chunks/_00y5nb3._.js")
R.c("server/chunks/_next-internal_server_app_api_test_payments_confirm_route_actions_18lt1ee.js")
R.m(61552)
module.exports=R.m(61552).exports
