import { afterEach, describe, expect, it, vi } from "vitest";
vi.mock("server-only",()=>({}));
import { getPaymentProvider, PayOSPaymentProvider } from "./provider";
afterEach(()=>vi.unstubAllEnvs());
describe("payOS adapter",()=>{
  it("maps requests through the official client boundary",async()=>{const create=vi.fn().mockResolvedValue({checkoutUrl:"https://pay.payos.vn/x",paymentLinkId:"link-1"});const get=vi.fn().mockResolvedValue({id:"link-1",amount:59000,status:"PAID"});const cancel=vi.fn().mockResolvedValue({status:"CANCELLED"});const verify=vi.fn().mockResolvedValue({orderCode:123,amount:59000,currency:"VND",paymentLinkId:"link-1",reference:"ref-1",code:"00"});const adapter=new PayOSPaymentProvider({clientId:"test",apiKey:"test",checksumKey:"test"},{paymentRequests:{create,get,cancel} as never,webhooks:{verify} as never});const expiresAt=new Date("2030-01-01T00:00:00Z");expect(await adapter.create({orderCode:123,amountVnd:59000,description:"TG123",returnUrl:"https://toeicgym.net/billing/return",cancelUrl:"https://toeicgym.net/billing/cancel",expiresAt})).toEqual({checkoutUrl:"https://pay.payos.vn/x",providerPaymentId:"link-1"});expect(create).toHaveBeenCalledWith(expect.objectContaining({orderCode:123,amount:59000,description:"TG123",returnUrl:"https://toeicgym.net/billing/return",cancelUrl:"https://toeicgym.net/billing/cancel",expiredAt:Math.floor(expiresAt.getTime()/1000)}));expect((await adapter.verifyWebhook({signed:true})).eventKey).toBe("123:ref-1");expect(verify).toHaveBeenCalledOnce();expect((await adapter.getStatus(123)).status).toBe("PAID");expect(await adapter.cancel(123)).toBe("CANCELLED")});
  it("forbids Fake provider in production",()=>{vi.stubEnv("NODE_ENV","production");vi.stubEnv("PAYMENT_PROVIDER","FAKE");expect(()=>getPaymentProvider()).toThrow("FAKE_PAYMENT_PROVIDER_FORBIDDEN")});
  it("loads configured payOS server-side",()=>{vi.stubEnv("NODE_ENV","test");vi.stubEnv("PAYMENT_PROVIDER","PAYOS");vi.stubEnv("PAYOS_CLIENT_ID","configured");vi.stubEnv("PAYOS_API_KEY","configured");vi.stubEnv("PAYOS_CHECKSUM_KEY","configured");expect(getPaymentProvider().name).toBe("PAYOS")});
  it("propagates official invalid-signature rejection",async()=>{const verify=vi.fn().mockRejectedValue(new Error("InvalidSignatureError"));const adapter=new PayOSPaymentProvider({clientId:"test",apiKey:"test",checksumKey:"test"},{paymentRequests:{} as never,webhooks:{verify} as never});await expect(adapter.verifyWebhook({signature:"invalid"})).rejects.toThrow("InvalidSignatureError")});
});
