import Link from "next/link";
import { notFound } from "next/navigation";
import { AdminNav } from "@/components/admin/admin-nav";
import { requireAdmin } from "@/lib/admin/authorization";
import { getAdminUser, getLearningSummary, getUserOperations } from "@/lib/admin/service";
import { getUsageStatus } from "@/lib/entitlements/service";
import { getPreferences } from "@/lib/i18n/get-translations";
import { getToeicProgress } from "@/lib/progress/queries";

export default async function LearnerSnapshotPage({params}:{params:Promise<{userId:string}>}){
  const actor=await requireAdmin("USER_READ"); const {userId}=await params; const [prefs,user,summary,progress,usage,ops]=await Promise.all([getPreferences(actor.id),getAdminUser(userId),getLearningSummary(userId),getToeicProgress(userId),getUsageStatus(userId),getUserOperations(userId)]); if(!user) notFound(); const vi=prefs.interfaceLanguage==="vi";
  return <main className="min-h-screen bg-[#f3f7f5] px-4 py-6 text-slate-900 sm:px-6"><div className="mx-auto max-w-6xl"><AdminNav locale={prefs.interfaceLanguage}/><Link className="mt-7 inline-flex font-bold text-teal-800" href={`/admin/users/${userId}?tab=overview`}>← {vi?"Quay lại hồ sơ hỗ trợ":"Back to support profile"}</Link><header className="mt-5 rounded-3xl bg-slate-900 p-6 text-white sm:p-8"><p className="text-xs font-black uppercase tracking-[.2em] text-teal-300">{vi?"Chế độ Admin chỉ đọc":"Read-only admin view"}</p><h1 className="mt-2 text-3xl font-black">{vi?"Hồ sơ người học":"Learner snapshot"}</h1><p className="mt-2 text-slate-300">{user.name??user.email} · {vi?"Không chuyển danh tính, không tạo hoạt động và không thay đổi dữ liệu.":"No identity switching, activity creation, or data mutation."}</p></header>
    <section className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[[vi?"Câu đã trả lời":"Answered",summary.answeredQuestions],[vi?"Độ chính xác":"Accuracy",summary.accuracy===null?"—":`${summary.accuracy}%`],[vi?"Lỗi chưa xử lý":"Unresolved",summary.unresolvedMistakes],[vi?"Bài đã nộp":"Submitted",summary.submittedSessions]].map(([k,v])=><article className="rounded-2xl border bg-white p-5" key={k}><p className="text-sm text-slate-500">{k}</p><p className="mt-1 text-2xl font-black">{v}</p></article>)}</section>
    <div className="mt-5 grid gap-5 lg:grid-cols-2"><section className="rounded-2xl border bg-white p-6"><h2 className="text-xl font-black">Listening & Reading</h2>{[progress.listening,progress.reading].map(area=><div className="mt-5" key={area.skillArea}><div className="flex justify-between"><strong>{area.skillArea==="LISTENING"?"Listening":"Reading"}</strong><span>{area.accuracy===null?"—":`${area.accuracy}% · ${area.attemptedCount} ${vi?"câu":"questions"}`}</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full bg-teal-600" style={{width:`${area.accuracy??0}%`}}/></div></div>)}</section><section className="rounded-2xl border bg-white p-6"><h2 className="text-xl font-black">{vi?"Hạn mức hiện tại":"Current quota"}</h2><ul className="mt-4 space-y-3">{Object.entries(usage.entitlements).map(([key,item])=><li className="flex justify-between rounded-xl bg-slate-50 p-3" key={key}><span>{key.replaceAll("_"," ")}</span><strong>{item.type==="UNLIMITED"?(vi?"Không giới hạn":"Unlimited"):`${item.used}/${item.limit}`}</strong></li>)}</ul></section></div>
    <section className="mt-5 rounded-2xl border bg-white p-6"><h2 className="text-xl font-black">{vi?"Hoạt động học gần đây":"Recent learning activity"}</h2>{ops.recentLearning.length?<ul className="mt-3 divide-y">{ops.recentLearning.slice(0,5).map(x=><li className="flex justify-between gap-4 py-3" key={x.id}><span>{x.part?`Part ${x.part}`:x.skillArea}</span><strong>{x.correct??0}/{x.total??0}</strong></li>)}</ul>:<p className="mt-3 text-slate-600">{vi?"Chưa có hoạt động học đã nộp.":"No submitted learning activity yet."}</p>}</section>
  </div></main>;
}
