import { and, eq, sql } from "drizzle-orm";
import { gamificationEvents, studyStreaks } from "@/db/schema";
import { GAMIFICATION_CATALOG } from "./catalog";
import { addLocalDays, getVietnamLocalDate } from "./time";
type Tx = Parameters<Parameters<typeof import("@/db").db.transaction>[0]>[0];
type Source = "PRACTICE_SESSION"|"DIAGNOSTIC_RUN"|"FULL_MOCK_RUN"|"CHALLENGE_RUN";
export async function awardCompletedLearning(tx: Tx, input: { userId: string | null; sourceType: Source; sourceId: string; questionIds: string[]; completion?: "WORKOUT"|"MASTERY"|"DIAGNOSTIC"|"FULL_MOCK"|"READING_100"|"LISTENING_100"|"FULL_200"; now?: Date }) {
  if (!input.userId) return; const now=input.now??new Date(); const localDate=getVietnamLocalDate(now); await tx.execute(sql`select pg_advisory_xact_lock(hashtextextended(${`${input.userId}:${localDate}:gamification`},0))`);
  const existing=await tx.select().from(gamificationEvents).where(and(eq(gamificationEvents.userId,input.userId),eq(gamificationEvents.localDate,localDate))); let daily=existing.reduce((n,e)=>n+e.rankPointsAwarded,0); const qCount=existing.filter(e=>e.eventType==="QUESTION"&&e.rankPointsAwarded>0).length;
  const insert=async(eventType:string,xp:number,desired:number,questionId?:string)=>{const rank=Math.max(0,Math.min(desired,GAMIFICATION_CATALOG.dailyRankPointsCap-daily));if(!xp&&!rank)return;const rows=await tx.insert(gamificationEvents).values({userId:input.userId!,eventType,sourceType:input.sourceType,sourceId:input.sourceId,questionId,localDate,xpAwarded:xp,rankPointsAwarded:rank,createdAt:now}).onConflictDoNothing().returning({rank:gamificationEvents.rankPointsAwarded});if(rows.length)daily+=rows[0].rank;};
  const [streak]=await tx.select().from(studyStreaks).where(eq(studyStreaks.userId,input.userId)).for("update").limit(1); let streakDays=streak?.currentDays??0; if(streak?.lastStudyDate!==localDate){streakDays=streak?.lastStudyDate===addLocalDays(localDate,-1)?streakDays+1:1;await tx.insert(studyStreaks).values({userId:input.userId,currentDays:streakDays,bestDays:Math.max(streak?.bestDays??0,streakDays),lastStudyDate:localDate,updatedAt:now}).onConflictDoUpdate({target:studyStreaks.userId,set:{currentDays:streakDays,bestDays:Math.max(streak?.bestDays??0,streakDays),lastStudyDate:localDate,updatedAt:now}});await insert("STUDY_DAY",0,GAMIFICATION_CATALOG.studyDayRankPoints);await insert("STREAK",0,Math.min(streakDays,GAMIFICATION_CATALOG.streakRankPointsCap));}
  const seen=new Set(existing.filter(e=>e.questionId&&e.rankPointsAwarded>0).map(e=>e.questionId!));let remaining=Math.max(0,GAMIFICATION_CATALOG.questionDailyCap-qCount);for(const id of [...new Set(input.questionIds)]){const rank=!seen.has(id)&&remaining>0?GAMIFICATION_CATALOG.questionRankPoints:0;if(rank)remaining--;await insert("QUESTION",GAMIFICATION_CATALOG.questionXp,rank,id);}
  if(input.completion){const map={WORKOUT:["WORKOUT_COMPLETE",10,10],MASTERY:["MASTERY_COMPLETE",10,10],DIAGNOSTIC:["DIAGNOSTIC_COMPLETE",20,0],FULL_MOCK:["FULL_MOCK_COMPLETE",50,0],READING_100:["CHALLENGE_COMPLETE",25,0],LISTENING_100:["CHALLENGE_COMPLETE",25,0],FULL_200:["CHALLENGE_COMPLETE",50,0]} as const;const [type,xp,rp]=map[input.completion];const already=(type==="WORKOUT_COMPLETE"||type==="MASTERY_COMPLETE")&&existing.some(e=>e.eventType===type);if(!already)await insert(type,xp,rp);}
}
