import Link from "next/link";
import { AdminNav } from "@/components/admin/admin-nav";
import { PendingSubmit } from "@/components/admin/pending-submit";
import { requireAdmin } from "@/lib/admin/authorization";
import { listAdminContent } from "@/lib/admin/content";
import { getPreferences } from "@/lib/i18n/get-translations";
import { publishAllDraftsAction, unarchiveAllContentAction } from "../actions";

const filterKeys = ["domain", "part", "lifecycle", "difficulty", "skill", "subSkill", "provenance", "batch", "setType", "search"] as const;

export default async function Page({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) {
  const q = await searchParams;
  const actor = await requireAdmin("CONTENT_READ");
  const prefs = await getPreferences(actor.id);
  const data = await listAdminContent({ search: q.search, domain: q.domain, part: q.part ? Number(q.part) : undefined, lifecycle: q.lifecycle, difficulty: q.difficulty, skill: q.skill, subSkill: q.subSkill, provenance: q.provenance, batch: q.batch, setType: q.setType, page: Number(q.page) || 1 });
  const context = new URLSearchParams();
  filterKeys.forEach((key) => { if (q[key]) context.set(key, q[key]!); });
  const exportParams = new URLSearchParams(context);
  if (q.part) exportParams.set("part", q.part);
  const bulkFields = [...context].filter(([key]) => key !== "lifecycle");

  return <main className="min-h-screen bg-slate-50 px-4 py-6"><div className="mx-auto max-w-7xl"><AdminNav locale={prefs.interfaceLanguage}/>
    <div className="mt-8 flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-widest text-teal-700">Content operations</p><h1 className="text-3xl font-black">Ngân hàng câu hỏi</h1><p className="mt-1 text-slate-600">Lọc, review, import và xuất nội dung TOEIC.</p></div><div className="flex gap-2"><Link href="/admin/content/import" className="rounded-lg border bg-white px-4 py-2 font-bold">Import JSON</Link><Link href="/admin/content/new" className="rounded-lg bg-teal-700 px-4 py-2 font-bold text-white">Tạo Draft</Link></div></div>
    <form className="mt-5 grid gap-3 rounded-2xl border bg-white p-4 md:grid-cols-4"><input aria-label="Tìm kiếm" name="search" defaultValue={q.search} placeholder="Tìm nội dung hoặc ID" className="rounded-lg border p-2"/><select aria-label="Domain" name="domain" defaultValue={q.domain ?? ""} className="rounded-lg border p-2"><option value="">Mọi domain</option><option>LISTENING</option><option>READING</option></select><select aria-label="Part" name="part" defaultValue={q.part ?? ""} className="rounded-lg border p-2"><option value="">Mọi part</option>{[1,2,3,4,5,6,7].map((part) => <option key={part}>{part}</option>)}</select><select aria-label="Trạng thái" name="lifecycle" defaultValue={q.lifecycle ?? ""} className="rounded-lg border p-2"><option value="">Mọi trạng thái</option><option value="draft">Draft</option><option value="published">Published</option><option value="archived">Archived</option></select><input name="skill" defaultValue={q.skill} placeholder="Skill" className="rounded-lg border p-2"/><input name="subSkill" defaultValue={q.subSkill} placeholder="Subskill" className="rounded-lg border p-2"/><select name="difficulty" defaultValue={q.difficulty ?? ""} className="rounded-lg border p-2"><option value="">Mọi độ khó</option><option>easy</option><option>medium</option><option>hard</option></select><input type="hidden" name="setType" value={q.setType ?? ""}/><input name="batch" defaultValue={q.batch} placeholder="Batch key" className="rounded-lg border p-2"/><select name="provenance" defaultValue={q.provenance ?? ""} className="rounded-lg border p-2"><option value="">Mọi nguồn</option><option>SEEDED</option><option>ADMIN</option></select><button className="rounded-lg bg-slate-900 p-2 font-bold text-white">Áp dụng bộ lọc</button><Link href="/admin/content/questions" className="rounded-lg border p-2 text-center font-semibold">Xóa lọc</Link></form>
    {(q.operation || q.bulkError) && <div className={`mt-4 rounded-xl border p-4 ${q.bulkError ? "border-red-200 bg-red-50 text-red-900" : "border-emerald-200 bg-emerald-50 text-emerald-900"}`}>{q.bulkError ? `Thao tác thất bại: ${q.bulkError}` : q.operation === "publish-all" ? `Đã duyệt ${q.published ?? 0}/${q.processed ?? 0} Draft. ${q.failed ?? 0} mục không hợp lệ được giữ nguyên.` : `Đã khôi phục ${q.unarchived ?? 0}/${q.processed ?? 0} mục lưu trữ; đã xóa ${q.duplicatesDeleted ?? 0} bản trùng. ${q.failed ?? 0} mục lỗi được giữ nguyên.`}</div>}
    <div className="mt-4 flex flex-wrap items-center justify-between gap-3 rounded-xl border border-teal-200 bg-teal-50 p-4"><p><strong>{data.totalQuestions}</strong> câu hỏi trong {data.total} nhóm khớp bộ lọc{q.part ? ` · Part ${q.part}` : ""}</p>{q.part ? <a href={`/api/admin/content-export?${exportParams}`} className="rounded-lg bg-teal-700 px-4 py-2 font-bold text-white">Export {data.totalQuestions} câu · JSON</a> : <span className="text-sm text-slate-600">Chọn Part để bật Export JSON.</span>}</div>
    <div className="mt-4 flex flex-wrap gap-3 rounded-xl border bg-white p-3"><form action={publishAllDraftsAction}>{bulkFields.map(([key, value]) => <input type="hidden" name={key} value={value} key={key}/>)}<PendingSubmit className="rounded-lg bg-teal-700 px-4 py-2 font-bold text-white" confirmMessage="Duyệt toàn bộ Draft khớp bộ lọc hiện tại?" pendingLabel="Đang duyệt…">Duyệt toàn bộ Draft</PendingSubmit></form><form action={unarchiveAllContentAction}>{bulkFields.map(([key, value]) => <input type="hidden" name={key} value={value} key={key}/>)}<PendingSubmit className="rounded-lg border border-slate-400 bg-white px-4 py-2 font-bold text-slate-900" confirmMessage="Khôi phục toàn bộ nội dung Archived khớp bộ lọc? Bản trùng hoàn toàn sẽ bị xóa." pendingLabel="Đang khôi phục…">Unarchive toàn bộ</PendingSubmit></form></div>
    <form action="/api/admin/content-export" className="mt-5"><input type="hidden" name="scope" value="selected"/><div className="flex flex-wrap items-center gap-2 rounded-t-xl border bg-white p-3">{[...exportParams].map(([key, value]) => <input type="hidden" name={key} value={value} key={key}/>)}<button className="rounded-lg border bg-white px-3 py-2 font-bold" disabled={!q.part} type="submit">Xuất mục đã chọn</button></div><div className="overflow-x-auto rounded-b-2xl border bg-white"><table className="w-full min-w-[900px] text-left"><thead><tr className="border-b bg-slate-100 text-sm uppercase tracking-wide text-slate-600"><th className="p-3"><span className="sr-only">Chọn</span></th><th className="p-3">Nội dung</th><th>Domain / Part</th><th>Trạng thái</th><th>Nguồn / Batch</th><th>Số câu</th><th>Thao tác</th></tr></thead><tbody>{data.rows.map((row) => { const href = `/admin/content/questions/${row.id}${context.size ? `?${context}` : ""}`; return <tr key={row.id} className="border-b align-top hover:bg-slate-50"><td className="p-3"><input aria-label={`Chọn ${row.title}`} name="id" type="checkbox" value={row.id}/></td><td className="p-3"><Link className="font-bold text-teal-700" href={href}>{row.title}</Link><small className="block text-slate-500">Cập nhật {row.updatedAt.toLocaleString()}</small></td><td className="py-3">{row.domain} · P{row.part}<br/><span className="text-sm text-slate-500">{row.setType}</span></td><td className="py-3"><span className={`rounded-full px-2 py-1 text-xs font-bold ${row.lifecycle === "draft" ? "bg-amber-100 text-amber-900" : row.lifecycle === "published" ? "bg-emerald-100 text-emerald-900" : "bg-slate-200 text-slate-700"}`}>{row.lifecycle.toUpperCase()}</span></td><td className="py-3">{row.provenance}{row.batchKey && <><br/><Link className="text-sm font-semibold text-teal-700 underline" href={`/admin/content/batches/${encodeURIComponent(row.batchKey)}`}>{row.batchKey}</Link></>}</td><td className="py-3">{row.questions}</td><td className="py-3"><Link className="font-bold text-teal-700" href={href}>Review →</Link></td></tr>; })}</tbody></table>{!data.rows.length && <p className="p-8 text-center text-slate-500">Không có nội dung phù hợp.</p>}</div></form><p className="mt-4">Trang {data.page} · {data.total} kết quả</p>
    <nav aria-label="Phân trang" className="mt-3 flex gap-3">{data.page > 1 && <Link className="rounded-lg border bg-white px-4 py-2 font-bold" href={`/admin/content/questions?${new URLSearchParams({ ...Object.fromEntries(context), page: String(data.page - 1) })}`}>← Trước</Link>}{data.page * data.pageSize < data.total && <Link className="rounded-lg border bg-white px-4 py-2 font-bold" href={`/admin/content/questions?${new URLSearchParams({ ...Object.fromEntries(context), page: String(data.page + 1) })}`}>Tiếp →</Link>}</nav>
  </div></main>;
}
