import Link from "next/link";
import { AdminNav } from "@/components/admin/admin-nav";
import { requireAdmin } from "@/lib/admin/authorization";
import { listAdminUsers } from "@/lib/admin/service";
import { getPreferences } from "@/lib/i18n/get-translations";

export default async function UsersPage({ searchParams }: { searchParams: Promise<{ q?: string; page?: string }> }) {
  const actor = await requireAdmin("USER_READ"); const preferences = await getPreferences(actor.id); const vi = preferences.interfaceLanguage === "vi"; const params = await searchParams; const page = Math.max(1, Number.parseInt(params.page ?? "1") || 1); const q = params.q ?? ""; const data = await listAdminUsers(q, page); const pages = Math.max(1, Math.ceil(data.total / data.pageSize));
  return <main className="min-h-screen bg-slate-50 px-4 py-6 text-slate-900 sm:px-6"><div className="mx-auto max-w-6xl"><AdminNav locale={preferences.interfaceLanguage} /><div className="mt-8 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-black">{vi ? "Người dùng" : "Users"}</h1><p className="mt-2 text-slate-600">{data.total} {vi ? "kết quả" : "results"}</p></div><form className="flex gap-2" method="get"><label className="sr-only" htmlFor="user-search">{vi ? "Tìm theo email hoặc tên" : "Search by email or name"}</label><input className="min-h-11 rounded-xl border border-slate-300 bg-white px-4" defaultValue={q} id="user-search" name="q" placeholder={vi ? "Email hoặc tên" : "Email or name"}/><button className="rounded-xl bg-slate-900 px-5 font-bold text-white">{vi ? "Tìm" : "Search"}</button></form></div><div className="mt-6 overflow-x-auto rounded-2xl border border-slate-200 bg-white"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-100"><tr>{[vi?"Email":"Email",vi?"Tên":"Name",vi?"Trạng thái":"Status",vi?"Gói":"Plan",vi?"Ngày tạo":"Created",vi?"Đăng nhập cuối":"Last login"].map(x=><th className="p-4" key={x}>{x}</th>)}</tr></thead><tbody>{data.rows.map(user=><tr className="border-t border-slate-100" key={user.id}><td className="p-4"><Link className="font-bold text-teal-700" href={`/admin/users/${user.id}`}>{user.email}</Link></td><td className="p-4">{user.name ?? "—"}</td><td className="p-4">{user.status}</td><td className="p-4 font-bold">{user.premium?"PREMIUM":"FREE"}</td><td className="p-4">{user.createdAt.toLocaleDateString(preferences.interfaceLanguage)}</td><td className="p-4">{user.lastLoginAt?.toLocaleString(preferences.interfaceLanguage) ?? "—"}</td></tr>)}</tbody></table>{!data.rows.length?<p className="p-8 text-center text-slate-500">{vi?"Không tìm thấy người dùng.":"No users found."}</p>:null}</div><nav className="mt-5 flex items-center justify-between" aria-label="Pagination"><Link aria-disabled={page<=1} className={`rounded-lg border px-4 py-2 font-semibold ${page<=1?"pointer-events-none opacity-40":""}`} href={`?q=${encodeURIComponent(q)}&page=${page-1}`}>{vi?"Trước":"Previous"}</Link><span>{page} / {pages}</span><Link aria-disabled={page>=pages} className={`rounded-lg border px-4 py-2 font-semibold ${page>=pages?"pointer-events-none opacity-40":""}`} href={`?q=${encodeURIComponent(q)}&page=${page+1}`}>{vi?"Sau":"Next"}</Link></nav></div></main>;
}
