import Link from "next/link";
import { AdminNav } from "@/components/admin/admin-nav";
import { requireAdmin } from "@/lib/admin/authorization";
import { getAdminOverview, listAdminUsers } from "@/lib/admin/service";
import { getPreferences } from "@/lib/i18n/get-translations";

type Query = { q?: string; plan?: string; status?: string; role?: string; verified?: string; activity?: string; sort?: string; page?: string };
const date = (value: Date | null, locale: string, withTime = false) => value ? new Intl.DateTimeFormat(locale, { timeZone: "Asia/Ho_Chi_Minh", day: "2-digit", month: "2-digit", year: "numeric", ...(withTime ? { hour: "2-digit", minute: "2-digit" } : {}) }).format(value) : "—";
const statusLabel = (status: string, vi: boolean) => status === "active" ? (vi ? "Đang hoạt động" : "Active") : status === "disabled" ? (vi ? "Tạm khóa" : "Suspended") : (vi ? "Chờ xác minh" : "Pending verification");
const tone = (status: string) => status === "active" ? "bg-emerald-50 text-emerald-800" : status === "disabled" ? "bg-red-50 text-red-800" : "bg-amber-50 text-amber-800";

export default async function UsersPage({ searchParams }: { searchParams: Promise<Query> }) {
  const actor = await requireAdmin("USER_READ"); const [prefs, query, overview] = await Promise.all([getPreferences(actor.id), searchParams, getAdminOverview()]); const vi = prefs.interfaceLanguage === "vi"; const locale = vi ? "vi-VN" : "en-US";
  const page = Math.max(1, Number.parseInt(query.page ?? "1") || 1); const data = await listAdminUsers({ search: query.q, plan: query.plan, status: query.status, role: query.role, verified: query.verified, activity: query.activity, sort: query.sort, page }); const pages = Math.ceil(data.total / data.pageSize);
  const href = (nextPage: number) => { const p = new URLSearchParams(); Object.entries(query).forEach(([k,v]) => { if (v && k !== "page") p.set(k,v); }); p.set("page", String(nextPage)); return `?${p}`; };
  const hasFilters = Boolean(query.q || query.plan || query.status || query.role || query.verified || query.activity || query.sort); const select = "mt-1 min-h-11 w-full rounded-xl border border-slate-300 bg-white px-3 text-sm";
  return <main className="min-h-screen bg-slate-50 px-4 py-6 text-slate-900 sm:px-6"><div className="mx-auto max-w-7xl"><AdminNav locale={prefs.interfaceLanguage}/>
    <header className="mt-8"><p className="text-xs font-black uppercase tracking-[.18em] text-teal-700">{vi?"Vận hành & hỗ trợ":"Operations & support"}</p><h1 className="mt-2 text-3xl font-black">{vi?"Người dùng":"Users"}</h1><p className="mt-2 text-slate-600">{vi?"Quản lý tài khoản, quyền truy cập và trạng thái học tập.":"Manage accounts, access, and learning status."}</p></header>
    <section aria-label={vi?"Tổng quan người dùng":"User overview"} className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[[vi?"Tổng người dùng":"Total users",overview.total],["Premium",overview.premium],[vi?"Đã tạm khóa":"Suspended",overview.suspended],[vi?"Chưa xác minh":"Unverified",overview.unverified]].map(([label,value])=><article className="rounded-2xl border border-slate-200 bg-white p-4" key={label}><p className="text-sm text-slate-500">{label}</p><p className="mt-1 text-2xl font-black">{value}</p></article>)}</section>
    <form className="mt-6 rounded-2xl border border-slate-200 bg-white p-4" method="get"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><div className="xl:col-span-2"><label className="text-sm font-bold" htmlFor="user-search">{vi?"Tìm kiếm":"Search"}</label><input className="mt-1 min-h-11 w-full rounded-xl border border-slate-300 px-4" defaultValue={query.q} id="user-search" name="q" placeholder={vi?"Tìm theo email hoặc tên":"Search by email or name"}/></div>
      <label className="text-sm font-bold">{vi?"Gói":"Plan"}<select className={select} defaultValue={query.plan??""} name="plan"><option value="">{vi?"Tất cả":"All"}</option><option value="free">Free</option><option value="premium">Premium</option></select></label>
      <label className="text-sm font-bold">{vi?"Trạng thái":"Status"}<select className={select} defaultValue={query.status??""} name="status"><option value="">{vi?"Tất cả":"All"}</option><option value="active">{vi?"Đang hoạt động":"Active"}</option><option value="disabled">{vi?"Tạm khóa":"Suspended"}</option><option value="pending_verification">{vi?"Chờ xác minh":"Pending verification"}</option></select></label>
      <label className="text-sm font-bold">{vi?"Vai trò":"Role"}<select className={select} defaultValue={query.role??""} name="role"><option value="">{vi?"Tất cả":"All"}</option><option value="learner">Learner</option><option value="admin">Admin</option></select></label>
      <label className="text-sm font-bold">{vi?"Xác minh email":"Email verification"}<select className={select} defaultValue={query.verified??""} name="verified"><option value="">{vi?"Tất cả":"All"}</option><option value="yes">{vi?"Đã xác minh":"Verified"}</option><option value="no">{vi?"Chưa xác minh":"Unverified"}</option></select></label>
      <label className="text-sm font-bold">{vi?"Hoạt động":"Activity"}<select className={select} defaultValue={query.activity??""} name="activity"><option value="">{vi?"Tất cả":"All"}</option><option value="recent">{vi?"Đăng nhập trong 30 ngày":"Logged in within 30 days"}</option><option value="never">{vi?"Chưa từng đăng nhập":"Never logged in"}</option></select></label>
      <label className="text-sm font-bold">{vi?"Sắp xếp":"Sort"}<select className={select} defaultValue={query.sort??"created"} name="sort"><option value="created">{vi?"Mới tạo gần đây":"Recently created"}</option><option value="login">{vi?"Đăng nhập gần nhất":"Last login"}</option><option value="identity">Email A–Z</option></select></label></div><div className="mt-4 flex flex-wrap gap-3"><button className="min-h-11 rounded-xl bg-slate-900 px-5 font-bold text-white">{vi?"Áp dụng":"Apply"}</button>{hasFilters?<Link className="inline-flex min-h-11 items-center rounded-xl border px-5 font-bold" href="/admin/users">{vi?"Xóa bộ lọc":"Clear filters"}</Link>:null}</div></form>
    {data.rows.length ? <div className="mt-5 overflow-x-auto rounded-2xl border border-slate-200 bg-white"><table className="w-full min-w-[840px] text-left text-sm"><thead className="bg-slate-100"><tr>{[vi?"Người dùng":"User",vi?"Vai trò":"Role",vi?"Trạng thái":"Status",vi?"Gói":"Plan",vi?"Ngày tạo":"Created",vi?"Đăng nhập gần nhất":"Last login"].map(x=><th className="p-4" scope="col" key={x}>{x}</th>)}</tr></thead><tbody>{data.rows.map(user=><tr className="border-t border-slate-100 hover:bg-slate-50" key={user.id}><td className="p-4"><Link className="font-bold text-teal-800 underline-offset-2 hover:underline" href={`/admin/users/${user.id}`}>{user.name??(vi?"Chưa đặt tên":"Unnamed user")}</Link><p className="mt-1 max-w-[18rem] truncate text-slate-500">{user.email}</p>{actor.id===user.id?<span className="mt-2 inline-flex rounded-full bg-blue-50 px-2 py-1 text-xs font-bold text-blue-800">{vi?"Bạn":"You"}</span>:null}</td><td className="p-4"><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold">{user.admin?"Admin":"Learner"}</span></td><td className="p-4"><span className={`rounded-full px-3 py-1 text-xs font-bold ${tone(user.status)}`}>{statusLabel(user.status,vi)}</span></td><td className="p-4"><span className={`rounded-full px-3 py-1 text-xs font-bold ${user.premium?"bg-teal-50 text-teal-800":"bg-slate-100 text-slate-700"}`}>{user.premium?"Premium":"Free"}</span></td><td className="p-4 whitespace-nowrap">{date(user.createdAt,locale)}</td><td className="p-4 whitespace-nowrap">{user.lastLoginAt?date(user.lastLoginAt,locale,true):(vi?"Chưa đăng nhập":"Never")}</td></tr>)}</tbody></table></div> : <section className="mt-5 rounded-2xl border border-dashed bg-white p-10 text-center"><h2 className="text-xl font-black">{hasFilters?(vi?"Không tìm thấy người dùng phù hợp.":"No matching users."):(vi?"Chưa có người dùng.":"No users yet.")}</h2><p className="mt-2 text-slate-600">{hasFilters?(vi?"Thử tên, email khác hoặc xóa bộ lọc.":"Try another name or email, or clear the filters."):(vi?"Tài khoản sẽ xuất hiện tại đây khi được tạo.":"Accounts will appear here once created.")}</p>{hasFilters?<Link className="mt-5 inline-flex rounded-xl bg-slate-900 px-5 py-3 font-bold text-white" href="/admin/users">{vi?"Xóa bộ lọc":"Clear filters"}</Link>:null}</section>}
    {data.total>0&&pages>1?<nav aria-label={vi?"Phân trang người dùng":"User pages"} className="mt-5 flex items-center justify-between"><Link aria-disabled={page<=1} className={`rounded-lg border bg-white px-4 py-2 font-semibold ${page<=1?"pointer-events-none opacity-40":""}`} href={href(page-1)}>{vi?"Trước":"Previous"}</Link><span>{page} / {pages}</span><Link aria-disabled={page>=pages} className={`rounded-lg border bg-white px-4 py-2 font-semibold ${page>=pages?"pointer-events-none opacity-40":""}`} href={href(page+1)}>{vi?"Sau":"Next"}</Link></nav>:null}
  </div></main>;
}
