import Link from "next/link";
import {AdminNav} from "@/components/admin/admin-nav";
import {requireAdmin} from "@/lib/admin/authorization";
import {listAuditLogs} from "@/lib/admin/service";
import {getPreferences} from "@/lib/i18n/get-translations";

const actions:Record<string,[string,string]>={ADMIN_ROLE_GRANTED:["Đã cấp quyền quản trị","Admin role granted"],ADMIN_ROLE_REVOKED:["Đã thu hồi quyền quản trị","Admin role revoked"],USER_SUSPENDED:["Đã tạm khóa người dùng","User suspended"],USER_REACTIVATED:["Đã mở khóa người dùng","User reactivated"],PREMIUM_GRANTED:["Đã cấp Premium","Premium granted"],PREMIUM_REVOKED:["Đã thu hồi Premium","Premium revoked"],CONTENT_DRAFT_CREATED:["Đã tạo bản nháp học liệu","Content draft created"],CONTENT_DRAFT_UPDATED:["Đã cập nhật bản nháp học liệu","Content draft updated"],CONTENT_CLONED:["Đã nhân bản học liệu","Content cloned"],CONTENT_PUBLISHED:["Đã xuất bản học liệu","Content published"],CONTENT_ARCHIVED:["Đã lưu trữ học liệu","Content archived"],CONTENT_DRAFT_DISCARDED:["Đã bỏ bản nháp học liệu","Content draft discarded"],MEDIA_UPLOADED:["Đã tải media lên","Media uploaded"],CHALLENGE_DRAFT_CREATED:["Đã tạo nháp sự kiện","Event draft created"],CHALLENGE_FORM_GENERATED:["Đã tạo đề sự kiện","Event test generated"],CHALLENGE_PUBLISHED:["Đã công bố sự kiện","Event published"],CHALLENGE_CANCELLED:["Đã hủy sự kiện","Event cancelled"],SEO_POST_CREATED:["Đã tạo bài viết","Post created"],SEO_POST_UPDATED:["Đã cập nhật bài viết","Post updated"],SEO_POST_PUBLISHED:["Đã xuất bản bài viết","Post published"],SEO_POST_UNPUBLISHED:["Đã gỡ bài viết","Post unpublished"],SEO_POST_DELETED:["Đã xóa bài viết","Post deleted"],IMPORT_VALIDATED:["Đã kiểm tra tệp nhập","Import validated"],IMPORT_COMMITTED:["Đã nhập bộ câu hỏi","Question batch imported"],IMPORT_FAILED:["Nhập câu hỏi thất bại","Question import failed"]};
function safeMetadata(value:unknown){if(!value||typeof value!=="object"||Array.isArray(value))return [];return Object.entries(value).filter(([key,v])=>/^(challengeId|type|questions|batchId|batchKey|postId|contentId|mediaId|count|status)$/i.test(key)&&["string","number","boolean"].includes(typeof v));}
export default async function AuditPage({searchParams}:{searchParams:Promise<{page?:string}>}){const actor=await requireAdmin("AUDIT_READ");const p=await getPreferences(actor.id);const vi=p.interfaceLanguage==="vi";const q=await searchParams;const page=Math.min(100000,Math.max(1,Number.parseInt(q.page??"1")||1));const data=await listAuditLogs(page);const pages=Math.max(1,Math.ceil(data.total/data.pageSize));return <main className="min-h-screen bg-slate-50 px-4 py-6 text-slate-900 sm:px-6"><div className="mx-auto max-w-6xl"><AdminNav locale={p.interfaceLanguage}/><h1 className="mt-8 text-3xl font-black">{vi?"Nhật ký quản trị":"Audit log"}</h1><p className="mt-2 text-slate-600">{vi?"Các thay đổi quản trị gần đây. Mở từng dòng để xem mã sự kiện và thông tin an toàn.":"Recent admin changes. Open an entry for its event code and safe details."}</p><div className="mt-6 grid gap-3">{data.rows.map(row=>{const details=safeMetadata(row.metadata);return <article className="rounded-xl border bg-white p-4" key={row.id}><div className="flex flex-wrap items-start justify-between gap-2"><div><h2 className="font-bold">{actions[row.action]?.[vi?0:1]??(vi?"Hành động quản trị":"Admin action")}</h2><p className="mt-1 text-sm text-slate-600">{row.actorEmail??(vi?"Hệ thống":"System")} · {row.createdAt.toLocaleString(vi?"vi-VN":"en-US",{timeZone:"Asia/Ho_Chi_Minh"})} (GMT+7)</p></div><span className="text-sm text-slate-600">{row.targetEmail??(row.targetUserId?`${vi?"Người dùng":"User"}: ${row.targetUserId}`:"")}</span></div><details className="mt-3 text-sm"><summary className="cursor-pointer font-semibold text-teal-700">{vi?"Xem chi tiết":"View details"}</summary><dl className="mt-3 grid gap-2 rounded-lg bg-slate-50 p-3"><div><dt className="font-semibold">{vi?"Mã sự kiện":"Event code"}</dt><dd className="break-all">{row.action}</dd></div><div><dt className="font-semibold">ID</dt><dd className="break-all">{row.id}</dd></div>{details.map(([key,value])=><div key={key}><dt className="font-semibold">{key}</dt><dd className="break-all">{String(value)}</dd></div>)}</dl></details></article>})}{!data.rows.length?<div className="rounded-xl border bg-white p-8"><h2 className="font-bold">{vi?"Chưa có hoạt động nào":"No activity yet"}</h2><p className="mt-2 text-slate-600">{vi?"Thao tác quản trị sẽ xuất hiện ở đây khi được ghi nhận.":"Recorded admin actions will appear here."}</p></div>:null}</div><nav aria-label={vi?"Trang nhật ký":"Audit pages"} className="mt-5 flex justify-between"><Link aria-disabled={page<=1} className={page<=1?"pointer-events-none opacity-40":""} href={`?page=${page-1}`}>{vi?"Trước":"Previous"}</Link><span>{page} / {pages}</span><Link aria-disabled={page>=pages} className={page>=pages?"pointer-events-none opacity-40":""} href={`?page=${page+1}`}>{vi?"Sau":"Next"}</Link></nav></div></main>}
