var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/admin/posts/cover/route.js")
R.c("server/chunks/[root-of-the-server]__06y_wl9._.js")
R.c("server/chunks/_0xisrkt._.js")
R.c("server/chunks/_0400ysv._.js")
R.c("server/chunks/_00y5nb3._.js")
R.c("server/chunks/_0pq3p4i._.js")
R.c("server/chunks/[root-of-the-server]__0qqi26o._.js")
R.c("server/chunks/src_lib_media_ingestion_ts_1bddge5._.js")
R.c("server/chunks/_next-internal_server_app_api_admin_posts_cover_route_actions_1naffyc.js")
R.m(27847)
module.exports=R.m(27847).exports
