import Link from "next/link";
import { notFound } from "next/navigation";
import { AdminNav } from "@/components/admin/admin-nav";
import { ConfirmSubmit } from "@/components/admin/confirm-submit";
import { PendingSubmit } from "@/components/admin/pending-submit";
import { requireAdmin } from "@/lib/admin/authorization";
import { getAdminContentDetail, getImportContextForGroup, getReviewQueue, type ReviewFilters } from "@/lib/admin/content";
import { getPreferences } from "@/lib/i18n/get-translations";
import { archiveContentAction, cloneContentAction, discardDraftAction, publishAndNextAction, publishContentAction, validateContentAction } from "../../actions";

const filterKeys=["domain","part","setType","lifecycle","difficulty","skill","subSkill","provenance","batch"] as const;
export default async function Page({params,searchParams}:{params:Promise<{id:string}>,searchParams:Promise<Record<string,string|undefined>>}){
  const actor=await requireAdmin("CONTENT_READ"),prefs=await getPreferences(actor.id),{id}=await params,q=await searchParams,d=await getAdminContentDetail(id);if(!d)notFound();
  const filters:ReviewFilters={domain:q.domain,part:q.part?Number(q.part):d.group.toeicPart,setType:q.setType,lifecycle:q.lifecycle??(d.group.status==="draft"?"draft":undefined),difficulty:q.difficulty,skill:q.skill,subSkill:q.subSkill,provenance:q.provenance,batch:q.batch};
  const [queue,batch]=await Promise.all([getReviewQueue(id,filters),getImportContextForGroup(id)]); const query=new URLSearchParams(); filterKeys.forEach(k=>{const v=filters[k];if(v!==undefined)query.set(k,String(v))});
  const hidden=<><input type="hidden" name="id" value={id}/><input type="hidden" name="updatedAt" value={d.group.updatedAt.toISOString()}/>{[...query].map(([k,v])=><input key={k} type="hidden" name={k} value={v}/>)}</>; const link=(target:string)=>`/admin/content/questions/${target}?${query}`;
  return <main className="min-h-screen bg-slate-50 px-4 py-6 pb-28"><div className="mx-auto max-w-6xl"><AdminNav locale={prefs.interfaceLanguage}/>
    <nav aria-label="Breadcrumb" className="mt-6 text-sm text-slate-600"><Link href="/admin/content/questions" className="underline">Ngân hàng câu hỏi</Link>{batch&&<> / <Link href={`/admin/content/batches/${encodeURIComponent(batch.batchKey)}`} className="underline">{batch.batchKey}</Link></>}</nav>
    <header className="mt-4 grid gap-5 rounded-2xl border bg-white p-6 lg:grid-cols-[1fr_auto]"><div><p className="font-bold uppercase tracking-widest text-teal-700">{d.group.skillArea} · PART {d.group.toeicPart} · {d.group.setType}</p><div className="mt-2 flex flex-wrap items-center gap-3"><h1 className="text-3xl font-black">{d.group.title}</h1><span className={`rounded-full px-3 py-1 text-xs font-black ${d.group.status==="draft"?"bg-amber-100 text-amber-900":d.group.status==="published"?"bg-emerald-100 text-emerald-900":"bg-slate-200"}`}>{d.group.status.toUpperCase()}</span></div><dl className="mt-4 grid gap-x-6 gap-y-2 text-sm sm:grid-cols-2"><div><dt className="font-bold text-slate-500">Batch / nguồn</dt><dd>{batch?<Link className="text-teal-700 underline" href={`/admin/content/batches/${encodeURIComponent(batch.batchKey)}`}>{batch.batchKey} · {batch.externalItemId}</Link>:d.group.provenance}</dd></div><div><dt className="font-bold text-slate-500">Thời gian</dt><dd>Tạo {d.group.createdAt.toLocaleString()}<br/>Cập nhật {d.group.updatedAt.toLocaleString()}</dd></div></dl></div><div className="rounded-xl bg-slate-100 p-4 text-center"><p className="text-sm font-bold text-slate-500">REVIEW QUEUE</p><p className="mt-1 text-2xl font-black">{queue.position??"—"} / {queue.total}</p><p className="text-sm">{queue.total-(queue.position??queue.total)} còn phía sau</p></div></header>
    {q.error&&<p role="alert" aria-live="assertive" className="mt-4 rounded-lg bg-red-100 p-3 text-red-800">Không thể thực hiện: {decodeURIComponent(q.error).split("|").join(" · ")}</p>}{q.validation&&<p role="alert" className="mt-4 rounded-lg bg-amber-100 p-3">Validation FAIL: {q.validation.split("|").join(" · ")}</p>}{q.valid&&<p className="mt-4 rounded-lg bg-emerald-100 p-3">Validation PASS</p>}{q.published&&<p className="mt-4 rounded-lg bg-emerald-100 p-3">Đã publish thành công.</p>}{q.queueEnd&&<p className="mt-4 rounded-lg bg-blue-100 p-3">Đã đến cuối hàng đợi review.</p>}
    {(d.passages.length>0||d.transcript)&&<section className="mt-6 rounded-2xl border bg-white p-5"><h2 className="text-xl font-black">{d.transcript?"Transcript":"Passage"}</h2>{d.passages.map((p,i)=><article key={p.id} className="mt-4"><h3 className="text-sm font-bold uppercase text-slate-500">Tài liệu {i+1}{p.title?` · ${p.title}`:""}</h3><div className="mt-2 whitespace-pre-wrap rounded-lg bg-slate-50 p-4 leading-7">{p.content}</div></article>)}{d.transcript&&<div className="mt-3 whitespace-pre-wrap rounded-lg bg-slate-50 p-4 leading-7">{d.transcript.content}</div>}</section>}
    <div className="mt-4 flex flex-wrap gap-2"><Link className="rounded-lg bg-teal-700 px-4 py-2 font-bold text-white" href={`/admin/content/questions/${encodeURIComponent(id)}/preview`}>Xem như người học →</Link>{d.group.status==="draft"&&<Link className="rounded-lg border bg-white px-4 py-2 font-bold" href={`/admin/content/questions/${encodeURIComponent(id)}/edit`}>Sửa bản nháp</Link>}<a className="rounded-lg border bg-white px-4 py-2 font-bold" href={`/api/admin/content-export?part=${d.group.toeicPart}`}>Xuất JSON Part {d.group.toeicPart}</a></div><div className="mt-6 space-y-5">{d.questions.map((item,i)=><section key={item.id} className="rounded-2xl border bg-white p-5"><div className="flex flex-wrap justify-between gap-3"><h2 className="text-lg font-black">Câu {i+1}. {item.questionText||<span className="italic text-slate-500">Nghe audio và chọn đáp án</span>}</h2><div className="flex gap-2 text-xs font-bold"><span className="rounded-full bg-blue-50 px-2 py-1">{item.skill} / {item.subSkill}</span><span className="rounded-full bg-violet-50 px-2 py-1">{item.difficulty}</span></div></div><ol className="mt-4 grid gap-2 sm:grid-cols-2">{item.options.map(o=><li key={o.id} className={`rounded-lg border p-3 ${o.id===item.solution?.correctOptionId?"border-emerald-400 bg-emerald-50 font-bold text-emerald-900":""}`}><span className="mr-2 font-black">{o.optionKey}.</span>{o.optionText}{o.id===item.solution?.correctOptionId&&<span className="ml-2 text-xs">✓ ĐÚNG</span>}</li>)}</ol><div className="mt-4 grid gap-3 lg:grid-cols-2"><div className="rounded-lg bg-slate-50 p-3"><h3 className="font-bold">Giải thích EN</h3><p className="mt-1 leading-6">{item.solution?.explanationEn}</p></div><div className="rounded-lg bg-slate-50 p-3"><h3 className="font-bold">Giải thích VI</h3><p className="mt-1 leading-6">{item.solution?.explanationVi}</p></div></div></section>)}</div>
    <div className="fixed inset-x-0 bottom-0 z-20 border-t bg-white/95 p-3 shadow-[0_-8px_30px_rgba(15,23,42,.12)] backdrop-blur"><div className="mx-auto flex max-w-6xl flex-wrap items-center justify-between gap-2"><div className="flex gap-2">{queue.previous?<Link className="rounded-lg border bg-white px-4 py-2 font-bold focus:ring-2" href={link(queue.previous.id)}>← Previous</Link>:<span className="rounded-lg border px-4 py-2 text-slate-400">← Previous</span>}{queue.next?<Link className="rounded-lg border bg-white px-4 py-2 font-bold focus:ring-2" href={link(queue.next.id)}>Skip / Next →</Link>:<span className="rounded-lg border px-4 py-2 text-slate-400">End of queue</span>}</div><div className="flex flex-wrap gap-2">{d.group.status==="draft"&&<><form action={validateContentAction}>{hidden}<PendingSubmit className="rounded-lg border bg-white px-4 py-2 font-bold">Validate</PendingSubmit></form><form action={publishContentAction}>{hidden}<PendingSubmit confirmMessage="Publish nội dung này?" className="rounded-lg border border-teal-700 bg-white px-4 py-2 font-bold text-teal-800">Publish</PendingSubmit></form><form action={publishAndNextAction}>{hidden}<PendingSubmit confirmMessage="Publish và chuyển sang nội dung kế tiếp?" pendingLabel="Đang publish…" className="rounded-lg bg-teal-700 px-4 py-2 font-bold text-white">Publish & Next →</PendingSubmit></form><form action={discardDraftAction}>{hidden}<ConfirmSubmit message="Discard bản nháp này?" className="rounded-lg border bg-white px-4 py-2 font-bold">Discard</ConfirmSubmit></form></>}{d.group.status==="published"&&<form action={archiveContentAction}>{hidden}<ConfirmSubmit message="Archive nội dung đã xuất bản? Hệ thống sẽ chặn nếu ảnh hưởng Full Mock." className="rounded-lg border bg-white px-4 py-2 font-bold">Archive</ConfirmSubmit></form>}{d.group.status!=="draft"&&<form action={cloneContentAction}>{hidden}<PendingSubmit className="rounded-lg border bg-white px-4 py-2 font-bold">Clone as Draft</PendingSubmit></form>}</div></div></div>
  </div></main>;
}
