import "server-only";
import { and, desc, eq, inArray } from "drizzle-orm";
import { db } from "@/db";
import { attemptAnswers, demoTestAnswers, practiceSessionQuestions, practiceSessions, questionSolutions } from "@/db/schema";
import { percentage } from "@/lib/analytics/calculate";
import { getSafeSessionContent } from "@/lib/practice/queries";
import type { DemoSubmissionReason, DemoTestResult, DemoTestSession } from "./types";

async function ownedDemo(sessionId: string, userId: string) { return (await db.select().from(practiceSessions).where(and(eq(practiceSessions.id, sessionId), eq(practiceSessions.userId, userId), eq(practiceSessions.practiceType, "demo_test"))).limit(1))[0] ?? null; }
export async function getActiveDemoTest(userId: string) { const [row] = await db.select({ id: practiceSessions.id, expiresAt: practiceSessions.expiresAt }).from(practiceSessions).where(and(eq(practiceSessions.userId, userId), eq(practiceSessions.practiceType, "demo_test"), eq(practiceSessions.status, "in_progress"))).orderBy(desc(practiceSessions.createdAt)).limit(1); return row?.expiresAt ? { id: row.id, expires_at: row.expiresAt.toISOString() } : null; }
export async function getDemoTestSession(sessionId: string, userId: string): Promise<DemoTestSession | null | "submitted" | "expired"> { const session = await ownedDemo(sessionId, userId); if (!session) return null; if (session.status === "submitted") return "submitted"; if (session.status !== "in_progress" || !session.expiresAt) return null; if (session.expiresAt.getTime() <= Date.now()) return "expired"; const [content, answers] = await Promise.all([getSafeSessionContent(session.id), db.select().from(demoTestAnswers).where(and(eq(demoTestAnswers.sessionId, session.id), eq(demoTestAnswers.userId, userId)))]); if (content.questions.length !== 100) throw new Error("DEMO_LOAD_FAILED"); return { id: session.id, status: "in_progress", startedAt: session.startedAt.toISOString(), expiresAt: session.expiresAt.toISOString(), questionCount: 100, ...content, answers: Object.fromEntries(answers.map((a) => [a.questionId, a.selectedOptionId])) }; }
export async function finalizeDemoTest(sessionId: string, userId: string, reason: DemoSubmissionReason) { return db.transaction(async (tx) => { const [session] = await tx.select().from(practiceSessions).where(and(eq(practiceSessions.id, sessionId), eq(practiceSessions.userId, userId), eq(practiceSessions.practiceType, "demo_test"))).for("update").limit(1); if (!session) throw new Error("DEMO_SUBMIT_FAILED"); if (session.status === "submitted") return session; if (session.status !== "in_progress" || !session.expiresAt) throw new Error("DEMO_SUBMIT_FAILED"); const assigned = await tx.select().from(practiceSessionQuestions).where(eq(practiceSessionQuestions.sessionId, sessionId)); if (assigned.length !== 100) throw new Error("DEMO_SUBMIT_FAILED"); const ids = assigned.map((a) => a.questionId); const [saved, solutions] = await Promise.all([tx.select().from(demoTestAnswers).where(and(eq(demoTestAnswers.sessionId, sessionId), eq(demoTestAnswers.userId, userId))), tx.select().from(questionSolutions).where(inArray(questionSolutions.questionId, ids))]); const answerMap = new Map(saved.map((a) => [a.questionId, a])); const solutionMap = new Map(solutions.map((s) => [s.questionId, s.correctOptionId])); let correct = 0; const rows = assigned.map((a) => { const answer = answerMap.get(a.questionId); const isCorrect = Boolean(answer && answer.selectedOptionId === solutionMap.get(a.questionId)); if (isCorrect) correct++; return { sessionId, userId, questionId: a.questionId, selectedOptionId: answer?.selectedOptionId ?? null, isCorrect, responseTimeMs: answer?.responseTimeMs ?? null, answeredAt: answer?.answeredAt ?? null }; }); await tx.insert(attemptAnswers).values(rows).onConflictDoNothing(); const finalReason = new Date() >= session.expiresAt ? "time_expired" : reason; await tx.update(practiceSessions).set({ status: "submitted", submittedAt: new Date(), scoreCorrect: correct, scoreTotal: 100, submissionReason: finalReason }).where(and(eq(practiceSessions.id, sessionId), eq(practiceSessions.status, "in_progress"))); await tx.delete(demoTestAnswers).where(eq(demoTestAnswers.sessionId, sessionId)); return { ...session, scoreCorrect: correct, scoreTotal: 100, submissionReason: finalReason }; }); }
export async function getDemoTestResult(sessionId: string, userId: string): Promise<DemoTestResult | null | "in_progress"> { const session = await ownedDemo(sessionId, userId); if (!session) return null; if (session.status === "in_progress") return "in_progress"; if (session.status !== "submitted" || session.scoreCorrect === null || session.scoreTotal !== 100 || !session.submittedAt || !session.submissionReason || !session.expiresAt) return null; const content = await getSafeSessionContent(session.id); const ids = content.questions.map((q) => q.id); const [answers, solutions] = await Promise.all([db.select().from(attemptAnswers).where(and(eq(attemptAnswers.sessionId, session.id), eq(attemptAnswers.userId, userId))), db.select().from(questionSolutions).where(inArray(questionSolutions.questionId, ids))]); const answerMap = new Map(answers.map((a) => [a.questionId, a])); const solutionMap = new Map(solutions.map((s) => [s.questionId, s])); const review = content.questions.map((q) => { const a = answerMap.get(q.id); const s = solutionMap.get(q.id); if (!a || !s) throw new Error("DEMO_RESULT_INCOMPLETE"); return { ...q, selectedOptionId: a.selectedOptionId, correctOptionId: s.correctOptionId, isCorrect: a.isCorrect, explanationEn: s.explanationEn, explanationVi: s.explanationVi }; }); const reviewMap = new Map(review.map((q) => [q.id, q])); const partResults = ([5, 6, 7] as const).map((part) => { const rows = review.filter((q) => q.part === part); const correct = rows.filter((q) => q.isCorrect).length; return { part, correct, total: rows.length, accuracy: percentage(correct, rows.length) }; }); return { id: session.id, startedAt: session.startedAt.toISOString(), expiresAt: session.expiresAt.toISOString(), submittedAt: session.submittedAt.toISOString(), submissionReason: session.submissionReason as DemoSubmissionReason, scoreCorrect: session.scoreCorrect, scoreTotal: 100, timeUsedSeconds: Math.max(0, Math.round((Math.min(session.submittedAt.getTime(), session.expiresAt.getTime()) - session.startedAt.getTime()) / 1000)), partResults, questions: review, groups: content.groups.map((group) => ({ ...group, questions: group.questions.map((q) => reviewMap.get(q.id)!) })) }; }
