import "server-only";
import { and, desc, eq, inArray, sql } from "drizzle-orm";
import { db } from "@/db";
import { passageSets, passages, practiceSessionQuestions, practiceSessions, questionOptions, questionSolutions, questions } from "@/db/schema";
import { shuffle } from "@/lib/practice/selection";
import { selectExactUnits, validateDemoComposition } from "./composition";
import type { DemoSelectionUnit } from "./types";
type Candidate = { id: string; part: 5 | 6 | 7; setId: string | null; order: number; skill: string; difficulty: string };

function choosePart5(candidates: DemoSelectionUnit[], metadata: Map<string, Candidate>, previous: Set<string>) { const ranked = shuffle(candidates).sort((a, b) => Number(previous.has(a.questionIds[0])) - Number(previous.has(b.questionIds[0])) || `${metadata.get(a.questionIds[0])!.skill}:${metadata.get(a.questionIds[0])!.difficulty}`.localeCompare(`${metadata.get(b.questionIds[0])!.skill}:${metadata.get(b.questionIds[0])!.difficulty}`)); const buckets = new Map<string, DemoSelectionUnit[]>(); for (const item of ranked) { const m = metadata.get(item.questionIds[0])!; const key = `${m.skill}:${m.difficulty}`; buckets.set(key, [...(buckets.get(key) ?? []), item]); } const selected: DemoSelectionUnit[] = []; while (selected.length < 30 && [...buckets.values()].some((b) => b.length)) for (const bucket of buckets.values()) { const next = bucket.shift(); if (next) selected.push(next); if (selected.length === 30) break; } return selected; }
function choosePart7(units: DemoSelectionUnit[]) { const by = { single: units.filter((u) => u.setType === "single"), double: units.filter((u) => u.setType === "double"), triple: units.filter((u) => u.setType === "triple") }; if (by.single.length && by.double.length && by.triple.length) for (const single of by.single) for (const double of by.double) for (const triple of by.triple) { const base = [single, double, triple]; const remaining = 54 - base.reduce((sum, u) => sum + u.questionIds.length, 0); const rest = remaining >= 0 ? selectExactUnits(units.filter((u) => !base.some((x) => x.id === u.id)), remaining) : null; if (rest) return [...base, ...rest]; } return selectExactUnits(units, 54); }

async function previousIds(userId: string) { const [prior] = await db.select({ id: practiceSessions.id }).from(practiceSessions).where(and(eq(practiceSessions.userId, userId), eq(practiceSessions.practiceType, "demo_test"), eq(practiceSessions.status, "submitted"))).orderBy(desc(practiceSessions.submittedAt)).limit(1); if (!prior) return new Set<string>(); return new Set((await db.select({ id: practiceSessionQuestions.questionId }).from(practiceSessionQuestions).where(eq(practiceSessionQuestions.sessionId, prior.id))).map((x) => x.id)); }
async function validUnits() {
  const rows = await db.select().from(questions).where(and(inArray(questions.toeicPart, [5, 6, 7]), eq(questions.status, "published"))).limit(1000); const ids = rows.map((q) => q.id); const setIds = [...new Set(rows.flatMap((q) => q.passageSetId ?? []))];
  const [opts, sols, sets, docs] = await Promise.all([db.select({ id: questionOptions.questionId }).from(questionOptions).where(inArray(questionOptions.questionId, ids)), db.select({ id: questionSolutions.questionId }).from(questionSolutions).where(inArray(questionSolutions.questionId, ids)), setIds.length ? db.select().from(passageSets).where(inArray(passageSets.id, setIds)) : [], setIds.length ? db.select().from(passages).where(inArray(passages.passageSetId, setIds)) : []]);
  const counts = new Map<string, number>(); for (const o of opts) counts.set(o.id, (counts.get(o.id) ?? 0) + 1); const solutionIds = new Set(sols.map((s) => s.id)); const candidates: Candidate[] = rows.filter((q) => counts.get(q.id) === 4 && solutionIds.has(q.id)).map((q) => ({ id: q.id, part: q.toeicPart as 5 | 6 | 7, setId: q.passageSetId, order: q.questionOrder, skill: q.skill, difficulty: q.difficulty })); const metadata = new Map(candidates.map((q) => [q.id, q]));
  const units: DemoSelectionUnit[] = candidates.filter((q) => q.part === 5).map((q) => ({ id: q.id, part: 5, setType: "standalone", questionIds: [q.id] })); const expected: Record<string, number> = { part6: 1, single: 1, double: 2, triple: 3 };
  for (const set of sets) { const setDocs = docs.filter((d) => d.passageSetId === set.id).sort((a, b) => (a.position ?? 0) - (b.position ?? 0)); if (set.status !== "published" || setDocs.length !== expected[set.setType] || setDocs.some((d, i) => d.status !== "published" || d.position !== i + 1)) continue; const all = rows.filter((q) => q.passageSetId === set.id).sort((a, b) => a.questionOrder - b.questionOrder); if (!all.length || all.some((q) => !metadata.has(q.id))) continue; units.push({ id: set.id, part: set.toeicPart as 6 | 7, setType: set.setType as DemoSelectionUnit["setType"], questionIds: all.map((q) => q.id) }); }
  return { units, metadata };
}
export async function assembleReadingDemoTest(userId: string) { const [{ units, metadata }, previous] = await Promise.all([validUnits(), previousIds(userId)]); const rank = (items: DemoSelectionUnit[]) => shuffle(items).sort((a, b) => a.questionIds.filter((id) => previous.has(id)).length - b.questionIds.filter((id) => previous.has(id)).length); const p5 = choosePart5(units.filter((u) => u.part === 5), metadata, previous); const p6 = selectExactUnits(rank(units.filter((u) => u.part === 6)), 16); const p7 = choosePart7(rank(units.filter((u) => u.part === 7))); if (p5.length !== 30 || !p6 || !p7) throw new Error("DEMO_CONTENT_INCOMPLETE"); const selected = [...p5, ...p6, ...p7]; if (!validateDemoComposition(selected)) throw new Error("DEMO_COMPOSITION_INVALID"); return selected; }
export async function createReadingDemoTest(userId: string) { return db.transaction(async (tx) => { await tx.execute(sql`select pg_advisory_xact_lock(hashtextextended(${`${userId}:reading-demo`}, 0))`); const [active] = await tx.select({ id: practiceSessions.id }).from(practiceSessions).where(and(eq(practiceSessions.userId, userId), eq(practiceSessions.practiceType, "demo_test"), eq(practiceSessions.status, "in_progress"))).limit(1); if (active) return active.id; const units = await assembleReadingDemoTest(userId); const ids = units.flatMap((u) => u.questionIds); const configured = Number(process.env.DEMO_TEST_DURATION_SECONDS); const duration = process.env.NODE_ENV !== "production" && Number.isInteger(configured) && configured >= 30 ? Math.min(configured, 4500) : 4500; const [session] = await tx.insert(practiceSessions).values({ userId, practiceType: "demo_test", part: null, questionCount: 100, source: "demo_test", requestedQuestionCount: 100, expiresAt: new Date(Date.now() + duration * 1000) }).returning({ id: practiceSessions.id }); const setByQuestion = new Map(units.flatMap((u) => u.questionIds.map((id) => [id, u.part === 5 ? null : u.id] as const))); await tx.insert(practiceSessionQuestions).values(ids.map((questionId, i) => ({ sessionId: session.id, questionId, displayOrder: i + 1, passageSetId: setByQuestion.get(questionId) }))); return session.id; }); }
