"use client";
import { useState } from "react";
import Link from "next/link";
import { savePostAction } from "@/app/admin/posts/actions";
import { CATEGORY_LABELS, POST_CATEGORIES, STATUS_LABELS, isValidSlug, slugify, type PostCategory, type PostStatus } from "@/lib/blog/core";
import { parsePostImport } from "@/lib/blog/post-import";

export type InitialPost={id?:string;title:string;slug:string;excerpt:string;content:string;category:PostCategory;seoTitle:string;seoDescription:string;canonicalPath:string;coverMediaId:string;coverAlt:string;socialTitle:string;socialDescription:string;authorName:string;targetTopic:string;searchIntent:string;noindex:boolean;tags:string;status?:PostStatus;publishedAt?:string;updatedAt?:string};
type Image={id:string;storageKey:string;imageWidth:number|null;imageHeight:number|null};
type Suggestion={id:string;title:string;slug:string;category:string;seoTitle:string|null;seoDescription:string|null};
const field="mt-1 w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm focus-visible:outline-2 focus-visible:outline-teal-700";
const panel="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm";
export function PostForm({initial,images,suggestions,siteUrl}:{initial:InitialPost;images:Image[];suggestions:Suggestion[];siteUrl:string}){
  const [title,setTitle]=useState(initial.title),[slug,setSlug]=useState(initial.slug),[manual,setManual]=useState(Boolean(initial.slug));
  const [excerpt,setExcerpt]=useState(initial.excerpt),[content,setContent]=useState(initial.content),[seoTitle,setSeoTitle]=useState(initial.seoTitle),[seoDescription,setSeoDescription]=useState(initial.seoDescription);
  const [category,setCategory]=useState(initial.category),[availableImages,setAvailableImages]=useState(images),[coverId,setCoverId]=useState(initial.coverMediaId),[coverAlt,setCoverAlt]=useState(initial.coverAlt),[noindex,setNoindex]=useState(initial.noindex);
  const [socialTitle,setSocialTitle]=useState(initial.socialTitle),[socialDescription,setSocialDescription]=useState(initial.socialDescription),[authorName,setAuthorName]=useState(initial.authorName),[canonicalPath,setCanonicalPath]=useState(initial.canonicalPath),[tab,setTab]=useState("Tổng quan");
  const [tags,setTags]=useState(initial.tags),[targetTopic,setTargetTopic]=useState(initial.targetTopic),[searchIntent,setSearchIntent]=useState(initial.searchIntent);
  const [importText,setImportText]=useState(""),[importMessage,setImportMessage]=useState(""),[coverFile,setCoverFile]=useState<File|null>(null),[uploading,setUploading]=useState(false),[uploadMessage,setUploadMessage]=useState("");
  const image=availableImages.find(x=>x.id===coverId),headings=[...content.matchAll(/^(#{1,3})\s+(.+)$/gm)],foundLinks=[...content.matchAll(/(?<!!)\[([^\]]+)\]\(([^)]+)\)/g)].map(x=>x[2]);
  const internal=foundLinks.filter(x=>x.startsWith("/")),external=foundLinks.filter(x=>/^https?:\/\//i.test(x));
  const invalid=foundLinks.filter(x=>!x.startsWith("/")&&!x.startsWith("#")&&!/^https?:\/\//i.test(x)&&!/^mailto:/i.test(x));
  const unknown=internal.filter(x=>x.startsWith("/blog/")&&!suggestions.some(p=>x===`/blog/${p.slug}`)&&x!==`/blog/${slug}`);
  const duplicateTitle=suggestions.some(x=>x.slug!==slug&&(x.seoTitle||x.title).toLocaleLowerCase()===(seoTitle||title).toLocaleLowerCase());
  const duplicateMeta=Boolean(seoDescription&&suggestions.some(x=>x.slug!==slug&&x.seoDescription?.toLocaleLowerCase()===seoDescription.toLocaleLowerCase()));
  const checks=[
    {kind:"error",text:!title.trim()?"Thiếu tiêu đề bài viết":null},{kind:"error",text:!isValidSlug(slug)?"Đường dẫn chưa hợp lệ":null},
    {kind:"error",text:!content.trim()?"Thiếu nội dung để xuất bản":null},{kind:"error",text:!excerpt.trim()?"Thiếu tóm tắt để xuất bản":null},
    {kind:"warning",text:!seoDescription.trim()?"Chưa có mô tả tìm kiếm; sẽ dùng tóm tắt":null},
    {kind:"warning",text:duplicateTitle?"Tiêu đề SEO có thể trùng bài đã xuất bản":null},{kind:"warning",text:duplicateMeta?"Mô tả tìm kiếm trùng bài đã xuất bản":null},
    {kind:"warning",text:!coverId?"Chưa chọn ảnh đại diện":null},{kind:"warning",text:coverId&&!coverAlt.trim()?"Ảnh đại diện chưa có văn bản thay thế":null},
    {kind:"warning",text:!internal.length?"Chưa có liên kết nội bộ":null},{kind:"warning",text:unknown.length?`${unknown.length} liên kết blog chưa thấy trong bài đã xuất bản`:null},
    {kind:"warning",text:invalid.length?`${invalid.length} liên kết có định dạng không an toàn`:null},
    {kind:"warning",text:headings.some((h,i)=>i>0&&h[1].length-headings[i-1][1].length>1)?"Thứ bậc tiêu đề bị nhảy cấp":null},
    {kind:"warning",text:headings.some(h=>h[1].length===1)?"Markdown có H1; trang đã dùng tiêu đề bài làm H1":null},
    {kind:"warning",text:/\b(todo|lorem ipsum|placeholder)\b/i.test(content)?"Có dấu hiệu văn bản giữ chỗ":null},
  ].filter(x=>x.text);
  const errors=checks.filter(x=>x.kind==="error").length,warnings=checks.length-errors;
  const related=suggestions.filter(x=>x.category===category||title.toLocaleLowerCase().split(/\s+/).some(word=>word.length>4&&x.title.toLocaleLowerCase().includes(word))).slice(0,5);
  function applyImport(){try{const imported=parsePostImport(importText);if((title||content)&&!window.confirm("Dữ liệu JSON sẽ ghi đè các trường bài viết hiện tại. Tiếp tục?"))return;setTitle(imported.title);setSlug(imported.slug);setManual(true);setExcerpt(imported.excerpt);setContent(imported.content);setCategory(imported.category);setTags(imported.tags);setSeoTitle(imported.seoTitle);setSeoDescription(imported.seoDescription);setCanonicalPath(imported.canonicalPath);setNoindex(imported.noindex);setSocialTitle(imported.socialTitle);setSocialDescription(imported.socialDescription);setAuthorName(imported.authorName);setTargetTopic(imported.targetTopic);setSearchIntent(imported.searchIntent);setCoverAlt(imported.coverAlt);setImportMessage("Đã nhập JSON vào bản nháp. Kiểm tra lại nội dung, tải ảnh rồi bấm Lưu bài viết.");}catch(error){setImportMessage(error instanceof Error?error.message:"Không thể đọc JSON");}}
  async function chooseImport(file?:File){if(!file)return;if(file.size>1024*1024){setImportMessage("File JSON tối đa 1 MiB");return;}const text=await file.text();setImportText(text);setImportMessage(`Đã đọc ${file.name}. Bấm Nhập vào bản nháp để áp dụng.`);}
  async function uploadCover(){if(!coverFile)return;setUploading(true);setUploadMessage("");try{const data=new FormData();data.set("file",coverFile);const response=await fetch("/api/admin/posts/cover",{method:"POST",body:data});const result=await response.json() as {image?:Image;error?:string};if(!response.ok||!result.image)throw new Error(result.error||"UPLOAD_FAILED");setAvailableImages(current=>[result.image!,...current.filter(item=>item.id!==result.image!.id)]);setCoverId(result.image.id);setCoverFile(null);setUploadMessage("Đã tải ảnh lên và chọn làm ảnh đại diện. Bấm Lưu bài viết để gắn ảnh vào draft.");}catch(error){setUploadMessage(`Tải ảnh thất bại: ${error instanceof Error?error.message:"FAILED"}`);}finally{setUploading(false);}}
  return <form action={savePostAction} className="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1fr)_340px]">
    <input name="id" type="hidden" value={initial.id}/>
    {tab!=="SEO"&&<><input type="hidden" name="seoTitle" value={seoTitle}/><input type="hidden" name="seoDescription" value={seoDescription}/><input type="hidden" name="slug" value={slug}/></>}
    {tab!=="Social"&&<><input type="hidden" name="socialTitle" value={socialTitle}/><input type="hidden" name="socialDescription" value={socialDescription}/></>}
    {tab!=="Nâng cao"&&<><input type="hidden" name="authorName" value={authorName}/><input type="hidden" name="canonicalPath" value={canonicalPath}/>{noindex&&<input type="hidden" name="noindex" value="on"/>}</>}
    <div className="min-w-0 space-y-5">
      <section className="rounded-2xl border border-teal-200 bg-gradient-to-br from-teal-50 to-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-teal-800">AI → Draft</p><h2 className="mt-1 text-lg font-black">Nhập bài viết chuẩn SEO từ JSON</h2><p className="mt-2 max-w-2xl text-sm text-slate-600">Chọn file hoặc dán JSON do AI tạo. Hệ thống chỉ điền form, không tự lưu hay xuất bản.</p></div><a className="rounded-xl border border-teal-700 bg-white px-4 py-2 text-sm font-black text-teal-800" href="/api/admin/posts/import-template">Tải JSON mẫu</a></div><label className="mt-4 block text-sm font-bold">Chọn file JSON<input className={field} type="file" accept="application/json,.json" onChange={event=>void chooseImport(event.target.files?.[0])}/></label><label className="mt-3 block text-sm font-bold">Hoặc dán JSON<textarea className={`${field} min-h-40 font-mono`} value={importText} onChange={event=>setImportText(event.target.value)} placeholder='{"schemaVersion":1,"title":"...","content":"## ..."}'/></label><button className="mt-3 rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-black text-white disabled:opacity-50" type="button" disabled={!importText.trim()} onClick={applyImport}>Nhập vào bản nháp</button>{importMessage&&<p className="mt-3 rounded-xl bg-white p-3 text-sm font-semibold text-slate-700" role="status">{importMessage}</p>}</section>
      <section className={panel}><h2 className="text-lg font-black">Nội dung bài viết</h2>
        <label className="mt-4 block text-sm font-bold">Tiêu đề<input className={field} name="title" required value={title} onChange={e=>{setTitle(e.target.value);if(!manual)setSlug(slugify(e.target.value));}}/></label>
        <label className="mt-4 block text-sm font-bold">Tóm tắt<textarea className={field} name="excerpt" rows={3} value={excerpt} onChange={e=>setExcerpt(e.target.value)}/></label>
        <label className="mt-4 block text-sm font-bold">Nội dung Markdown<textarea className={`${field} min-h-[430px] font-mono`} name="content" value={content} onChange={e=>setContent(e.target.value)}/></label>
        <p className="mt-2 text-xs text-slate-600">Hỗ trợ tiêu đề, đậm, nghiêng, liên kết, danh sách, trích dẫn, code và ảnh. HTML hiển thị như văn bản.</p>
      </section>
      <section className={panel}><h2 className="text-lg font-black">Phân loại và hình ảnh</h2><div className="mt-3 grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold">Danh mục<select className={field} name="category" value={category} onChange={e=>setCategory(e.target.value as PostCategory)}>{POST_CATEGORIES.map(x=><option key={x} value={x}>{CATEGORY_LABELS[x].vi}</option>)}</select></label><label className="text-sm font-bold">Thẻ (cách nhau bằng dấu phẩy)<input className={field} name="tags" value={tags} onChange={e=>setTags(e.target.value)}/></label></div>
        <div className="mt-4 rounded-xl border border-dashed border-slate-300 bg-slate-50 p-4"><label className="block text-sm font-bold">Tải ảnh từ máy (JPG, PNG, WebP · tối đa 5 MiB)<input className={field} type="file" accept="image/jpeg,image/png,image/webp" onChange={event=>setCoverFile(event.target.files?.[0]??null)}/></label><button className="mt-3 rounded-xl bg-teal-700 px-4 py-2.5 text-sm font-black text-white disabled:opacity-50" type="button" disabled={!coverFile||uploading} onClick={()=>void uploadCover()}>{uploading?"Đang tải ảnh…":"Tải lên và chọn ảnh"}</button>{uploadMessage&&<p className="mt-2 text-sm font-semibold text-slate-700" role="status">{uploadMessage}</p>}</div>
        <label className="mt-4 block text-sm font-bold">Ảnh đại diện từ Media<select className={field} name="coverMediaId" value={coverId} onChange={e=>setCoverId(e.target.value)}><option value="">Không có</option>{availableImages.map(x=><option key={x.id} value={x.id}>{x.storageKey}</option>)}</select></label>
        {image&&<p className="mt-2 text-xs text-slate-600">Ảnh sẵn sàng · {image.imageWidth??"?"} × {image.imageHeight??"?"} px{image.imageWidth&&image.imageWidth<1200?" · Nên cân nhắc ảnh lớn hơn cho mạng xã hội":""}</p>}
        <label className="mt-3 block text-sm font-bold">Văn bản thay thế (alt)<input className={field} name="coverAlt" value={coverAlt} onChange={e=>setCoverAlt(e.target.value)} placeholder="Mô tả ảnh có ý nghĩa; để trống nếu chỉ trang trí"/></label>
      </section>
      <section className={panel}><h2 className="text-lg font-black">Mục đích biên tập</h2><div className="mt-3 grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold">Chủ đề chính<input className={field} name="targetTopic" value={targetTopic} onChange={e=>setTargetTopic(e.target.value)}/></label><label className="text-sm font-bold">Mục đích tìm kiếm<select className={field} name="searchIntent" value={searchIntent} onChange={e=>setSearchIntent(e.target.value)}><option value="">Chưa chọn</option>{["Tìm hiểu","Hướng dẫn","So sánh","Luyện tập","Điều hướng"].map(x=><option key={x}>{x}</option>)}</select></label></div><p className="mt-2 text-xs text-slate-600">Dùng để định hướng bài viết, không dùng để đếm mật độ từ khóa.</p></section>
      <button className="min-h-12 rounded-xl bg-teal-700 px-6 font-black text-white focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-teal-700" type="submit">Lưu bài viết</button>
    </div><aside className="min-w-0 space-y-4 xl:sticky xl:top-4 xl:self-start" aria-label="Không gian SEO">
      <section className={panel}><h2 className="font-black">Xuất bản</h2><p className="mt-2 text-sm">{initial.status?STATUS_LABELS[initial.status]:"Bản nháp mới"}{noindex?" · Không lập chỉ mục":" · Có thể lập chỉ mục khi xuất bản"}</p><p className="mt-2 text-xs text-slate-500">{initial.publishedAt&&`Xuất bản: ${initial.publishedAt}`} {initial.updatedAt&&`· Cập nhật: ${initial.updatedAt}`}</p>{initial.id&&<Link className="mt-3 inline-block text-sm font-bold text-teal-700 underline" href={`/admin/posts/${initial.id}/preview`}>Xem bản đã lưu →</Link>}<p className="mt-3 text-xs text-slate-600">Lưu thay đổi trước khi xem trước hoặc xuất bản.</p></section>
      <nav aria-label="Các mục SEO" className="flex flex-wrap gap-1 rounded-xl bg-slate-100 p-1">{["Tổng quan","SEO","Liên kết","Social","Schema","Nâng cao"].map(x=><button type="button" key={x} aria-current={tab===x?"page":undefined} onClick={()=>setTab(x)} className={`rounded-lg px-2 py-2 text-xs font-bold ${tab===x?"bg-white text-teal-800 shadow":"text-slate-600"}`}>{x}</button>)}</nav>
      {tab==="Tổng quan"&&<><section className={panel}><h2 className="font-black">Kiểm tra trước xuất bản</h2><p className="mt-2 text-sm font-bold">{errors?`${errors} lỗi cần sửa`:"Sẵn sàng về mặt kỹ thuật"} · {warnings} gợi ý</p><ul className="mt-3 space-y-2 text-sm" aria-live="polite">{checks.map((x,i)=><li key={i}><span className={x.kind==="error"?"font-bold text-red-700":"font-medium text-amber-800"}>{x.kind==="error"?"Lỗi":"Gợi ý"}: </span>{x.text}</li>)}{!checks.length&&<li>Không phát hiện vấn đề trong các kiểm tra hiện có.</li>}</ul></section><section className={panel}><h2 className="font-black">Dàn ý nội dung</h2><ol className="mt-2 space-y-1 text-sm">{headings.map((h,i)=><li key={i} style={{paddingLeft:`${(h[1].length-1)*12}px`}}>H{h[1].length} · {h[2]}</li>)}{!headings.length&&<li className="text-slate-500">Chưa có tiêu đề phụ.</li>}</ol></section><section className={panel}><h2 className="font-black">Chất lượng nội dung</h2><ul className="mt-2 list-disc space-y-2 pl-5 text-sm text-slate-700"><li>Bài viết trả lời nhu cầu thật của người học?</li><li>Có ví dụ và giá trị riêng?</li><li>Nguồn tham khảo và tác giả được ghi rõ khi cần?</li></ul></section></>}
      {tab==="SEO"&&<><section className={panel}><h2 className="font-black">Xem trước kết quả tìm kiếm</h2><div className="mt-3 rounded-xl border p-3"><p className="truncate text-xs text-slate-600">{siteUrl.replace(/\/$/,"")}/blog/{slug||"duong-dan"}</p><p className="mt-1 truncate text-lg text-blue-700">{seoTitle||title||"Tiêu đề bài viết"}</p><p className="mt-1 line-clamp-3 text-sm text-slate-700">{seoDescription||excerpt||"Mô tả ngắn về bài viết sẽ xuất hiện ở đây."}</p></div><p className="mt-2 text-xs text-slate-600">Đây là bản mô phỏng. Google có thể viết lại tiêu đề và đoạn mô tả.</p></section><section className={panel}><h2 className="font-black">Thông tin tìm kiếm</h2><label className="mt-3 block text-sm font-bold">Tiêu đề SEO<input className={field} name="seoTitle" value={seoTitle} onChange={e=>setSeoTitle(e.target.value)} placeholder="Mặc định dùng tiêu đề bài viết"/></label><label className="mt-3 block text-sm font-bold">Mô tả tìm kiếm<textarea className={field} name="seoDescription" rows={3} value={seoDescription} onChange={e=>setSeoDescription(e.target.value)} placeholder="Mặc định dùng tóm tắt"/></label><label className="mt-3 block text-sm font-bold">Đường dẫn (slug)<input className={field} name="slug" value={slug} onChange={e=>{setManual(true);setSlug(slugify(e.target.value));}} readOnly={initial.status==="PUBLISHED"}/></label><p className="mt-2 break-all text-xs text-slate-600">URL: {siteUrl.replace(/\/$/,"")}/blog/{slug||"duong-dan"}</p>{initial.status==="PUBLISHED"&&<p className="mt-2 text-xs text-amber-800">Slug đã khóa sau xuất bản vì chưa có hệ thống chuyển hướng.</p>}</section></>}
      {tab==="Liên kết"&&<section className={panel}><h2 className="font-black">Liên kết trong bài</h2><p className="mt-2 text-sm">Nội bộ: {internal.length} · Ngoài: {external.length} · Cần kiểm tra: {invalid.length+unknown.length}</p>{unknown.map(x=><p className="mt-2 break-all text-xs text-amber-800" key={x}>Chưa tìm thấy: {x}</p>)}<h3 className="mt-4 text-sm font-bold">Gợi ý từ bài đã xuất bản</h3><ul className="mt-2 space-y-2 text-sm">{related.map(x=><li key={x.id}><a className="text-teal-700 underline" href={`/blog/${x.slug}`} target="_blank" rel="noopener noreferrer">{x.title}</a><code className="block break-all text-xs">/blog/{x.slug}</code></li>)}{!related.length&&<li>Chưa có bài liên quan.</li>}</ul><p className="mt-3 text-xs text-slate-600">Chèn liên kết phù hợp vào Markdown theo dạng [văn bản](/blog/slug).</p></section>}
      {tab==="Social"&&<section className={panel}><h2 className="font-black">Chia sẻ mạng xã hội</h2><label className="mt-3 block text-sm font-bold">Tiêu đề OG<input className={field} name="socialTitle" value={socialTitle} onChange={e=>setSocialTitle(e.target.value)} placeholder="Kế thừa tiêu đề SEO"/></label><label className="mt-3 block text-sm font-bold">Mô tả OG<textarea className={field} name="socialDescription" rows={3} value={socialDescription} onChange={e=>setSocialDescription(e.target.value)} placeholder="Kế thừa mô tả tìm kiếm"/></label><div className="mt-3 overflow-hidden rounded-xl border">{image&&<div className="bg-slate-100 p-4 text-xs">Ảnh: {image.storageKey}</div>}<div className="p-3"><p className="font-bold">{socialTitle||seoTitle||title||"Tiêu đề bài viết"}</p><p className="mt-1 text-sm text-slate-600">{socialDescription||seoDescription||excerpt||"Mô tả bài viết"}</p></div></div></section>}
      {tab==="Schema"&&<section className={panel}><h2 className="font-black">Dữ liệu có cấu trúc</h2><p className="mt-2 text-sm">BlogPosting được tạo từ tiêu đề, ngày xuất bản, ngày cập nhật, tác giả và ảnh hiện có.</p><p className="mt-3 text-sm font-bold">{title&&initial.publishedAt?"Đủ dữ liệu cốt lõi":"Sẽ hoàn thiện khi bài được xuất bản"}</p><p className="mt-2 text-xs text-slate-600">Xem bản đã lưu để kiểm tra dữ liệu cuối cùng.</p></section>}
      {tab==="Nâng cao"&&<section className={panel}><h2 className="font-black">Cài đặt nâng cao</h2><label className="mt-3 block text-sm font-bold">Tác giả / tên hiển thị<input className={field} name="authorName" value={authorName} onChange={e=>setAuthorName(e.target.value)} placeholder="Mặc định: TOEICGym"/></label><label className="mt-4 flex items-center gap-2 text-sm font-bold"><input type="checkbox" name="noindex" checked={noindex} onChange={e=>setNoindex(e.target.checked)}/> Không lập chỉ mục bài đã xuất bản</label><p className="mt-2 text-xs text-slate-600">Bài nháp và bản xem trước luôn không lập chỉ mục. Bài noindex không có trong sitemap.</p><label className="mt-4 block text-sm font-bold">URL chuẩn (canonical)<input className={field} name="canonicalPath" value={canonicalPath} onChange={e=>setCanonicalPath(e.target.value)} placeholder={`/blog/${slug||"slug"}`}/></label><p className="mt-2 text-xs text-slate-600">Để trống để dùng URL của bài. Chỉ nhập đường dẫn cùng website, bắt đầu bằng /.</p></section>}
    </aside>
  </form>;
}
