"use client";
import Link from "next/link";
import { useState } from "react";
import { IMPORT_MAX_BYTES } from "@/lib/question-import/schema";
type Issue={severity:"ERROR"|"WARNING"|"INFO";code:string;message:string;path?:string;importKey?:string;part?:number};
type Report={valid:boolean;schemaVersion?:string;batchName?:string;itemCount:number;questionCount:number;counts:Record<string,number>;issues:Issue[];summary:Record<string,number>};
type Result={importId:string;batchKey:string;questionsCreated:number;groupsCreated:number;stimuliCreated:number;warnings:number;durationMs:number};
export function QuestionImportClient(){const[text,setText]=useState("");const[filename,setFilename]=useState("");const[report,setReport]=useState<Report|null>(null);const[result,setResult]=useState<Result|null>(null);const[busy,setBusy]=useState(false);const[message,setMessage]=useState("");const [preview,setPreview]=useState<PreviewItem[]>([]);
async function choose(file?:File){setReport(null);setResult(null);setPreview([]);setMessage("");if(!file)return;if(file.size>IMPORT_MAX_BYTES){setMessage("Tệp vượt giới hạn 2 MiB.");return;}setFilename(file.name);setText(await file.text());}
async function validate(){setBusy(true);setMessage("");try{const response=await fetch("/api/admin/content-import/validate",{method:"POST",headers:{"content-type":"application/json"},body:text});const data=await response.json();if(!data.counts){setReport(null);setPreview([]);setMessage(`Không thể validate: ${data.error??"INVALID_UPLOAD"}`);return;}setReport(data);if(response.ok){const parsed=JSON.parse(text) as {items:PreviewItem[]};setPreview(parsed.items.slice(0,5));}else{setPreview([]);setMessage("Validation phát hiện lỗi. Không có dữ liệu nào được ghi.");}}catch{setMessage("Không thể validate tệp.");}finally{setBusy(false)}}
async function commit(){if(!report?.valid||!confirm(`Import ${report.questionCount} câu hỏi dưới dạng Draft?`))return;setBusy(true);try{const response=await fetch("/api/admin/content-import/commit",{method:"POST",headers:{"content-type":"application/json","x-import-filename":filename},body:text});const data=await response.json();if(!response.ok){setMessage(`Import thất bại: ${data.error}`);if(data.report)setReport(data.report);}else{setResult(data);setMessage("");}}catch{setMessage("Import thất bại; transaction đã rollback.");}finally{setBusy(false)}}
function copyReport(){if(report)navigator.clipboard.writeText(JSON.stringify({valid:report.valid,issues:report.issues},null,2));}
function downloadReport(){if(!report)return;const url=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:"application/json"}));const a=document.createElement("a");a.href=url;a.download="toeicgym-validation-report.json";a.click();URL.revokeObjectURL(url);}
return <div className="mt-6 space-y-5"><section className="rounded-2xl border bg-white p-5"><p className="font-bold">1. Chọn JSON (tối đa 2 MiB / 500 nhóm)</p><input className="mt-3 block w-full rounded-xl border p-3" accept="application/json,.json" type="file" onChange={(e)=>choose(e.target.files?.[0])}/><div className="mt-3 flex flex-wrap gap-3"><button disabled={!text||busy} onClick={validate} className="rounded-xl bg-slate-900 px-4 py-3 font-bold text-white disabled:opacity-50">{busy?"Đang xử lý…":"Validate / Dry run"}</button><a className="rounded-xl border px-4 py-3 font-bold" href="/api/admin/content-import/template">Tải JSON template</a></div>{filename&&<p className="mt-3 text-sm text-slate-600">Tệp: {filename}</p>}{message&&<p role="alert" className="mt-3 rounded-xl bg-amber-50 p-3 font-semibold text-amber-900">{message}</p>}</section>
{report&&<><section className="rounded-2xl border bg-white p-5"><h2 className="text-xl font-black">2. Báo cáo validation</h2><div className="mt-3 grid gap-3 sm:grid-cols-5"><Stat label="Schema" value={report.schemaVersion??"—"}/><Stat label="Nhóm" value={report.itemCount}/><Stat label="Câu hỏi" value={report.questionCount}/><Stat label="Lỗi" value={report.counts.ERROR}/><Stat label="Cảnh báo" value={report.counts.WARNING}/></div><p className="mt-3 font-semibold">Batch: {report.batchName??"—"} · {report.valid?"HỢP LỆ":"BỊ CHẶN"}</p><div className="mt-3 flex gap-2"><button onClick={copyReport} className="rounded-lg border px-3 py-2 font-bold">Copy report</button><button onClick={downloadReport} className="rounded-lg border px-3 py-2 font-bold">Tải report JSON</button></div></section>
<section className="overflow-x-auto rounded-2xl border bg-white"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-slate-100"><tr>{["Key","Part","Mức","Code","Field","Lý do"].map(x=><th className="p-3" key={x}>{x}</th>)}</tr></thead><tbody>{report.issues.map((x,i)=><tr className="border-t" key={`${x.code}-${i}`}><td className="p-3 font-mono">{x.importKey??"—"}</td><td>P{x.part??"—"}</td><td className={x.severity==="ERROR"?"font-bold text-red-700":"font-bold text-amber-700"}>{x.severity}</td><td className="font-mono">{x.code}</td><td className="font-mono">{x.path??"—"}</td><td>{x.message}</td></tr>)}</tbody></table>{!report.issues.length&&<p className="p-5 font-bold text-emerald-700">Không có lỗi hoặc cảnh báo.</p>}</section>
{preview.length>0&&<section className="rounded-2xl border bg-white p-5"><h2 className="text-xl font-black">3. Preview (5 nhóm đầu)</h2><div className="mt-3 space-y-4">{preview.map(item=><article className="rounded-xl border p-4" key={item.externalItemId}><h3 className="font-bold">{item.externalItemId} · P{item.part} · {item.title}</h3><p className="mt-1 text-sm">{item.setType} · {item.passages?.length??0} passage · Audio: {item.media?.audio?.assetId?"READY reference":item.media?.audio?.pending?"pending":"none"} · Image: {item.media?.image?.assetId?"READY reference":item.media?.image?.pending?"pending":"none"}</p>{item.passages?.map((p,i)=><p className="mt-2 whitespace-pre-wrap rounded bg-slate-50 p-2 text-sm" key={i}>{p.content}</p>)}{item.questions.map(q=><div className="mt-3 border-t pt-3" key={q.externalQuestionId}><p className="font-semibold">{q.externalQuestionId}: {q.text||"(spoken question)"}</p><ol className="mt-1 list-inside list-disc">{q.options.map(o=><li key={o.key}>{o.key}. {o.text}{o.key===q.correctOptionKey?" ✓":""}</li>)}</ol><p className="mt-1 text-sm">{q.skill}/{q.subSkill} · {q.difficulty}</p><p className="mt-1 text-sm">EN: {q.explanation.en} · VI: {q.explanation.vi}</p></div>)}</article>)}</div></section>}
<section className="rounded-2xl border bg-white p-5"><h2 className="text-xl font-black">4. Xác nhận</h2><p className="mt-2">Nội dung sẽ được tạo dưới dạng Draft và vẫn phải qua QA/publish trong Admin Content. Chỉ import nội dung có quyền sử dụng.</p><button disabled={!report.valid||busy||Boolean(result)} onClick={commit} className="mt-3 rounded-xl bg-teal-700 px-5 py-3 font-black text-white disabled:opacity-50">Xác nhận import Draft</button></section></>}
{result&&<section className="rounded-2xl border border-emerald-300 bg-emerald-50 p-5"><h2 className="text-xl font-black text-emerald-900">Import thành công</h2><p className="mt-2 font-mono text-sm">Batch/import ID: {result.importId}</p><p>{result.questionsCreated} câu · {result.groupsCreated} nhóm · {result.stimuliCreated} stimuli · {result.warnings} cảnh báo · {result.durationMs} ms</p><Link className="mt-3 inline-block font-bold text-teal-800 underline" href="/admin/content/questions">Mở Admin Content để review</Link></section>}</div>}
function Stat({label,value}:{label:string;value:string|number}){return <div className="rounded-xl bg-slate-50 p-3"><small className="block text-slate-500">{label}</small><strong className="text-xl">{value}</strong></div>}
type PreviewItem={externalItemId:string;part:number;title:string;setType:string;passages?:{content:string}[];media?:{audio?:{assetId?:string;pending?:boolean};image?:{assetId?:string;pending?:boolean}};questions:{externalQuestionId:string;text:string;options:{key:string;text:string}[];correctOptionKey:string;explanation:{en:string;vi:string};skill:string;subSkill:string;difficulty:string}[]};
