"use client";
/* Signed local-media URLs are generated dynamically. */
/* eslint-disable @next/next/no-img-element */
import { useRouter } from "next/navigation";
import { useState, useTransition } from "react";
import { ListeningAudioPlayer } from "@/components/listening/listening-audio-player";
import { PassageDocuments } from "@/components/practice/passage-documents";
import type { InterfaceLanguage } from "@/lib/i18n/config";
import type { PracticeQuestion, PracticeSession } from "@/lib/practice/types";
import { submitDiagnosticPart } from "../actions";

export function DiagnosticClient({ runId, session, completed, total, partIndex, locale }: { runId: string; session: PracticeSession; completed: number; total: number; partIndex: number; locale: InterfaceLanguage }) {
  const vi = locale === "vi"; const router = useRouter(); const [groupIndex, setGroupIndex] = useState(0); const [answers, setAnswers] = useState<Record<string,string>>({}); const [error, setError] = useState(""); const [pending, startTransition] = useTransition(); const group = session.groups[groupIndex];
  function choose(question: PracticeQuestion, optionId: string) { setAnswers((old) => ({ ...old, [question.id]: optionId })); }
  function submit() { startTransition(async () => { const result = await submitDiagnosticPart(runId, session.id, session.questions.map((q) => ({ questionId: q.id, selectedOptionId: answers[q.id] ?? null }))); if (!result.ok) { setError(vi ? "Không thể nộp phần này. Vui lòng thử lại." : "Could not submit this Part. Please try again."); return; } router.push(result.completed ? `/diagnostic/${runId}/result` : `/diagnostic/${runId}`); router.refresh(); }); }
  const first = group.questions[0]; const audio = first.media?.find((item) => item.kind === "AUDIO"); const image = first.media?.find((item) => item.kind === "IMAGE");
  return <main className="min-h-screen overflow-x-hidden bg-slate-50 px-4 py-5 text-slate-900 sm:px-6"><div className="mx-auto max-w-5xl"><header><p className="text-sm font-black uppercase tracking-wider text-teal-700">{vi ? "Đánh giá đầu vào" : "Diagnostic Assessment"}</p><div className="mt-2 flex flex-wrap items-end justify-between gap-2"><h1 className="text-2xl font-black">{session.skillArea === "LISTENING" ? "Listening" : "Reading"} · Part {first.part}</h1><p className="font-semibold">{vi ? "Part" : "Part"} {partIndex} / 7 · {completed} / {total} {vi ? "câu" : "questions"}</p></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-slate-200" role="progressbar" aria-valuemin={0} aria-valuemax={total} aria-valuenow={completed}><div className="h-full bg-teal-600" style={{ width: `${completed / total * 100}%` }} /></div><p className="mt-3 text-sm text-slate-600">{vi ? "Đáp án và giải thích được giữ kín đến khi hoàn thành toàn bộ bài đánh giá." : "Answers and explanations remain locked until the full assessment is complete."}</p></header>
    <section className={`mt-6 grid min-w-0 gap-5 ${group.passages.length ? "lg:grid-cols-2" : "mx-auto max-w-3xl"}`}>{group.passages.length ? <PassageDocuments passages={group.passages} /> : null}<div className="min-w-0 rounded-3xl border border-slate-200 bg-white p-5 sm:p-7">{image ? <img alt={image.alt} className="mb-5 max-h-[50vh] w-full rounded-2xl object-contain" src={image.url} /> : null}{audio ? <div className="mb-5"><ListeningAudioPlayer assetId={audio.id} groupId={group.id} initialUrl={audio.url} labels={{ play: vi ? "Phát" : "Play", pause: vi ? "Tạm dừng" : "Pause", replay: vi ? "Phát lại" : "Replay", loading: vi ? "Đang tải" : "Loading", unavailable: vi ? "Âm thanh không khả dụng" : "Audio unavailable", retry: vi ? "Tải lại" : "Retry" }} questionId={first.id} sessionId={session.id} /></div> : null}<div className="space-y-6">{group.questions.map((question) => <fieldset key={question.id}><legend className="font-bold">{question.number}. {question.text}</legend><div className="mt-3 grid gap-3">{question.options.map((option) => <label className={`flex min-h-12 cursor-pointer items-center gap-3 rounded-xl border px-4 py-3 ${answers[question.id] === option.id ? "border-teal-600 bg-teal-50 ring-1 ring-teal-600" : "border-slate-300"}`} key={option.id}><input checked={answers[question.id] === option.id} name={question.id} onChange={() => choose(question, option.id)} type="radio"/><strong>{option.key}.</strong><span>{option.text}</span></label>)}</div></fieldset>)}</div></div></section>
    {error ? <p className="mt-4 rounded-xl bg-red-50 p-4 text-red-800" role="alert">{error}</p> : null}<div className="mt-5 flex gap-3 pb-10"><button className="min-h-12 rounded-xl border border-slate-300 bg-white px-5 font-bold disabled:opacity-40" disabled={groupIndex === 0 || pending} onClick={() => setGroupIndex((i) => i - 1)} type="button">{vi ? "Nhóm trước" : "Previous group"}</button>{groupIndex < session.groups.length - 1 ? <button className="ml-auto min-h-12 rounded-xl bg-slate-900 px-5 font-bold text-white" onClick={() => setGroupIndex((i) => i + 1)} type="button">{vi ? "Nhóm tiếp" : "Next group"}</button> : <button className="ml-auto min-h-12 rounded-xl bg-teal-700 px-5 font-bold text-white disabled:opacity-50" disabled={pending} onClick={submit} type="button">{pending ? (vi ? "Đang nộp…" : "Submitting…") : partIndex === 7 ? (vi ? "Hoàn thành đánh giá" : "Complete assessment") : (vi ? "Hoàn thành Part" : "Complete Part")}</button>}</div>
  </div></main>;
}
