// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/activate-account" | "/admin" | "/admin/access-denied" | "/admin/analytics" | "/admin/audit" | "/admin/challenges" | "/admin/challenges/[id]" | "/admin/challenges/new" | "/admin/content" | "/admin/content/batches/[batchKey]" | "/admin/content/import" | "/admin/content/media" | "/admin/content/new" | "/admin/content/posts" | "/admin/content/posts/[id]" | "/admin/content/posts/[id]/preview" | "/admin/content/posts/new" | "/admin/content/questions" | "/admin/content/questions/[id]" | "/admin/content/questions/[id]/edit" | "/admin/content/questions/[id]/preview" | "/admin/content/similarity" | "/admin/payments" | "/admin/payments/[id]" | "/admin/settings" | "/admin/support" | "/admin/users" | "/admin/users/[userId]" | "/admin/users/[userId]/snapshot" | "/billing" | "/billing/cancel" | "/billing/confirm" | "/billing/return" | "/blog" | "/blog/[slug]" | "/continue-learning" | "/dashboard" | "/demo-test" | "/demo-test/[sessionId]" | "/demo-test/[sessionId]/results" | "/diagnostic" | "/diagnostic/[runId]" | "/diagnostic/[runId]/result" | "/forgot-password" | "/full-mock" | "/full-mock/[runId]" | "/full-mock/[runId]/results" | "/full-mock/history" | "/learners/[publicProfileId]" | "/mistakes" | "/onboarding" | "/practice" | "/practice/[sessionId]" | "/practice/[sessionId]/results" | "/practice/part-5" | "/practice/part-5/[sessionId]" | "/practice/part-5/[sessionId]/results" | "/pricing" | "/privacy" | "/progress" | "/ranking" | "/ranking/challenges/[challengeId]" | "/ranking/challenges/run/[runId]" | "/ranking/challenges/run/[runId]/result" | "/reset-password" | "/settings" | "/sign-in" | "/sign-up" | "/support" | "/terms" | "/try" | "/verify-email"
type AppRouteHandlerRoutes = "/admin/content/media/[id]/preview" | "/api/admin/analytics-export" | "/api/admin/content-export" | "/api/admin/content-import/commit" | "/api/admin/content-import/template" | "/api/admin/content-import/validate" | "/api/admin/posts/cover" | "/api/admin/posts/import-template" | "/api/analytics/events" | "/api/auth/google" | "/api/health" | "/api/media/local" | "/api/payments/payos/webhook" | "/api/test/payments/confirm" | "/auth/callback" | "/blog/cover/[category]"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/activate-account": {}
  "/admin": {}
  "/admin/access-denied": {}
  "/admin/analytics": {}
  "/admin/audit": {}
  "/admin/challenges": {}
  "/admin/challenges/[id]": { "id": string; }
  "/admin/challenges/new": {}
  "/admin/content": {}
  "/admin/content/batches/[batchKey]": { "batchKey": string; }
  "/admin/content/import": {}
  "/admin/content/media": {}
  "/admin/content/media/[id]/preview": { "id": string; }
  "/admin/content/new": {}
  "/admin/content/posts": {}
  "/admin/content/posts/[id]": { "id": string; }
  "/admin/content/posts/[id]/preview": { "id": string; }
  "/admin/content/posts/new": {}
  "/admin/content/questions": {}
  "/admin/content/questions/[id]": { "id": string; }
  "/admin/content/questions/[id]/edit": { "id": string; }
  "/admin/content/questions/[id]/preview": { "id": string; }
  "/admin/content/similarity": {}
  "/admin/payments": {}
  "/admin/payments/[id]": { "id": string; }
  "/admin/settings": {}
  "/admin/support": {}
  "/admin/users": {}
  "/admin/users/[userId]": { "userId": string; }
  "/admin/users/[userId]/snapshot": { "userId": string; }
  "/api/admin/analytics-export": {}
  "/api/admin/content-export": {}
  "/api/admin/content-import/commit": {}
  "/api/admin/content-import/template": {}
  "/api/admin/content-import/validate": {}
  "/api/admin/posts/cover": {}
  "/api/admin/posts/import-template": {}
  "/api/analytics/events": {}
  "/api/auth/google": {}
  "/api/health": {}
  "/api/media/local": {}
  "/api/payments/payos/webhook": {}
  "/api/test/payments/confirm": {}
  "/auth/callback": {}
  "/billing": {}
  "/billing/cancel": {}
  "/billing/confirm": {}
  "/billing/return": {}
  "/blog": {}
  "/blog/[slug]": { "slug": string; }
  "/blog/cover/[category]": { "category": string; }
  "/continue-learning": {}
  "/dashboard": {}
  "/demo-test": {}
  "/demo-test/[sessionId]": { "sessionId": string; }
  "/demo-test/[sessionId]/results": { "sessionId": string; }
  "/diagnostic": {}
  "/diagnostic/[runId]": { "runId": string; }
  "/diagnostic/[runId]/result": { "runId": string; }
  "/forgot-password": {}
  "/full-mock": {}
  "/full-mock/[runId]": { "runId": string; }
  "/full-mock/[runId]/results": { "runId": string; }
  "/full-mock/history": {}
  "/learners/[publicProfileId]": { "publicProfileId": string; }
  "/mistakes": {}
  "/onboarding": {}
  "/practice": {}
  "/practice/[sessionId]": { "sessionId": string; }
  "/practice/[sessionId]/results": { "sessionId": string; }
  "/practice/part-5": {}
  "/practice/part-5/[sessionId]": { "sessionId": string; }
  "/practice/part-5/[sessionId]/results": { "sessionId": string; }
  "/pricing": {}
  "/privacy": {}
  "/progress": {}
  "/ranking": {}
  "/ranking/challenges/[challengeId]": { "challengeId": string; }
  "/ranking/challenges/run/[runId]": { "runId": string; }
  "/ranking/challenges/run/[runId]/result": { "runId": string; }
  "/reset-password": {}
  "/settings": {}
  "/sign-in": {}
  "/sign-up": {}
  "/support": {}
  "/terms": {}
  "/try": {}
  "/verify-email": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
