// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/activate-account/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/activate-account">> = Specific
  const handler = {} as typeof import("../../src/app/activate-account/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/access-denied/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/access-denied">> = Specific
  const handler = {} as typeof import("../../src/app/admin/access-denied/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/analytics">> = Specific
  const handler = {} as typeof import("../../src/app/admin/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/audit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/audit">> = Specific
  const handler = {} as typeof import("../../src/app/admin/audit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/challenges/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/challenges/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/admin/challenges/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/challenges/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/challenges/new">> = Specific
  const handler = {} as typeof import("../../src/app/admin/challenges/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/challenges/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/challenges">> = Specific
  const handler = {} as typeof import("../../src/app/admin/challenges/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/content/batches/[batchKey]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/content/batches/[batchKey]">> = Specific
  const handler = {} as typeof import("../../src/app/admin/content/batches/[batchKey]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/content/import/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/content/import">> = Specific
  const handler = {} as typeof import("../../src/app/admin/content/import/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/content/media/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/content/media">> = Specific
  const handler = {} as typeof import("../../src/app/admin/content/media/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/content/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/content/new">> = Specific
  const handler = {} as typeof import("../../src/app/admin/content/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/content/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/content">> = Specific
  const handler = {} as typeof import("../../src/app/admin/content/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/content/posts/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/content/posts/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/admin/content/posts/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/content/posts/[id]/preview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/content/posts/[id]/preview">> = Specific
  const handler = {} as typeof import("../../src/app/admin/content/posts/[id]/preview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/content/posts/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/content/posts/new">> = Specific
  const handler = {} as typeof import("../../src/app/admin/content/posts/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/content/posts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/content/posts">> = Specific
  const handler = {} as typeof import("../../src/app/admin/content/posts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/content/questions/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/content/questions/[id]/edit">> = Specific
  const handler = {} as typeof import("../../src/app/admin/content/questions/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/content/questions/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/content/questions/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/admin/content/questions/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/content/questions/[id]/preview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/content/questions/[id]/preview">> = Specific
  const handler = {} as typeof import("../../src/app/admin/content/questions/[id]/preview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/content/questions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/content/questions">> = Specific
  const handler = {} as typeof import("../../src/app/admin/content/questions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/content/similarity/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/content/similarity">> = Specific
  const handler = {} as typeof import("../../src/app/admin/content/similarity/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/payments/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/payments/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/admin/payments/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/payments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/payments">> = Specific
  const handler = {} as typeof import("../../src/app/admin/payments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings">> = Specific
  const handler = {} as typeof import("../../src/app/admin/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/support/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/support">> = Specific
  const handler = {} as typeof import("../../src/app/admin/support/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/users/[userId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/users/[userId]">> = Specific
  const handler = {} as typeof import("../../src/app/admin/users/[userId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/users/[userId]/snapshot/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/users/[userId]/snapshot">> = Specific
  const handler = {} as typeof import("../../src/app/admin/users/[userId]/snapshot/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/users">> = Specific
  const handler = {} as typeof import("../../src/app/admin/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/billing/cancel/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/billing/cancel">> = Specific
  const handler = {} as typeof import("../../src/app/billing/cancel/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/billing/confirm/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/billing/confirm">> = Specific
  const handler = {} as typeof import("../../src/app/billing/confirm/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/billing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/billing">> = Specific
  const handler = {} as typeof import("../../src/app/billing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/billing/return/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/billing/return">> = Specific
  const handler = {} as typeof import("../../src/app/billing/return/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/blog/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/blog/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog">> = Specific
  const handler = {} as typeof import("../../src/app/blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/continue-learning/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/continue-learning">> = Specific
  const handler = {} as typeof import("../../src/app/continue-learning/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/demo-test/[sessionId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/demo-test/[sessionId]">> = Specific
  const handler = {} as typeof import("../../src/app/demo-test/[sessionId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/demo-test/[sessionId]/results/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/demo-test/[sessionId]/results">> = Specific
  const handler = {} as typeof import("../../src/app/demo-test/[sessionId]/results/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/demo-test/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/demo-test">> = Specific
  const handler = {} as typeof import("../../src/app/demo-test/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/diagnostic/[runId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/diagnostic/[runId]">> = Specific
  const handler = {} as typeof import("../../src/app/diagnostic/[runId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/diagnostic/[runId]/result/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/diagnostic/[runId]/result">> = Specific
  const handler = {} as typeof import("../../src/app/diagnostic/[runId]/result/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/diagnostic/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/diagnostic">> = Specific
  const handler = {} as typeof import("../../src/app/diagnostic/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forgot-password">> = Specific
  const handler = {} as typeof import("../../src/app/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/full-mock/[runId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/full-mock/[runId]">> = Specific
  const handler = {} as typeof import("../../src/app/full-mock/[runId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/full-mock/[runId]/results/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/full-mock/[runId]/results">> = Specific
  const handler = {} as typeof import("../../src/app/full-mock/[runId]/results/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/full-mock/history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/full-mock/history">> = Specific
  const handler = {} as typeof import("../../src/app/full-mock/history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/full-mock/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/full-mock">> = Specific
  const handler = {} as typeof import("../../src/app/full-mock/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/learners/[publicProfileId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/learners/[publicProfileId]">> = Specific
  const handler = {} as typeof import("../../src/app/learners/[publicProfileId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/mistakes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mistakes">> = Specific
  const handler = {} as typeof import("../../src/app/mistakes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/onboarding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/onboarding">> = Specific
  const handler = {} as typeof import("../../src/app/onboarding/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/practice/[sessionId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/practice/[sessionId]">> = Specific
  const handler = {} as typeof import("../../src/app/practice/[sessionId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/practice/[sessionId]/results/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/practice/[sessionId]/results">> = Specific
  const handler = {} as typeof import("../../src/app/practice/[sessionId]/results/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/practice/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/practice">> = Specific
  const handler = {} as typeof import("../../src/app/practice/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/practice/part-5/[sessionId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/practice/part-5/[sessionId]">> = Specific
  const handler = {} as typeof import("../../src/app/practice/part-5/[sessionId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/practice/part-5/[sessionId]/results/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/practice/part-5/[sessionId]/results">> = Specific
  const handler = {} as typeof import("../../src/app/practice/part-5/[sessionId]/results/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/practice/part-5/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/practice/part-5">> = Specific
  const handler = {} as typeof import("../../src/app/practice/part-5/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/pricing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pricing">> = Specific
  const handler = {} as typeof import("../../src/app/pricing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../src/app/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/progress/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/progress">> = Specific
  const handler = {} as typeof import("../../src/app/progress/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/ranking/challenges/[challengeId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ranking/challenges/[challengeId]">> = Specific
  const handler = {} as typeof import("../../src/app/ranking/challenges/[challengeId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/ranking/challenges/run/[runId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ranking/challenges/run/[runId]">> = Specific
  const handler = {} as typeof import("../../src/app/ranking/challenges/run/[runId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/ranking/challenges/run/[runId]/result/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ranking/challenges/run/[runId]/result">> = Specific
  const handler = {} as typeof import("../../src/app/ranking/challenges/run/[runId]/result/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/ranking/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ranking">> = Specific
  const handler = {} as typeof import("../../src/app/ranking/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reset-password">> = Specific
  const handler = {} as typeof import("../../src/app/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../src/app/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/sign-in/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sign-in">> = Specific
  const handler = {} as typeof import("../../src/app/sign-in/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/sign-up/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sign-up">> = Specific
  const handler = {} as typeof import("../../src/app/sign-up/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/support/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/support">> = Specific
  const handler = {} as typeof import("../../src/app/support/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../src/app/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/try/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/try">> = Specific
  const handler = {} as typeof import("../../src/app/try/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/verify-email/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/verify-email">> = Specific
  const handler = {} as typeof import("../../src/app/verify-email/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/content/media/[id]/preview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/admin/content/media/[id]/preview">> = Specific
  const handler = {} as typeof import("../../src/app/admin/content/media/[id]/preview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/analytics-export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/analytics-export">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/analytics-export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/content-export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/content-export">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/content-export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/content-import/commit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/content-import/commit">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/content-import/commit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/content-import/template/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/content-import/template">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/content-import/template/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/content-import/validate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/content-import/validate">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/content-import/validate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/posts/cover/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/posts/cover">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/posts/cover/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/posts/import-template/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/posts/import-template">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/posts/import-template/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/analytics/events/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/analytics/events">> = Specific
  const handler = {} as typeof import("../../src/app/api/analytics/events/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/google/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/google">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/google/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../src/app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/media/local/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/media/local">> = Specific
  const handler = {} as typeof import("../../src/app/api/media/local/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/payments/payos/webhook/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payments/payos/webhook">> = Specific
  const handler = {} as typeof import("../../src/app/api/payments/payos/webhook/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/test/payments/confirm/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/test/payments/confirm">> = Specific
  const handler = {} as typeof import("../../src/app/api/test/payments/confirm/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/callback">> = Specific
  const handler = {} as typeof import("../../src/app/auth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/blog/cover/[category]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/blog/cover/[category]">> = Specific
  const handler = {} as typeof import("../../src/app/blog/cover/[category]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
