"use client";
import { useEffect, useState } from "react";
import { useFormStatus } from "react-dom";
import type { InterfaceLanguage } from "@/lib/i18n/config";
import { getTranslations } from "@/lib/i18n/runtime";
import { modeLabel, taxonomyLabel } from "@/lib/i18n/labels";
import { QUESTION_COUNT_OPTIONS, READING_TAXONOMY } from "@/lib/practice/constants";
import type { ReadingPart, ReadingPracticeMode } from "@/lib/practice/types";
import { loadAdvancedTargetingAccess, startAdvancedTargeting, startReadingPractice } from "./actions";

function SubmitButton({ locale }: { locale: InterfaceLanguage }) { const { pending } = useFormStatus(); const t = getTranslations(locale); return <button className="w-full rounded-xl bg-teal-700 px-5 py-3 font-bold text-white disabled:opacity-60" disabled={pending} type="submit">{pending ? t.practiceConfig.building : t.practiceConfig.start}</button>; }

export function PracticeConfigurator({ locale }: { locale: InterfaceLanguage }) {
  const t = getTranslations(locale); const [mode, setMode] = useState<ReadingPracticeMode>("part_5"); const [skill, setSkill] = useState(""); const [targetingMode, setTargetingMode] = useState("adaptive"); const [access, setAccess] = useState({ enabled: false, unresolvedMistakes: 0 });
  useEffect(() => { let active = true; void loadAdvancedTargetingAccess().then((value) => { if (active) setAccess(value); }); return () => { active = false; }; }, []);
  const canUseAdvancedTargeting = access.enabled; const unresolvedMistakes = access.unresolvedMistakes;
  const part = mode === "mixed_reading" ? null : Number(mode.slice(-1)) as ReadingPart; const skills = part ? Object.keys(READING_TAXONOMY[part]) : []; const subSkills = part && skill ? READING_TAXONOMY[part][skill] ?? [] : []; const advanced = canUseAdvancedTargeting && targetingMode !== "adaptive";
  const targets = [
    { value: "adaptive", en: "Adaptive", vi: "Thích ứng", detail: locale === "vi" ? "Giữ nguyên bộ chọn và luồng đề xuất hiện có." : "Keeps the existing builder and recommendation flow." },
    { value: "target_weakness", en: "Target weakness", vi: "Điểm yếu", detail: locale === "vi" ? "Ưu tiên kỹ năng cần cải thiện có đủ dữ liệu." : "Prioritizes a reliable area for improvement." },
    { value: "review_mistakes", en: "Review mistakes", vi: "Ôn lỗi sai", detail: locale === "vi" ? `Ôn lỗi chưa làm chủ (${unresolvedMistakes} câu hiện có).` : `Review unresolved mistakes (${unresolvedMistakes} available).` },
    { value: "prefer_unseen", en: "Prefer unseen", vi: "Câu chưa làm", detail: locale === "vi" ? "Ưu tiên câu chưa từng trả lời, rồi đến nội dung cũ hơn." : "Prefers unanswered questions, then older content." },
  ];
  function changeMode(value: ReadingPracticeMode) { setMode(value); setSkill(""); }
  return <form action={advanced ? startAdvancedTargeting : startReadingPractice} className="mt-6 space-y-7"><input name="source" type="hidden" value="custom" />
    {canUseAdvancedTargeting ? <fieldset aria-describedby="targeting-help"><legend className="font-black">{locale === "vi" ? "Mục tiêu luyện tập" : "Practice target"}<span className="ml-2 text-xs font-semibold text-teal-700">Premium targeting</span></legend><div className="mt-3 grid grid-cols-2 gap-3">{targets.map((target) => <label className="cursor-pointer rounded-xl border border-slate-300 p-4 has-checked:border-teal-600 has-checked:bg-teal-50 has-focus-visible:outline-2 has-focus-visible:outline-offset-2 has-focus-visible:outline-teal-700" key={target.value}><span className="flex items-center gap-2"><input checked={targetingMode === target.value} name="targetingMode" onChange={() => setTargetingMode(target.value)} type="radio" value={target.value}/><strong>{locale === "vi" ? target.vi : target.en}</strong></span><span className="mt-2 block text-sm leading-5 text-slate-600">{target.detail}</span></label>)}</div><p className="sr-only" id="targeting-help">{targets.find((target) => target.value === targetingMode)?.detail}</p></fieldset> : null}
    <fieldset><legend className="font-black">{t.practiceConfig.part}</legend><div className="mt-3 grid gap-3 sm:grid-cols-2">{(["part_5", "part_6", "part_7", "mixed_reading"] as const).map((value) => <label className="flex min-h-14 cursor-pointer items-center gap-3 rounded-xl border border-slate-300 p-4 has-checked:border-teal-600 has-checked:bg-teal-50" key={value}><input checked={mode === value} name="mode" onChange={() => changeMode(value)} type="radio" value={value} /><span className="font-bold">{modeLabel(value, locale)}</span></label>)}</div></fieldset>
    {part && targetingMode !== "target_weakness" && targetingMode !== "review_mistakes" ? <div className="grid gap-4 sm:grid-cols-2"><label className="font-bold">{t.practiceConfig.focus}<select className="mt-2 min-h-12 w-full rounded-xl border border-slate-300 bg-white px-3 font-normal" name="skill" onChange={(event) => setSkill(event.target.value)} value={skill}><option value="">{t.practiceConfig.allSkills}</option>{skills.map((value) => <option key={value} value={value}>{taxonomyLabel(value, locale)}</option>)}</select></label><label className="font-bold">{t.practiceConfig.subskill}<select className="mt-2 min-h-12 w-full rounded-xl border border-slate-300 bg-white px-3 font-normal disabled:bg-slate-100" disabled={!skill} name="subSkill" defaultValue=""><option value="">{t.practiceConfig.allSubskills}</option>{subSkills.map((value) => <option key={value} value={value}>{taxonomyLabel(value, locale)}</option>)}</select></label></div> : !part ? <p className="rounded-xl bg-slate-50 p-4 text-sm leading-6 text-slate-600">{t.practiceConfig.mixedInfo}</p> : null}
    <fieldset><legend className="font-black">{t.practiceConfig.target}</legend><div className="mt-3 grid grid-cols-3 gap-3">{QUESTION_COUNT_OPTIONS.map((count) => <label className="cursor-pointer rounded-xl border border-slate-300 p-4 text-center has-checked:border-teal-600 has-checked:bg-teal-50" key={count}><input className="sr-only" defaultChecked={count === 15} name="questionCount" type="radio" value={count} /><strong>{count}</strong></label>)}</div><p className="mt-2 text-sm text-slate-500">{t.practiceConfig.setsInfo}</p></fieldset><SubmitButton locale={locale} /></form>;
}
