import { expect, test } from "@playwright/test";
import pg from "pg";
const password = "Task17-browser-2026!";
function testDb(){const url=new URL(process.env.DATABASE_URL??"");expect(url.hostname).toBe("127.0.0.1");expect(url.port).toBe("15433");expect(process.env.PAYMENT_PROVIDER).toBe("FAKE");return new pg.Pool({connectionString:url.href})}
async function signIn(page:import("@playwright/test").Page,email:string){await page.goto("/sign-in");await page.getByLabel("Email").fill(email);await page.locator('input[name="password"]').fill(password);await page.locator('button[type="submit"], form button').last().click();await expect(page).toHaveURL(/\/dashboard/)}

test("pricing, billing and verified Fake payment activate Premium",async({page})=>{
  await signIn(page,"alice@task17.invalid");await page.goto("/pricing");await expect(page.getByText("59.000 ₫")).toBeVisible();await page.goto("/billing");await page.getByRole("button",{name:/Pay now|Thanh toán ngay/}).first().click();await expect(page).toHaveURL(/\/billing\/return\?order=\d+/);
  const pool=testDb();const order=(await pool.query(`select o.id from payment_orders o join users u on u.id=o.user_id where u.email_normalized='alice@task17.invalid' and o.status='PENDING' order by o.created_at desc limit 1`)).rows[0];await pool.end();expect(order).toBeTruthy();
  const response=await page.request.post("/api/test/payments/confirm",{data:{orderId:order.id}});expect(response.ok()).toBeTruthy();await page.goto(`/billing/return?order=${order.id}`);await expect(page.getByRole("heading",{name:/confirmed|xác nhận/i})).toBeVisible();await page.goto("/billing");await expect(page.getByText("PREMIUM").first()).toBeVisible();await expect(page.getByRole("cell",{name:"PAID"}).first()).toBeVisible();await page.goto("/settings");await expect(page.getByText(/Premium/).first()).toBeVisible();
});
test("return query spoof remains pending and cross-user order is hidden",async({page})=>{
  await signIn(page,"bob@task17.invalid");await page.goto("/billing");await page.getByRole("button",{name:/Pay now|Thanh toán ngay/}).first().click();await expect(page).toHaveURL(/\/billing\/return\?order=\d+/);
  const pool=testDb();const bob=(await pool.query(`select o.id from payment_orders o join users u on u.id=o.user_id where u.email_normalized='bob@task17.invalid' and o.status='PENDING' order by o.created_at desc limit 1`)).rows[0];const alice=(await pool.query(`select o.id from payment_orders o join users u on u.id=o.user_id where u.email_normalized='alice@task17.invalid' order by o.created_at desc limit 1`)).rows[0];await pool.end();expect(bob).toBeTruthy();expect(alice).toBeTruthy();
  await page.goto(`/billing/return?order=${bob.id}&status=PAID&success=true&code=00`);await expect(page.getByRole("heading",{name:/Waiting|Đang xác nhận/i})).toBeVisible();await page.goto(`/billing/return?order=${alice.id}`);await expect(page.getByRole("heading",{name:/not found|Không tìm thấy/i})).toBeVisible();
});
test("admin payments is protected and read-only",async({page})=>{await signIn(page,"bob@task17.invalid");await page.goto("/admin/payments");await expect(page).toHaveURL(/access-denied/);await page.context().clearCookies();await signIn(page,"admin@task17.invalid");await page.goto("/admin/payments");await expect(page.getByRole("heading",{name:/Payments|Thanh toán/})).toBeVisible();await expect(page.getByText(/Mark Paid|Force Paid|Fake Webhook|Edit Amount/)).toHaveCount(0)});
