import Link from "next/link";
import { PublicFooter } from "@/components/public-footer";
import { PublicHeader } from "@/components/public-header";
import { PricingSection } from "@/components/pricing-section";
import { getPreferences } from "@/lib/i18n/get-translations";
import { getMarketingTranslations } from "@/lib/i18n/marketing";
import { getCurrentUser } from "@/lib/auth/session";

export default async function Home() {
  const user = await getCurrentUser();
  const preferences = await getPreferences(user?.id);
  const locale = preferences.interfaceLanguage;
  const t = getMarketingTranslations(locale);
  const primaryHref = user ? "/dashboard" : "/try";
  const demoHref = user ? "/demo-test" : "/sign-in?next=/demo-test";
  const diagnosticHref = user ? "/diagnostic" : "/diagnostic";
  return <main className="min-h-screen overflow-x-hidden bg-slate-50 text-slate-900"><PublicHeader locale={locale} signedIn={Boolean(user)} />
    <section className="border-b border-slate-200 bg-white"><div className="mx-auto grid max-w-7xl gap-12 px-5 py-16 sm:px-6 sm:py-24 lg:grid-cols-[1.05fr_.95fr] lg:items-center"><div><p className="text-sm font-black uppercase tracking-[.16em] text-teal-700">{t.hero.eyebrow}</p><h1 className="mt-5 max-w-3xl text-4xl font-black leading-[1.08] tracking-tight text-slate-950 sm:text-6xl">{t.hero.title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-600">{t.hero.body}</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link className="inline-flex min-h-12 items-center justify-center rounded-xl bg-teal-700 px-6 py-3 font-bold text-white hover:bg-teal-800" href={diagnosticHref}>{locale === "vi" ? "Làm bài đánh giá TOEIC miễn phí" : "Take a free TOEIC diagnostic"}</Link><Link className="inline-flex min-h-12 items-center justify-center rounded-xl border border-slate-300 bg-white px-6 py-3 font-bold text-slate-800" href={primaryHref}>{user ? t.nav.continue : t.hero.start}</Link><Link className="inline-flex min-h-12 items-center justify-center rounded-xl border border-slate-300 bg-white px-6 py-3 font-bold text-slate-800" href={demoHref}>{t.hero.demo}</Link></div><p className="mt-4 text-sm text-slate-500">{t.hero.trust}</p></div><ProductPreview t={t.preview} /></div></section>
    <section className="mx-auto max-w-7xl px-5 py-16 sm:px-6 sm:py-20" id="features"><SectionHeading eyebrow={t.benefits.eyebrow} title={t.benefits.title} body={t.benefits.intro} /><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{t.benefits.items.map((item, index) => <article className="rounded-2xl border border-slate-200 bg-white p-6" key={item.title}><span className="grid size-9 place-items-center rounded-lg bg-teal-50 text-sm font-black text-teal-800" aria-hidden="true">{index + 1}</span><h3 className="mt-5 text-lg font-black">{item.title}</h3><p className="mt-2 leading-7 text-slate-600">{item.body}</p></article>)}</div></section>
    <section className="bg-slate-900 text-white" id="how-it-works"><div className="mx-auto max-w-7xl px-5 py-16 sm:px-6 sm:py-20"><SectionHeading dark eyebrow={t.how.eyebrow} title={t.how.title} /><ol className="mt-10 grid gap-px overflow-hidden rounded-2xl bg-slate-700 md:grid-cols-4">{t.how.items.map((item) => <li className="bg-slate-900 p-6" key={item.number}><p className="text-sm font-black text-teal-300">{item.number}</p><h3 className="mt-4 text-xl font-black">{item.title}</h3><p className="mt-2 leading-7 text-slate-300">{item.body}</p></li>)}</ol></div></section>
    <section className="mx-auto max-w-7xl px-5 py-16 sm:px-6 sm:py-20"><SectionHeading eyebrow={t.modes.eyebrow} title={t.modes.title} /><div className="mt-10 grid gap-5 lg:grid-cols-2"><article className="rounded-3xl border border-teal-200 bg-teal-50 p-7 sm:p-9"><p className="text-sm font-black uppercase tracking-wider text-teal-800">{t.modes.smart}</p><p className="mt-4 text-lg leading-8 text-slate-700">{t.modes.smartBody}</p><ul className="mt-6 grid gap-3 font-bold"><li>✓ {t.modes.recommended}</li><li>✓ {t.modes.choose}</li><li>✓ Part 5 · Part 6 · Part 7 · Mixed Reading</li></ul><Link className="mt-8 inline-flex min-h-12 items-center rounded-xl bg-teal-700 px-5 font-bold text-white" href={primaryHref}>{t.modes.openPractice}</Link></article><article className="rounded-3xl border border-slate-200 bg-white p-7 sm:p-9"><p className="text-sm font-black uppercase tracking-wider text-slate-500">{t.modes.demo}</p><div className="mt-4 flex flex-wrap gap-2"><span className="rounded-full bg-slate-100 px-3 py-1.5 text-sm font-bold">100 questions</span><span className="rounded-full bg-slate-100 px-3 py-1.5 text-sm font-bold">75 minutes</span></div><p className="mt-5 text-lg leading-8 text-slate-700">{t.modes.demoBody}</p><p className="mt-3 text-sm text-slate-500">{t.modes.demoNote}</p><Link className="mt-8 inline-flex min-h-12 items-center rounded-xl border border-slate-300 px-5 font-bold" href={demoHref}>{t.modes.openDemo}</Link></article></div></section>
    <section className="border-y border-slate-200 bg-white"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-16 sm:px-6 sm:py-20 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><SectionHeading eyebrow={t.assessment.eyebrow} title={t.assessment.title} body={t.assessment.body} /><div className="rounded-3xl bg-slate-900 p-7 text-white sm:p-9"><div className="flex items-center justify-between gap-4"><p className="text-sm font-black uppercase tracking-wider text-teal-300">TOEIC Reading</p><strong className="text-2xl">75:00</strong></div><p className="mt-8 text-4xl font-black">100</p><p className="text-slate-300">questions</p><p className="mt-8 whitespace-pre-wrap rounded-xl bg-white/10 p-4 text-sm leading-7 text-slate-200">{t.assessment.parts}</p></div></div></section>
    <PricingSection locale={locale} compact startHref={primaryHref} />
    <section className="mx-auto max-w-4xl px-5 py-16 sm:px-6 sm:py-20" id="faq"><h2 className="text-center text-3xl font-black tracking-tight sm:text-4xl">{t.faq.title}</h2><div className="mt-10 divide-y divide-slate-200 rounded-2xl border border-slate-200 bg-white px-6">{t.faq.items.map((item) => <details className="group py-5" key={item.question}><summary className="cursor-pointer list-none pr-8 font-black marker:content-none">{item.question}<span className="float-right text-teal-700 group-open:rotate-45" aria-hidden="true">+</span></summary><p className="mt-3 max-w-3xl leading-7 text-slate-600">{item.answer}</p></details>)}</div></section>
    <section className="px-5 pb-16 sm:px-6 sm:pb-20"><div className="mx-auto max-w-5xl rounded-3xl bg-teal-700 p-8 text-center text-white sm:p-12"><h2 className="text-3xl font-black tracking-tight sm:text-4xl">{t.final.title}</h2><p className="mx-auto mt-4 max-w-2xl text-lg leading-8 text-teal-50">{t.final.body}</p><Link className="mt-7 inline-flex min-h-12 items-center rounded-xl bg-white px-6 font-black text-teal-800" href={primaryHref}>{user ? t.nav.continue : t.hero.start}</Link></div></section><PublicFooter locale={locale} /></main>;
}

function SectionHeading({ eyebrow, title, body, dark = false }: { eyebrow: string; title: string; body?: string; dark?: boolean }) { return <div><p className={`text-sm font-black uppercase tracking-[.16em] ${dark ? "text-teal-300" : "text-teal-700"}`}>{eyebrow}</p><h2 className="mt-3 max-w-3xl text-3xl font-black tracking-tight sm:text-4xl">{title}</h2>{body ? <p className={`mt-4 max-w-2xl text-lg leading-8 ${dark ? "text-slate-300" : "text-slate-600"}`}>{body}</p> : null}</div>; }

function ProductPreview({ t }: { t: ReturnType<typeof getMarketingTranslations>["preview"] }) { const bars = [["Part 5", 81], ["Part 6", 69], ["Part 7", 61]] as const; return <aside className="rounded-3xl border border-slate-200 bg-slate-50 p-5 shadow-xl shadow-slate-200/60 sm:p-7" aria-label={t.eyebrow}><div className="rounded-2xl bg-white p-5"><div className="flex items-end justify-between"><div><p className="text-sm font-bold text-slate-500">{t.eyebrow}</p><h2 className="mt-1 text-xl font-black">{t.title}</h2></div><div className="text-right"><strong className="text-3xl text-teal-700">72%</strong><p className="text-xs text-slate-500">{t.overall}</p></div></div><div className="mt-6 space-y-4">{bars.map(([label, value]) => <div key={label}><div className="flex justify-between text-sm font-bold"><span>{label}</span><span>{value}%</span></div><div className="mt-2 h-2 rounded-full bg-slate-100"><div className="h-2 rounded-full bg-teal-600" style={{ width: `${value}%` }} /></div></div>)}</div></div><div className="mt-4 grid gap-4 sm:grid-cols-2"><div className="rounded-2xl bg-white p-5"><p className="text-xs font-black uppercase tracking-wider text-slate-500">{t.areas}</p><p className="mt-3 font-black">{t.inference} <span className="float-right text-amber-700">48%</span></p><p className="mt-2 text-sm font-semibold text-slate-600">{t.crossText} <span className="float-right">55%</span></p></div><div className="rounded-2xl bg-slate-900 p-5 text-white"><p className="text-xs font-black uppercase tracking-wider text-teal-300">{t.next}</p><p className="mt-3 font-black">Part 7 · {t.inference}</p><span className="mt-4 inline-flex rounded-lg bg-teal-400 px-3 py-2 text-sm font-black text-slate-950">{t.start}</span></div></div></aside>; }
