import Link from "next/link";
import { AdminNav } from "@/components/admin/admin-nav";
import { requireAdmin } from "@/lib/admin/authorization";
import { getAdminOverview } from "@/lib/admin/service";
import { getPreferences } from "@/lib/i18n/get-translations";

const number = (value: unknown, locale: string) => Number(value ?? 0).toLocaleString(locale);
const money = (value: unknown, locale: string) => new Intl.NumberFormat(locale, { style: "currency", currency: "VND", maximumFractionDigits: 0 }).format(Number(value ?? 0));

function Metric({ label, value, note, tone = "slate" }: { label: string; value: string; note: string; tone?: "slate" | "teal" | "amber" }) {
  const styles = { slate: "border-slate-200 bg-white", teal: "border-teal-200 bg-teal-50/70", amber: "border-amber-200 bg-amber-50/70" };
  return <article className={`rounded-2xl border p-5 ${styles[tone]}`}><p className="text-xs font-black uppercase tracking-[0.16em] text-slate-500">{label}</p><p className="mt-3 text-3xl font-black tracking-tight text-slate-950">{value}</p><p className="mt-1 text-sm text-slate-600">{note}</p></article>;
}

function Panel({ title, eyebrow, href, linkLabel, children }: { title: string; eyebrow: string; href: string; linkLabel: string; children: React.ReactNode }) {
  return <section className="group rounded-3xl border border-slate-200 bg-white p-6 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[0.16em] text-teal-700">{eyebrow}</p><h2 className="mt-2 text-xl font-black text-slate-950">{title}</h2></div><Link className="shrink-0 rounded-full border border-slate-200 px-3 py-1.5 text-sm font-bold text-slate-700 transition group-hover:border-teal-600 group-hover:text-teal-800" href={href}>{linkLabel} →</Link></div>{children}</section>;
}

const auditLabels: Record<string, { vi: string; en: string }> = {
  CONTENT_PUBLISHED: { vi: "Xuất bản học liệu", en: "Content published" }, CONTENT_DRAFT_CREATED: { vi: "Tạo bản nháp học liệu", en: "Content draft created" },
  PREMIUM_GRANTED: { vi: "Cấp Premium", en: "Premium granted" }, PREMIUM_REVOKED: { vi: "Thu hồi Premium", en: "Premium revoked" },
  USER_SUSPENDED: { vi: "Tạm khóa người dùng", en: "User suspended" }, USER_REACTIVATED: { vi: "Mở khóa người dùng", en: "User reactivated" },
  CHALLENGE_PUBLISHED: { vi: "Công bố sự kiện", en: "Event published" }, IMPORT_COMMITTED: { vi: "Nhập ngân hàng câu hỏi", en: "Question batch imported" },
};

export default async function AdminPage() {
  const actor = await requireAdmin("ADMIN_DASHBOARD_READ");
  const [preferences, data] = await Promise.all([getPreferences(actor.id), getAdminOverview()]);
  const vi = preferences.interfaceLanguage === "vi";
  const locale = vi ? "vi-VN" : "en-US";
  const premiumRate = Number(data.total) ? Math.round(Number(data.premium) / Number(data.total) * 100) : 0;
  const attention = [
    Number(data.unverified) > 0 && { href: "/admin/users?verified=no", value: data.unverified, vi: "tài khoản chưa xác minh", en: "unverified accounts" },
    Number(data.content.draftGroups) > 0 && { href: "/admin/content/questions?lifecycle=draft", value: data.content.draftGroups, vi: "nhóm câu hỏi đang chờ hoàn thiện", en: "question groups awaiting review" },
    Number(data.payments.pending) > 0 && { href: "/admin/payments?status=PENDING", value: data.payments.pending, vi: "thanh toán đang chờ", en: "pending payments" },
    Number(data.challenges.drafts) > 0 && { href: "/admin/challenges", value: data.challenges.drafts, vi: "sự kiện đang ở bản nháp", en: "draft events" },
  ].filter(Boolean) as Array<{ href: string; value: unknown; vi: string; en: string }>;

  return <main className="min-h-screen bg-[radial-gradient(circle_at_top_left,_#ccfbf1_0,_transparent_30%),linear-gradient(to_bottom,_#f8fafc,_#f1f5f9)] px-4 py-6 text-slate-900 sm:px-6"><div className="mx-auto max-w-7xl"><AdminNav locale={preferences.interfaceLanguage}/>
    <header className="mt-8 overflow-hidden rounded-3xl bg-slate-950 p-6 text-white shadow-xl sm:p-8"><div className="flex flex-wrap items-end justify-between gap-6"><div><p className="text-xs font-black uppercase tracking-[0.22em] text-teal-300">{vi ? "Trung tâm điều hành" : "Operations center"}</p><h1 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">{vi ? "Toàn cảnh TOEIC GYM" : "TOEIC GYM at a glance"}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-300">{vi ? "Theo dõi tăng trưởng, học tập, học liệu, doanh thu và các việc cần xử lý từ một nơi." : "Monitor growth, learning, content, revenue, and operational work from one place."}</p></div><div className="flex gap-2"><Link className="rounded-xl bg-teal-400 px-4 py-3 text-sm font-black text-slate-950 hover:bg-teal-300" href="/admin/content/new">{vi ? "+ Tạo học liệu" : "+ Create content"}</Link><Link className="rounded-xl border border-slate-700 px-4 py-3 text-sm font-bold hover:border-slate-400" href="/admin/challenges/new">{vi ? "+ Tạo sự kiện" : "+ Create event"}</Link></div></div>
      <div className="mt-8 grid gap-px overflow-hidden rounded-2xl bg-slate-800 sm:grid-cols-2 lg:grid-cols-4">{[[vi ? "Người dùng" : "Users", number(data.total, locale), `+${number(data.new7, locale)} ${vi ? "trong 7 ngày" : "in 7 days"}`],[vi ? "Hoạt động học" : "Learning activity", number(data.learning.practice7, locale), vi ? "buổi luyện tập / 7 ngày" : "practice sessions / 7 days"],[vi ? "Doanh thu" : "Revenue", money(data.payments.revenue30, locale), vi ? "30 ngày gần nhất" : "last 30 days"],["Premium", `${premiumRate}%`, `${number(data.premium, locale)} ${vi ? "thành viên đang hiệu lực" : "active members"}`]].map(([label, value, note]) => <div className="bg-slate-900 p-5" key={label}><p className="text-xs font-bold uppercase tracking-widest text-slate-400">{label}</p><p className="mt-2 text-2xl font-black">{value}</p><p className="mt-1 text-xs text-slate-400">{note}</p></div>)}</div>
    </header>
    {attention.length > 0 && <section className="mt-6 rounded-2xl border border-amber-200 bg-amber-50 p-5"><div className="flex flex-wrap items-center gap-x-3 gap-y-2"><span className="rounded-full bg-amber-200 px-3 py-1 text-xs font-black uppercase tracking-wider text-amber-950">{vi ? "Cần chú ý" : "Needs attention"}</span>{attention.map(item => <Link className="font-semibold text-amber-950 underline decoration-amber-400 underline-offset-4" href={item.href} key={item.href}>{number(item.value, locale)} {vi ? item.vi : item.en}</Link>)}</div></section>}
    <section className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric label={vi ? "Đang hoạt động" : "Active users"} value={number(data.active, locale)} note={`${number(data.new30, locale)} ${vi ? "người dùng mới / 30 ngày" : "new users / 30 days"}`} tone="teal"/><Metric label={vi ? "Người học có hoạt động" : "Active learners"} value={number(data.learning.learners7, locale)} note={`${number(data.learning.practice30, locale)} ${vi ? "buổi luyện tập / 30 ngày" : "practice sessions / 30 days"}`}/><Metric label={vi ? "Đơn đã thanh toán" : "Paid orders"} value={number(data.payments.paid30, locale)} note={vi ? "Trong 30 ngày gần nhất" : "In the last 30 days"}/><Metric label={vi ? "Sự kiện đang diễn ra" : "Live events"} value={number(data.challenges.live, locale)} note={`${number(data.challenges.upcoming, locale)} ${vi ? "sự kiện sắp tới" : "upcoming events"}`} tone={Number(data.challenges.live) ? "teal" : "slate"}/></section>
    <div className="mt-8 grid gap-5 lg:grid-cols-2">
      <Panel title={vi ? "Người dùng & tăng trưởng" : "Users & growth"} eyebrow={vi ? "Cộng đồng" : "Community"} href="/admin/users" linkLabel={vi ? "Quản lý" : "Manage"}><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4">{[[vi?"Tổng":"Total",data.total],["Premium",data.premium],["Free",data.free],[vi?"Tạm khóa":"Suspended",data.suspended]].map(([label,value])=><div className="rounded-xl bg-slate-50 p-3" key={String(label)}><p className="text-sm text-slate-500">{label}</p><strong className="mt-1 block text-xl">{number(value,locale)}</strong></div>)}</div><div className="mt-5 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-teal-600" style={{width:`${premiumRate}%`}}/></div><p className="mt-2 text-xs text-slate-500">{vi ? `${premiumRate}% tài khoản đang có Premium hiệu lực.` : `${premiumRate}% of accounts currently have active Premium.`}</p></Panel>
      <Panel title={vi ? "Học liệu & xuất bản" : "Content & publishing"} eyebrow={vi ? "Ngân hàng câu hỏi" : "Question bank"} href="/admin/content" linkLabel={vi ? "Mở học liệu" : "Open content"}><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-3">{[[vi?"Câu đã xuất bản":"Published questions",data.content.publishedQuestions],[vi?"Câu bản nháp":"Draft questions",data.content.draftQuestions],[vi?"Nhóm đã xuất bản":"Published groups",data.content.publishedGroups],[vi?"Nhóm bản nháp":"Draft groups",data.content.draftGroups],["Media",data.content.readyMedia],[vi?"Bài viết":"Posts",data.content.publishedPosts]].map(([label,value])=><div className="rounded-xl bg-slate-50 p-3" key={String(label)}><p className="text-xs leading-5 text-slate-500">{label}</p><strong className="block text-xl">{number(value,locale)}</strong></div>)}</div></Panel>
      <Panel title={vi ? "Thanh toán & doanh thu" : "Payments & revenue"} eyebrow={vi ? "Thương mại" : "Commerce"} href="/admin/payments" linkLabel={vi ? "Xem giao dịch" : "View payments"}><p className="mt-5 text-3xl font-black">{money(data.payments.revenue30,locale)}</p><p className="mt-1 text-sm text-slate-500">{vi ? "Doanh thu ghi nhận trong 30 ngày" : "Revenue recorded in the last 30 days"}</p><div className="mt-5 flex flex-wrap gap-2"><span className="rounded-full bg-emerald-100 px-3 py-1.5 text-sm font-bold text-emerald-800">{number(data.payments.paid30,locale)} {vi?"đã trả":"paid"}</span><span className="rounded-full bg-amber-100 px-3 py-1.5 text-sm font-bold text-amber-900">{number(data.payments.pending,locale)} {vi?"đang chờ":"pending"}</span><span className="rounded-full bg-rose-100 px-3 py-1.5 text-sm font-bold text-rose-800">{number(data.payments.failed7,locale)} {vi?"lỗi / 7 ngày":"failed / 7 days"}</span></div></Panel>
      <Panel title={vi ? "Sản phẩm & chuyển đổi" : "Product & conversion"} eyebrow="Analytics" href="/admin/analytics" linkLabel={vi ? "Phân tích" : "Analyze"}><div className="mt-5 grid grid-cols-2 gap-3">{[[vi?"Người dùng/khách":"Users/guests",data.analytics.activeActors7],[vi?"Sự kiện ghi nhận":"Events captured",data.analytics.events7],[vi?"Đăng ký hoàn tất":"Signups completed",data.analytics.signups7],[vi?"Bắt đầu thanh toán":"Checkout starts",data.analytics.checkouts7]].map(([label,value])=><div className="rounded-xl bg-slate-50 p-3" key={String(label)}><p className="text-xs leading-5 text-slate-500">{label}</p><strong className="block text-xl">{number(value,locale)}</strong></div>)}</div><p className="mt-3 text-xs text-slate-500">{vi ? "Dữ liệu 7 ngày gần nhất." : "Data from the last 7 days."}</p></Panel>
    </div>
    <div className="mt-8 grid gap-5 lg:grid-cols-[1.1fr_.9fr]"><section className="rounded-3xl border border-slate-200 bg-white p-6"><p className="text-xs font-black uppercase tracking-[0.16em] text-teal-700">{vi ? "Lối tắt" : "Shortcuts"}</p><h2 className="mt-2 text-xl font-black">{vi ? "Công việc thường dùng" : "Frequent tasks"}</h2><div className="mt-5 grid gap-3 sm:grid-cols-2">{[["/admin/content/import",vi?"Nhập bộ câu hỏi":"Import question set",vi?"Kiểm tra JSON rồi nhập nguyên tử":"Validate JSON and import atomically"],["/admin/content/questions?lifecycle=draft",vi?"Duyệt bản nháp":"Review drafts",vi?"Kiểm tra và xuất bản học liệu":"Review and publish content"],["/admin/users",vi?"Tra cứu người dùng":"Find a user",vi?"Gói, trạng thái và hoạt động học":"Plan, status, and learning activity"],["/admin/audit",vi?"Kiểm tra nhật ký":"Inspect audit log",vi?"Theo dõi thay đổi quản trị":"Track administrative changes"]].map(([href,title,description])=><Link className="rounded-2xl border border-slate-200 p-4 transition hover:border-teal-500 hover:bg-teal-50" href={href} key={href}><strong>{title} →</strong><span className="mt-1 block text-sm text-slate-500">{description}</span></Link>)}</div></section>
      <section className="rounded-3xl border border-slate-200 bg-white p-6"><div className="flex items-center justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[0.16em] text-teal-700">{vi ? "Gần đây" : "Recent"}</p><h2 className="mt-2 text-xl font-black">{vi ? "Hoạt động quản trị" : "Admin activity"}</h2></div><Link className="text-sm font-bold text-teal-800" href="/admin/audit">{vi?"Xem tất cả":"View all"} →</Link></div><div className="mt-5 divide-y divide-slate-100">{data.recentAudit.map((item) => <div className="py-3 first:pt-0" key={`${item.action}-${item.createdAt.toISOString()}`}><p className="font-semibold">{auditLabels[item.action]?.[vi?"vi":"en"] ?? item.action.replaceAll("_"," ").toLowerCase()}</p><p className="mt-1 text-xs text-slate-500">{item.actorEmail ?? (vi?"Hệ thống":"System")} · {item.createdAt.toLocaleString(locale,{timeZone:"Asia/Ho_Chi_Minh"})}</p></div>)}{data.recentAudit.length===0&&<p className="py-6 text-sm text-slate-500">{vi?"Chưa có hoạt động quản trị.":"No admin activity yet."}</p>}</div></section></div>
  </div></main>;
}
