var R=require("../../chunks/[turbopack]_runtime.js")("server/app/sitemap.xml/route.js")
R.c("server/chunks/[root-of-the-server]__0dczycj._.js")
R.c("server/chunks/node_modules_next_1zdbrne._.js")
R.c("server/chunks/_1em9c17._.js")
R.c("server/chunks/_0pq3p4i._.js")
R.c("server/chunks/[root-of-the-server]__00_hq9v._.js")
R.c("server/chunks/_0zjiehr._.js")
R.c("server/chunks/_next-internal_server_app_sitemap_xml_route_actions_05l5km9.js")
R.m(83345)
module.exports=R.m(83345).exports
