import Link from "next/link";
import { ActiveLearnerLinks } from "@/components/active-learner-links";
import { LanguageSwitcher } from "@/components/language-switcher";
import type { InterfaceLanguage } from "@/lib/i18n/config";
import { getTranslations } from "@/lib/i18n/get-translations";
import { getCurrentUser } from "@/lib/auth/session";
import { getPremiumAccount } from "@/lib/premium/presentation";
import { PremiumAvatar } from "@/components/premium/premium-avatar";
import { PremiumBadge } from "@/components/premium/premium-badge";
import { signOut } from "@/app/dashboard/actions";

export async function LearnerNav({ locale, showPremiumIdentity = true }: { locale: InterfaceLanguage; showPremiumIdentity?: boolean }) {
  const t = getTranslations(locale);
  const user=await getCurrentUser(); const account=user?await getPremiumAccount(user.id,user.email):null; const decorated=Boolean(showPremiumIdentity&&account?.isPremium);
  const items = [{ href: "/dashboard", label: t.navigation.dashboard }, { href: "/practice", label: t.navigation.practice }, { href: "/mistakes", label: t.mastery.title }, { href: "/progress", label: t.navigation.progress }, { href: "/ranking", label: locale === "vi" ? "Xếp hạng" : "Ranking" }, { href: "/demo-test", label: t.demoTest.shortTitle }];
  return <header className="grid gap-3 border-b border-slate-200 pb-4 md:grid-cols-[auto_1fr_auto] md:items-center"><Link className="text-xl font-black tracking-tight" href="/dashboard">{t.common.brand}</Link><div className="min-w-0 md:justify-self-center"><ActiveLearnerLinks items={items} label={t.navigation.mainLabel} /></div><div className="flex min-w-0 items-center justify-end gap-2"><LanguageSwitcher locale={locale} />{account?<details className="group relative"><summary className="flex min-h-11 cursor-pointer list-none items-center gap-2 rounded-xl px-2 hover:bg-white focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-teal-700"><PremiumAvatar avatarUrl={account.avatarUrl} name={account.name} premium={decorated} size="sm"/><span className="hidden max-w-32 truncate text-sm font-bold xl:inline">{account.name}</span>{decorated?<PremiumBadge className="hidden 2xl:inline-flex"/>:null}<span aria-hidden="true" className="text-xs text-slate-500">▾</span></summary><div className="absolute right-0 z-30 mt-2 w-72 rounded-2xl border border-slate-200 bg-white p-4 shadow-xl"><div className="flex min-w-0 items-center gap-3"><PremiumAvatar avatarUrl={account.avatarUrl} name={account.name} premium={decorated}/><div className="min-w-0"><p className="truncate font-black">{account.name}</p>{decorated?<div className="mt-1"><PremiumBadge/></div>:<p className="text-sm text-slate-500">Free</p>}</div></div>{decorated?<p className="mt-3 rounded-lg bg-amber-50 p-2 text-sm font-semibold text-amber-950">{locale==="vi"?"Premium đang hoạt động":"Premium active"}</p>:null}<nav className="mt-3 grid text-sm font-bold"><Link className="rounded-lg px-3 py-2 hover:bg-slate-50" href="/settings">{t.navigation.settings}</Link><Link className="rounded-lg px-3 py-2 hover:bg-slate-50" href="/billing">{locale==="vi"?"Thanh toán và gói":"Billing & plan"}</Link></nav><form action={signOut} className="mt-2 border-t border-slate-100 pt-2"><button className="w-full rounded-lg px-3 py-2 text-left text-sm font-bold text-red-700 hover:bg-red-50">{t.navigation.signOut}</button></form></div></details>:<Link className="rounded-lg px-3 py-2 text-sm font-semibold text-slate-600 hover:bg-white" href="/settings">{t.navigation.settings}</Link>}</div></header>;
}
