import Link from "next/link";
import type { InterfaceLanguage } from "@/lib/i18n/config";
import { getMarketingTranslations } from "@/lib/i18n/marketing";

type Props = { locale: InterfaceLanguage; compact?: boolean; startHref?: string };
export function PricingSection({ locale, compact = false, startHref = "/sign-in" }: Props) {
  const t = getMarketingTranslations(locale).pricing;
  return <section className="mx-auto max-w-7xl px-5 py-16 sm:px-6 sm:py-20" id="pricing"><div><p className="text-sm font-black uppercase tracking-[.16em] text-teal-700">{t.eyebrow}</p><h2 className="mt-3 max-w-3xl text-3xl font-black tracking-tight sm:text-4xl">{t.title}</h2><p className="mt-4 max-w-2xl text-lg leading-8 text-slate-600">{t.intro}</p></div><div className="mt-10 grid gap-5 lg:grid-cols-2"><article className="rounded-3xl border-2 border-teal-700 bg-white p-7 sm:p-9"><p className="text-sm font-black uppercase tracking-wider text-teal-700">{t.available}</p><h3 className="mt-3 text-2xl font-black">{t.free}</h3><p className="mt-2 text-4xl font-black">{t.price}</p><p className="mt-3 text-slate-600">{t.freeBody}</p><ul className="mt-6 grid gap-3 text-sm font-semibold">{t.freeFeatures.map((feature) => <li key={feature}>✓ <span className="ml-2">{feature}</span></li>)}</ul><Link className="mt-8 inline-flex min-h-12 w-full items-center justify-center rounded-xl bg-teal-700 px-5 font-black text-white sm:w-auto" href={startHref}>{t.start}</Link></article><article className="rounded-3xl border border-slate-200 bg-slate-100 p-7 sm:p-9"><p className="text-sm font-black uppercase tracking-wider text-slate-500">{t.planned}</p><div className="mt-3 flex flex-wrap items-center gap-3"><h3 className="text-2xl font-black">{t.premium}</h3><span className="rounded-full bg-slate-800 px-3 py-1 text-xs font-black text-white">{t.soon}</span></div><p className="mt-5 text-4xl font-black">—</p><p className="mt-3 text-slate-600">{t.premiumBody}</p><ul className="mt-6 grid gap-3 text-sm font-semibold text-slate-600">{t.premiumFeatures.map((feature) => <li key={feature}>○ <span className="ml-2">{feature}</span></li>)}</ul><button className="mt-8 min-h-12 rounded-xl bg-slate-200 px-5 font-black text-slate-500" disabled type="button">{t.soon}</button></article></div>{compact ? <div className="mt-8 text-center"><Link className="font-black text-teal-800" href="/pricing">{t.compare} →</Link></div> : null}</section>;
}
