module.exports=[57562,(e,t,r)=>{t.exports=e.x("argon2-f9a25551ac54f3a1",()=>require("argon2-f9a25551ac54f3a1"))},70406,(e,t,r)=>{t.exports=e.x("next/dist/compiled/@opentelemetry/api",()=>require("next/dist/compiled/@opentelemetry/api"))},18622,(e,t,r)=>{t.exports=e.x("next/dist/compiled/next-server/app-page-turbo.runtime.prod.js",()=>require("next/dist/compiled/next-server/app-page-turbo.runtime.prod.js"))},20635,(e,t,r)=>{t.exports=e.x("next/dist/server/app-render/action-async-storage.external.js",()=>require("next/dist/server/app-render/action-async-storage.external.js"))},24725,(e,t,r)=>{t.exports=e.x("next/dist/server/app-render/after-task-async-storage.external.js",()=>require("next/dist/server/app-render/after-task-async-storage.external.js"))},56704,(e,t,r)=>{t.exports=e.x("next/dist/server/app-render/work-async-storage.external.js",()=>require("next/dist/server/app-render/work-async-storage.external.js"))},32319,(e,t,r)=>{t.exports=e.x("next/dist/server/app-render/work-unit-async-storage.external.js",()=>require("next/dist/server/app-render/work-unit-async-storage.external.js"))},59043,(e,t,r)=>{t.exports=e.x("next/dist/server/runtime-reacts.external.js",()=>require("next/dist/server/runtime-reacts.external.js"))},93695,(e,t,r)=>{t.exports=e.x("next/dist/shared/lib/no-fallback-error.external.js",()=>require("next/dist/shared/lib/no-fallback-error.external.js"))},66680,(e,t,r)=>{t.exports=e.x("node:crypto",()=>require("node:crypto"))},81111,(e,t,r)=>{t.exports=e.x("node:stream",()=>require("node:stream"))},23862,e=>e.a(async(t,r)=>{try{var a=await e.y("pg-587764f78a6c7a9c");e.n(a),r()}catch(e){r(e)}},!0),23774,e=>e.a(async(t,r)=>{try{var a=e.i(18899),s=e.i(79371),n=e.i(86371),i=e.i(65179),o=t([s]);[s]=o.then?(await o)():o;let c={signup:{attempts:5,windowMs:36e5},login:{attempts:10,windowMs:9e5},forgot_password:{attempts:5,windowMs:36e5},reset_password:{attempts:8,windowMs:36e5},verify_email:{attempts:12,windowMs:9e5},activate_account:{attempts:6,windowMs:36e5},resend_verification:{attempts:5,windowMs:36e5},google_oauth:{attempts:20,windowMs:9e5},guest_practice:{attempts:20,windowMs:9e5},product_analytics:{attempts:60,windowMs:9e5},support_feedback:{attempts:5,windowMs:36e5}};async function d(e,t){let r=c[e],o=(0,i.hashToken)(`${e}:${t.toLowerCase()}`),d=(await s.db.execute(a.sql`
    insert into ${n.authRateLimits} (key_hash, action, window_started_at, attempts, updated_at)
    values (${o}, ${e}, now(), 1, now())
    on conflict (key_hash) do update set
      attempts = case when ${n.authRateLimits.windowStartedAt} < now() - (${r.windowMs} * interval '1 millisecond') then 1 else ${n.authRateLimits.attempts} + 1 end,
      window_started_at = case when ${n.authRateLimits.windowStartedAt} < now() - (${r.windowMs} * interval '1 millisecond') then now() else ${n.authRateLimits.windowStartedAt} end,
      blocked_until = case
        when ${n.authRateLimits.windowStartedAt} < now() - (${r.windowMs} * interval '1 millisecond') then null
        when ${n.authRateLimits.attempts} + 1 > ${r.attempts} then coalesce(${n.authRateLimits.blockedUntil}, ${n.authRateLimits.windowStartedAt} + (${r.windowMs} * interval '1 millisecond'))
        else ${n.authRateLimits.blockedUntil}
      end,
      updated_at = now()
    returning attempts, blocked_until`)).rows[0];if(d&&(Number(d.attempts)>r.attempts||d.blocked_until&&new Date(d.blocked_until)>new Date))throw Error("RATE_LIMITED")}e.s(["enforceRateLimit",0,d]),r()}catch(e){r(e)}},!1),32371,e=>{"use strict";var t=e.i(93458),r=e.i(65179);let a="tg_guest";async function s(){let e=(await (0,t.cookies)()).get(a)?.value;return e?(0,r.hashToken)(e):null}async function n(){(await (0,t.cookies)()).delete(a)}e.s(["clearGuestIdentity",0,n,"getGuestOwnerHash",0,s])},68164,e=>{"use strict";class t extends Error{code;constructor(e){super(e),this.code=e}}async function r(e,r){if("application/json"!==e.headers.get("content-type")?.split(";",1)[0].trim().toLowerCase())throw new t("INVALID_CONTENT_TYPE");let a=Number(e.headers.get("content-length")??0);if(Number.isFinite(a)&&a>r)throw new t("BODY_TOO_LARGE");let s=e.body?.getReader();if(!s)throw new t("INVALID_JSON");let n=[],i=0;for(;;){let{done:e,value:a}=await s.read();if(e)break;if((i+=a.byteLength)>r)throw await s.cancel().catch(()=>void 0),new t("BODY_TOO_LARGE");n.push(a)}let o=new Uint8Array(i),d=0;for(let e of n)o.set(e,d),d+=e.byteLength;try{return JSON.parse(new TextDecoder("utf-8",{fatal:!0}).decode(o))}catch{throw new t("INVALID_JSON")}}e.s(["RequestBodyError",0,t,"readBoundedJson",0,r])}];

//# sourceMappingURL=%5Broot-of-the-server%5D__099s-wq._.js.map