import Link from "next/link";
import { startGuestPractice } from "@/app/practice/actions";
import { getCookieLanguage } from "@/lib/i18n/get-translations";

export default async function TryPage({ searchParams }: { searchParams: Promise<{ error?: string }> }) {
  const [locale, query] = await Promise.all([getCookieLanguage(), searchParams]); const vi = locale === "vi";
  const choices = [["listening", vi ? "Thử Listening" : "Try Listening", vi ? "9 câu, giữ nguyên nhóm Part 3" : "9 questions, complete Part 3 groups"], ["reading", vi ? "Thử Reading" : "Try Reading", vi ? "Khoảng 10 câu, giữ nguyên bài đọc" : "About 10 questions, complete reading groups"]] as const;
  return <main className="min-h-screen bg-slate-50 px-5 py-12 text-slate-900"><div className="mx-auto max-w-3xl"><Link className="font-semibold text-teal-700" href="/">← {vi ? "Trang chủ" : "Home"}</Link><h1 className="mt-8 text-4xl font-black">{vi ? "Thử TOEICGym miễn phí" : "Try TOEICGym free"}</h1><p className="mt-3 text-lg text-slate-600">{vi ? "Chọn bài đánh giá đầu vào hoặc một bài luyện ngắn. Không cần tài khoản." : "Choose a diagnostic or short practice. No account required."}</p>{query.error ? <p className="mt-5 rounded-xl bg-red-50 p-4 text-red-800">{vi ? "Chưa thể tạo bài luyện. Vui lòng thử lại." : "Could not create practice. Please try again."}</p> : null}<section className="mt-8 rounded-3xl bg-slate-900 p-7 text-white"><p className="text-sm font-black uppercase tracking-wider text-teal-300">{vi ? "Được đề xuất" : "Recommended"}</p><h2 className="mt-2 text-2xl font-black">{vi ? "Làm bài đánh giá nhanh" : "Take a quick diagnostic"}</h2><p className="mt-2 text-slate-300">{vi ? "Listening Part 1–4 và Reading Part 5–7 để tạo hồ sơ ban đầu." : "Listening Parts 1–4 and Reading Parts 5–7 for an initial profile."}</p><Link className="mt-5 inline-flex min-h-12 items-center rounded-xl bg-teal-400 px-6 font-bold text-slate-950" href="/diagnostic">{vi ? "Bắt đầu đánh giá" : "Start diagnostic"}</Link></section><div className="mt-5 grid gap-5 sm:grid-cols-2">{choices.map(([kind,title,body]) => <form action={startGuestPractice} className="rounded-3xl border border-slate-200 bg-white p-7 shadow-sm" key={kind}><input name="kind" type="hidden" value={kind}/><h2 className="text-2xl font-black">{title}</h2><p className="mt-2 text-slate-600">{body}</p><button className="mt-6 min-h-12 rounded-xl bg-teal-700 px-6 font-bold text-white" type="submit">{vi ? "Bắt đầu" : "Start"}</button></form>)}</div></div></main>;
}
