import pg from "pg";
import { createHash } from "node:crypto";
import { ConfiguredR2MediaStorage } from "../src/lib/media/r2-client.ts";
import { LocalMediaStorage } from "../src/lib/media/local-storage.ts";

const execute=process.argv.includes("--execute"), dry=process.argv.includes("--dry-run");if(execute===dry)throw new Error("Specify exactly one of --dry-run or --execute");
for(const name of ["DATABASE_URL","LOCAL_MEDIA_ROOT","R2_ENDPOINT","R2_ACCESS_KEY_ID","R2_SECRET_ACCESS_KEY","R2_BUCKET_NAME"])if(!process.env[name])throw new Error(`Missing ${name}`);
const pool=new pg.Pool({connectionString:process.env.DATABASE_URL});const r2=new ConfiguredR2MediaStorage({endpoint:process.env.R2_ENDPOINT!,accessKeyId:process.env.R2_ACCESS_KEY_ID!,secretAccessKey:process.env.R2_SECRET_ACCESS_KEY!,bucketName:process.env.R2_BUCKET_NAME!});const local=new LocalMediaStorage(process.env.LOCAL_MEDIA_ROOT!,process.env.APP_URL??"http://localhost:3000",process.env.MEDIA_SIGNING_SECRET??"migration-only-secret-must-be-32chars");
const counts={examined:0,migrated:0,alreadyPresent:0,verified:0,failed:0,skipped:0};
try{const {rows}=await pool.query<{id:string;storage_key:string;byte_size:number;checksum:string}>("select id, storage_key, byte_size, checksum from media_assets where storage_provider='R2' and status='READY' order by id");counts.examined=rows.length;for(const row of rows){try{if(await local.exists(row.storage_key)){const body=await local.read(row.storage_key);if(body.byteLength!==Number(row.byte_size)||createHash("sha256").update(body).digest("hex")!==row.checksum)throw new Error("EXISTING_LOCAL_INTEGRITY_MISMATCH");if(execute)await pool.query("update media_assets set storage_provider='LOCAL', updated_at=now() where id=$1 and storage_provider='R2'",[row.id]);counts.alreadyPresent++;counts.verified++;continue}if(dry){counts.skipped++;continue}const body=await r2.download(row.storage_key);if(!body.byteLength||body.byteLength!==Number(row.byte_size)||createHash("sha256").update(body).digest("hex")!==row.checksum)throw new Error("INTEGRITY_MISMATCH");await local.upload({key:row.storage_key,body,contentType:"application/octet-stream"});const written=await local.read(row.storage_key);if(createHash("sha256").update(written).digest("hex")!==row.checksum)throw new Error("LOCAL_VERIFY_FAILED");await pool.query("update media_assets set storage_provider='LOCAL', updated_at=now() where id=$1 and storage_provider='R2'",[row.id]);counts.migrated++;counts.verified++}catch(error){counts.failed++;console.error(`Failed media ${row.id}: ${error instanceof Error?error.message:"UNKNOWN"}`)}}console.log(JSON.stringify({mode:dry?"dry-run":"execute",...counts},null,2));if(counts.failed)process.exitCode=1}finally{await pool.end()}
