import Link from "next/link";
import { notFound } from "next/navigation";
import { AdminNav } from "@/components/admin/admin-nav";
import { PendingSubmit } from "@/components/admin/pending-submit";
import { requireAdmin } from "@/lib/admin/authorization";
import { getImportBatchSummary } from "@/lib/admin/content";
import { getPreferences } from "@/lib/i18n/get-translations";
import { publishBatchAction } from "../../actions";

export default async function Page({params,searchParams}:{params:Promise<{batchKey:string}>,searchParams:Promise<Record<string,string|undefined>>}){
  const actor=await requireAdmin("CONTENT_READ"),prefs=await getPreferences(actor.id),{batchKey}=await params,q=await searchParams,summary=await getImportBatchSummary(batchKey);if(!summary)notFound();
  const draftIds=new Set(summary.items.filter(i=>i.status==="draft").map(i=>i.groupId)); const blocked=new Map(summary.validations.filter(v=>v.issues.length).map(v=>[v.groupId,v.issues]));
  return <main className="min-h-screen bg-slate-50 px-4 py-6"><div className="mx-auto max-w-6xl"><AdminNav locale={prefs.interfaceLanguage}/><nav className="mt-6 text-sm"><Link className="underline" href="/admin/content/questions">Ngân hàng câu hỏi</Link> / Import batch</nav>
    <header className="mt-4 rounded-2xl border bg-white p-6"><p className="text-sm font-bold uppercase tracking-widest text-teal-700">Import batch</p><h1 className="mt-1 text-3xl font-black">{summary.batchKey}</h1><p className="mt-1 text-slate-600">{summary.name}</p><dl className="mt-5 grid gap-4 text-sm sm:grid-cols-2 lg:grid-cols-4"><div><dt className="font-bold text-slate-500">Provenance</dt><dd>{summary.sourceType}<br/>{summary.reviewStatus}</dd></div><div><dt className="font-bold text-slate-500">Quyền sử dụng</dt><dd>{summary.rightsNote}</dd></div><div><dt className="font-bold text-slate-500">Import bởi</dt><dd>{summary.importedBy}<br/>{summary.createdAt.toLocaleString()}</dd></div><div><dt className="font-bold text-slate-500">Schema</dt><dd>{summary.schemaVersion} · {summary.filename}</dd></div></dl></header>
    {q.error&&<p role="alert" className="mt-4 rounded-xl bg-red-100 p-4 text-red-900">Batch không được publish: {decodeURIComponent(q.error).split("|").join(" · ")}</p>}{q.published&&<p className="mt-4 rounded-xl bg-emerald-100 p-4 text-emerald-900">Đã publish {q.published} nhóm trong một transaction.</p>}
    <section className="mt-5 grid gap-4 lg:grid-cols-2"><div className="rounded-2xl border bg-white p-5"><h2 className="text-xl font-black">Trạng thái</h2><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4">{Object.entries({Imported:summary.counts.imported,Draft:summary.counts.draft,Published:summary.counts.published,Blocked:summary.counts.blocked}).map(([label,value])=><div key={label} className="rounded-xl bg-slate-50 p-3"><p className="text-xs font-bold uppercase text-slate-500">{label}</p><p className="text-2xl font-black">{value}</p></div>)}</div></div><div className="rounded-2xl border bg-white p-5"><h2 className="text-xl font-black">Validation</h2><p className={`mt-3 rounded-lg p-3 font-bold ${summary.valid?"bg-emerald-50 text-emerald-900":"bg-red-50 text-red-900"}`}>{summary.valid?`✓ ${summary.counts.draft} Draft hợp lệ và sẵn sàng publish`:`✕ ${summary.counts.blocked} nhóm bị chặn; toàn batch sẽ không được publish`}</p><p className="mt-3 text-sm">Phân bố: {[1,2,3,4,5,6,7].filter(p=>summary.partDistribution[p]).map(p=>`P${p}: ${summary.partDistribution[p]}`).join(" · ")}</p></div></section>
    <section className="mt-5 rounded-2xl border bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-black">Review questions</h2><p className="text-sm text-slate-600">Thứ tự cố định theo Part, thời điểm import và ID.</p></div><Link href={`/admin/content/questions?batch=${encodeURIComponent(summary.batchKey)}&lifecycle=draft`} className="rounded-lg border px-4 py-2 font-bold">Mở hàng đợi Draft</Link></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[700px] text-left"><thead><tr className="border-b bg-slate-50"><th className="p-3">Item</th><th>Part</th><th>Status</th><th>Validation</th></tr></thead><tbody>{summary.items.map(item=><tr key={item.groupId} className="border-b"><td className="p-3"><Link className="font-bold text-teal-700" href={`/admin/content/questions/${item.groupId}?batch=${encodeURIComponent(summary.batchKey)}&lifecycle=draft`}>{item.title}</Link><small className="block text-slate-500">{item.externalItemId}</small></td><td>P{item.part}</td><td>{item.status.toUpperCase()}</td><td>{blocked.has(item.groupId)?<span className="text-red-700">Blocked: {blocked.get(item.groupId)!.join(" · ")}</span>:draftIds.has(item.groupId)?<span className="text-emerald-700">Ready</span>:"—"}</td></tr>)}</tbody></table></div></section>
    <section className="my-5 flex flex-wrap items-center justify-between gap-4 rounded-2xl border border-teal-200 bg-teal-50 p-5"><div><h2 className="text-lg font-black">Publish toàn bộ Draft hợp lệ</h2><p>{summary.counts.draft} nhóm sẽ publish · {summary.counts.blocked} bị chặn · thao tác được ghi audit.</p></div>{summary.valid&&summary.counts.draft>0?<form action={publishBatchAction}><input type="hidden" name="batchKey" value={summary.batchKey}/><PendingSubmit confirmMessage={`Publish batch ${summary.batchKey}? ${summary.counts.draft} nhóm sẽ được publish trong một transaction.`} pendingLabel="Đang publish batch…" className="rounded-lg bg-teal-700 px-5 py-3 font-bold text-white">Publish {summary.counts.draft}</PendingSubmit></form>:<button disabled className="rounded-lg bg-slate-300 px-5 py-3 font-bold text-slate-600">Không thể publish</button>}</section>
  </div></main>;
}
