import Link from "next/link";
import { AdminNav } from "@/components/admin/admin-nav";
import { requireAdmin } from "@/lib/admin/authorization";
import { getPreferences } from "@/lib/i18n/get-translations";
import { funnelRows, periodDays } from "@/lib/product-analytics/calculate";
import { getProductAnalytics } from "@/lib/product-analytics/queries";

const pct = (a: number, b: number) => b ? `${Math.round(a / b * 1000) / 10}%` : "—";
export default async function AnalyticsPage({ searchParams }: { searchParams: Promise<{ period?: string | string[] }> }) {
  const actor = await requireAdmin("ADMIN_DASHBOARD_READ");
  const [prefs, query] = await Promise.all([getPreferences(actor.id), searchParams]);
  const vi = prefs.interfaceLanguage === "vi", period = periodDays(typeof query.period === "string" ? query.period : undefined), data = await getProductAnalytics(period);
  const funnel = funnelRows(data.events, data.activated);
  const labels = vi ? ["Landing được ghi nhận", "Mở trang Try", "Bắt đầu chẩn đoán / bài thử", "Hoàn thành", "Đăng ký", "Kích hoạt"] : ["Tracked landing", "Opened Try", "Started diagnostic / guest practice", "Completed", "Signed up", "Activated"];
  const cards = [[vi?"Đăng ký mới":"New users",data.signups],[vi?"Người học kích hoạt":"Activated learners",data.activated],[vi?"Tỷ lệ kích hoạt":"Activation rate",pct(data.activated,data.signups)],["DAU",data.dau],["WAU",data.wau],[vi?"Phiên học hoàn thành":"Completed learning sessions",data.sessions],[vi?"Câu đã luyện":"Questions practiced",data.questions]];
  return <main className="min-h-screen bg-slate-50 px-4 py-6 text-slate-900 sm:px-6"><div className="mx-auto max-w-7xl"><AdminNav locale={prefs.interfaceLanguage}/><div className="mt-8 flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-black uppercase tracking-[.15em] text-teal-700">Product intelligence</p><h1 className="mt-2 text-3xl font-black">{vi?"Phân tích sản phẩm":"Product analytics"}</h1><p className="mt-2 max-w-3xl text-slate-600">{vi?"Dữ liệu first-party trong PostgreSQL. “Kích hoạt” = người dùng đăng nhập hoàn thành hoạt động học có ý nghĩa đầu tiên.":"First-party PostgreSQL data. “Activated” = a signed-in user completes their first meaningful learning activity."}</p></div><nav className="flex rounded-xl border bg-white p-1" aria-label={vi?"Khoảng thời gian":"Period"}>{[["today",vi?"Hôm nay":"Today"],["7d","7 days"],["30d","30 days"]].map(([value,label])=><Link className={`rounded-lg px-4 py-2 text-sm font-bold ${period===value?"bg-slate-900 text-white":""}`} href={`/admin/analytics?period=${value}`} key={value}>{label}</Link>)}</nav></div>
  <section className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-6">{cards.map(([label,value])=><article className="rounded-2xl border bg-white p-5" key={String(label)}><p className="text-sm font-bold text-slate-500">{label}</p><p className="mt-2 text-3xl font-black">{value}</p></article>)}</section>
  <div className="mt-6 grid gap-6 xl:grid-cols-[1.35fr_.65fr]"><section className="rounded-3xl border bg-white p-5 sm:p-7"><h2 className="text-xl font-black">{vi?"Phễu kích hoạt":"Activation funnel"}</h2>{funnel.some(x=>x.count)?<ol className="mt-6 space-y-4">{funnel.map((row,i)=><li key={labels[i]}><div className="flex flex-wrap justify-between gap-2 text-sm"><strong>{labels[i]}</strong><span>{row.count} · {row.conversion}% {vi?"chuyển đổi":"conversion"} · {row.dropoff}% {vi?"rời bước":"drop-off"}</span></div><div className="mt-2 h-3 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-teal-600" style={{width:`${Math.max(2,Math.min(100,funnel[0].count?row.count/funnel[0].count*100:0))}%`}}/></div></li>)}</ol>:<Empty vi={vi}/>}</section>
  <section className="rounded-3xl border bg-slate-900 p-5 text-white sm:p-7"><h2 className="text-xl font-black">{vi?"Chuyển đổi Premium":"Premium conversion"}</h2><dl className="mt-5 space-y-4">{[[vi?"Lượt xem Pricing":"Pricing views",data.events.pricing_viewed??0],[vi?"Bắt đầu checkout":"Checkout starts",data.events.checkout_started??0],[vi?"Tạo checkout thành công":"Checkout created",data.checkoutCreated],[vi?"Kích hoạt Premium":"Premium activations",data.premiumActivated]].map(([k,v])=><div className="flex justify-between border-b border-slate-700 pb-3" key={String(k)}><dt>{k}</dt><dd className="text-xl font-black text-teal-300">{v}</dd></div>)}</dl><p className="mt-5 text-sm text-slate-300">Pricing → Checkout: {pct(data.events.checkout_started??0,data.events.pricing_viewed??0)}<br/>Checkout → Premium: {pct(data.premiumActivated,data.checkoutCreated)}<br/>Signup → Premium: {pct(data.premiumActivated,data.signups)}</p></section></div>
  <section className="mt-6 rounded-3xl border bg-white p-5 sm:p-7"><h2 className="text-xl font-black">{vi?"Giữ chân theo cohort đăng ký":"Signup cohort retention"}</h2><p className="mt-2 text-sm text-slate-600">{vi?"Quay lại = hoàn thành một phiên học trong đúng ngày thứ N sau đăng ký. Trang chủ không được tính.":"Returned = completed a learning session on day N after signup. Homepage visits do not count."}</p><div className="mt-5 grid gap-4 sm:grid-cols-3">{[1,7,30].map(day=>{const r=data.retention[String(day)]??{cohort:0,returned:0};return <article className="rounded-2xl bg-slate-50 p-5" key={day}><p className="font-black">D{day}</p><p className="mt-2 text-3xl font-black text-teal-700">{pct(r.returned,r.cohort)}</p><p className="mt-1 text-sm text-slate-600">{r.returned}/{r.cohort} {vi?"người học":"learners"}</p>{r.cohort<20?<p className="mt-3 text-xs text-amber-700">{vi?"Mẫu nhỏ; chưa nên kết luận xu hướng.":"Small sample; avoid trend claims."}</p>:null}</article>})}</div></section>
  <p className="mt-6 text-xs leading-5 text-slate-500">{vi?"Lượt landing là lượt được trình duyệt ghi nhận, có thể gồm bot/kiểm tra uptime. Event thô được thiết kế giữ 18 tháng; chưa tự động xóa trong Task 23. Backup PostgreSQL hiện tại tự nhiên bao gồm bảng analytics.":"Landing counts are browser-tracked visits and may include bots/uptime checks. Raw events are designed for 18-month retention; Task 23 does not auto-delete them. Existing PostgreSQL backups naturally include analytics."}</p></div></main>;
}
function Empty({vi}:{vi:boolean}) { return <div className="mt-6 rounded-2xl border border-dashed p-8 text-center"><p className="font-black">{vi?"Chưa có dữ liệu trong khoảng này":"No data in this period"}</p><p className="mt-2 text-sm text-slate-600">{vi?"Các chỉ số sẽ xuất hiện khi có hành vi thật; không dùng dữ liệu giả.":"Metrics appear after real activity; no fake production data is used."}</p></div> }
