var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/auth/callback/route.js")
R.c("server/chunks/[root-of-the-server]__05510yd._.js")
R.c("server/chunks/node_modules_next_1zdbrne._.js")
R.c("server/chunks/_1n3vo_t._.js")
R.c("server/chunks/_1o3jxv_._.js")
R.c("server/chunks/_0pq3p4i._.js")
R.c("server/chunks/_0zjiehr._.js")
R.c("server/chunks/[root-of-the-server]__12hl4k9._.js")
R.c("server/chunks/[root-of-the-server]__00_hq9v._.js")
R.c("server/chunks/_next-internal_server_app_auth_callback_route_actions_0gq6cy0.js")
R.m(79799)
module.exports=R.m(79799).exports
