var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/auth/google/route.js")
R.c("server/chunks/[root-of-the-server]__0xokdne._.js")
R.c("server/chunks/_077-ve3._.js")
R.c("server/chunks/[root-of-the-server]__00_hq9v._.js")
R.c("server/chunks/node_modules_next_1zdbrne._.js")
R.c("server/chunks/_00y5nb3._.js")
R.c("server/chunks/_0pq3p4i._.js")
R.c("server/chunks/[root-of-the-server]__12hl4k9._.js")
R.c("server/chunks/_1z3vu6o._.js")
R.c("server/chunks/_next-internal_server_app_api_auth_google_route_actions_0rae5gv.js")
R.m(59636)
module.exports=R.m(59636).exports
