import Link from "next/link";
import { getCurrentUser } from "@/lib/auth/session";
import { getCookieLanguage } from "@/lib/i18n/get-translations";
import { startDiagnostic } from "./actions";

export default async function DiagnosticLandingPage({ searchParams }: { searchParams: Promise<{ error?: string }> }) {
  const [user, locale, query] = await Promise.all([getCurrentUser(), getCookieLanguage(), searchParams]); const vi = locale === "vi";
  return <main className="min-h-screen bg-slate-50 px-5 py-12 text-slate-900"><div className="mx-auto max-w-3xl"><Link className="font-semibold text-teal-700" href={user ? "/dashboard" : "/try"}>← {vi ? "Quay lại" : "Back"}</Link>{query.error ? <p className="mt-5 rounded-xl border border-amber-200 bg-amber-50 p-4 text-amber-900" role="alert">{query.error === "expired" ? (vi ? "Bài đánh giá đã hết hạn. Hãy bắt đầu một bài mới." : "Your diagnostic expired. Start a new assessment.") : (vi ? "Bài đánh giá hiện không khả dụng. Vui lòng thử lại." : "The diagnostic is currently unavailable. Please try again.")}</p> : null}<section className="mt-8 rounded-3xl border border-teal-200 bg-white p-7 shadow-sm sm:p-10"><p className="text-sm font-black uppercase tracking-wider text-teal-700">{vi ? "Đánh giá đầu vào" : "Diagnostic Assessment"}</p><h1 className="mt-3 text-3xl font-black sm:text-4xl">{vi ? "Xây dựng hồ sơ TOEIC ban đầu" : "Build your initial TOEIC profile"}</h1><p className="mt-4 leading-7 text-slate-600">{vi ? "Một bài đánh giá ngắn qua Listening Part 1–4 và Reading Part 5–7. Đây không phải điểm TOEIC chính thức." : "A short assessment across Listening Parts 1–4 and Reading Parts 5–7. This is not an official TOEIC score."}</p><ul className="mt-5 grid gap-2 text-sm font-semibold text-slate-700"><li>✓ {vi ? "Khoảng 25–35 câu, giữ nguyên các nhóm câu hỏi" : "About 25–35 questions with complete question groups"}</li><li>✓ {vi ? "Có thể rời đi và tiếp tục trong 7 ngày" : "Leave and resume for 7 days"}</li><li>✓ {vi ? "Kết quả và giải thích mở sau khi hoàn thành" : "Results and explanations unlock after completion"}</li></ul><form action={startDiagnostic}><button className="mt-7 min-h-12 rounded-xl bg-teal-700 px-6 py-3 font-bold text-white" type="submit">{vi ? "Bắt đầu / Tiếp tục đánh giá" : "Start / Continue diagnostic"}</button></form></section></div></main>;
}
