import type { ExplanationLanguage, InterfaceLanguage } from "@/lib/i18n/config";
import { getTranslations } from "@/lib/i18n/runtime";
import { taxonomyLabel } from "@/lib/i18n/labels";
import type { ReviewQuestion } from "@/lib/practice/types";

export function AnswerReviewCard({ question, locale, explanationLanguage }: { question: ReviewQuestion; locale: InterfaceLanguage; explanationLanguage: ExplanationLanguage }) {
  const t = getTranslations(locale); const selected = question.options.find((option) => option.id === question.selectedOptionId); const correct = question.options.find((option) => option.id === question.correctOptionId);
  const explanation = <div className="space-y-4 text-sm leading-6 text-slate-600">{explanationLanguage !== "vi" ? <div><p className="text-xs font-black uppercase tracking-wider text-slate-500">{explanationLanguage === "both" ? "EN" : t.results.explanation}</p><p className="mt-1" lang="en">{question.explanationEn ?? t.results.noEnglish}</p></div> : null}{explanationLanguage !== "en" ? <div><p className="text-xs font-black uppercase tracking-wider text-slate-500">{explanationLanguage === "both" ? "VI" : t.results.explanation}</p><p className="mt-1" lang="vi">{question.explanationVi ?? t.results.noVietnamese}</p></div> : null}</div>;
  return <article className={`scroll-mt-24 rounded-2xl border bg-white ${question.isCorrect ? "border-emerald-200" : "border-red-200 shadow-sm"}`} id={`review-question-${question.number}`}><div className="p-4 sm:p-5"><div className="flex flex-wrap items-center justify-between gap-2"><p className={`text-sm font-black ${question.isCorrect ? "text-emerald-700" : "text-red-700"}`}><span aria-hidden="true">{question.isCorrect ? "✓" : "✕"}</span> {t.practice.question} {question.number} · {question.isCorrect ? t.results.correct : t.results.incorrect}</p><p className="text-xs font-semibold text-slate-500">{taxonomyLabel(question.skill, locale)} · {taxonomyLabel(question.subSkill, locale)}</p></div><h3 className="mt-2 font-bold leading-7" lang="en">{question.text}</h3>{question.isCorrect ? <p className="mt-3 rounded-lg bg-emerald-50 px-3 py-2 font-semibold text-emerald-900" lang="en"><span className="sr-only">{t.results.correctAnswer}: </span>{correct ? `${correct.key}. ${correct.text}` : t.common.unavailable}</p> : <dl className="mt-4 grid gap-3 sm:grid-cols-2"><div className="rounded-xl border border-red-100 bg-red-50 p-3"><dt className="text-xs font-bold text-red-800">{t.results.yourAnswer}</dt><dd className="mt-1 font-semibold" lang="en">{selected ? `${selected.key}. ${selected.text}` : t.results.unanswered}</dd></div><div className="rounded-xl border border-emerald-100 bg-emerald-50 p-3"><dt className="text-xs font-bold text-emerald-800">{t.results.correctAnswer}</dt><dd className="mt-1 font-semibold" lang="en">{correct ? `${correct.key}. ${correct.text}` : t.common.unavailable}</dd></div></dl>}</div>{question.isCorrect ? <details className="group border-t border-slate-100"><summary className="cursor-pointer list-none px-4 py-3 text-sm font-bold text-teal-800 focus-visible:outline-2 focus-visible:outline-inset focus-visible:outline-teal-700 sm:px-5"><span className="group-open:hidden">{t.results.showExplanation}</span><span className="hidden group-open:inline">{t.results.hideExplanation}</span></summary><div className="border-t border-slate-100 px-4 py-4 sm:px-5">{explanation}</div></details> : <div className="border-t border-slate-100 px-4 py-4 sm:px-5"><p className="mb-3 font-black">{t.results.explanation}</p>{explanation}</div>}</article>;
}
