"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { db } from "@/db";
import { adminAuditLogs } from "@/db/schema";
import { getCurrentUser } from "@/lib/auth/session";
import { archiveContent, cloneContent, ContentAdminError, createAdminDraft, discardDraft, publishContent, updateDraftQuestion, validateContent, type AdminDraftInput } from "@/lib/admin/content";
import { requireAdmin } from "@/lib/admin/authorization";
import { ingestMedia } from "@/lib/media/ingestion";
import { DrizzleMediaAssetRepository } from "@/lib/media/repository";
import { R2MediaStorage } from "@/lib/media/r2-storage";

async function actor(permission: "CONTENT_MANAGE" | "MEDIA_MANAGE") { const current = await getCurrentUser(); if (!current) throw new ContentAdminError("ACCESS_DENIED"); const authorized = await requireAdmin(permission); return authorized.id; }
function value(fd: FormData, key: string) { return String(fd.get(key) ?? "").trim(); }
function location(id: string, key: string, details?: string[]) { const p = new URLSearchParams({ [key]: details?.join("|") || "1" }); return `/admin/content/questions/${encodeURIComponent(id)}?${p}`; }
function archiveError(error: unknown) { if (error instanceof ContentAdminError && error.code === "CONTENT_USED_BY_ACTIVE_CHALLENGE") return "Nội dung này đang được sử dụng bởi một thử thách xếp hạng sắp diễn ra hoặc đang diễn ra nên chưa thể lưu trữ. This content is used by an upcoming or active ranked challenge and cannot be archived."; return error instanceof ContentAdminError ? error.code : "FAILED"; }
function parseDraft(fd: FormData): AdminDraftInput {
  const part = Number(value(fd, "part")); const questionCount = Math.min(20, Math.max(1, Number(value(fd, "questionCount")) || 1));
  return { part, setType: value(fd, "setType") || undefined, title: value(fd, "title"), passage: value(fd, "passage") || undefined, transcript: value(fd, "transcript") || undefined, mediaIds: fd.getAll("mediaId").map(String).filter(Boolean), questions: Array.from({ length: questionCount }, (_, i) => ({ text: value(fd, `q${i}Text`), options: ["A","B","C","D"].map((k) => value(fd, `q${i}${k}`)).filter((_, x) => !(part === 2 && x === 3)), correct: Math.max(0, ["A","B","C","D"].indexOf(value(fd, `q${i}Correct`))), explanationEn: value(fd, `q${i}ExplanationEn`), explanationVi: value(fd, `q${i}ExplanationVi`), skill: value(fd, `q${i}Skill`), subSkill: value(fd, `q${i}SubSkill`), difficulty: value(fd, `q${i}Difficulty`) })) };
}
export async function createDraftAction(fd: FormData) { let id = ""; try { id = await createAdminDraft(await actor("CONTENT_MANAGE"), parseDraft(fd)); } catch (e) { const code = e instanceof ContentAdminError ? e.code : "FAILED"; redirect(`/admin/content/new?error=${encodeURIComponent(code)}`); } redirect(`/admin/content/questions/${id}`); }
export async function validateContentAction(fd: FormData) { const id = value(fd, "id"); await actor("CONTENT_MANAGE"); try { const issues = await validateContent(id); redirect(location(id, issues.length ? "validation" : "valid", issues)); } catch { redirect(location(id, "error")); } }
export async function publishContentAction(fd: FormData) { const id = value(fd, "id"); try { await publishContent(await actor("CONTENT_MANAGE"), id, value(fd, "updatedAt")); revalidatePath("/admin/content"); } catch (e) { redirect(location(id, "error", e instanceof ContentAdminError ? [e.code, ...e.issues] : ["FAILED"])); } redirect(location(id, "published")); }
export async function archiveContentAction(fd: FormData) { const id = value(fd, "id"); try { await archiveContent(await actor("CONTENT_MANAGE"), id, value(fd, "updatedAt")); revalidatePath("/admin/content"); } catch (e) { redirect(location(id, "error", [archiveError(e)])); } redirect(location(id, "archived")); }
export async function cloneContentAction(fd: FormData) { const id = value(fd, "id"); let cloned = ""; try { cloned = await cloneContent(await actor("CONTENT_MANAGE"), id); } catch { redirect(location(id, "error")); } redirect(`/admin/content/questions/${cloned}?cloned=1`); }
export async function discardDraftAction(fd: FormData) { const id = value(fd, "id"); try { await discardDraft(await actor("CONTENT_MANAGE"), id); } catch { redirect(location(id, "error")); } redirect("/admin/content/questions?discarded=1"); }
export async function updateDraftQuestionAction(fd:FormData){const id=value(fd,"id");try{const optionCount=Number(value(fd,"optionCount"));await updateDraftQuestion(await actor("CONTENT_MANAGE"),{groupId:id,questionId:value(fd,"questionId"),updatedAt:value(fd,"updatedAt"),text:value(fd,"text"),options:Array.from({length:optionCount},(_,i)=>value(fd,`option${i}`)),correct:Number(value(fd,"correct")),explanationEn:value(fd,"explanationEn"),explanationVi:value(fd,"explanationVi"),skill:value(fd,"skill"),subSkill:value(fd,"subSkill"),difficulty:value(fd,"difficulty")});revalidatePath(`/admin/content/questions/${id}`);}catch(e){redirect(location(id,"error",[e instanceof ContentAdminError?e.code:"FAILED"]));}redirect(location(id,"updated"));}
export async function uploadMediaAction(fd: FormData) { const actorUserId = await actor("MEDIA_MANAGE"); const file = fd.get("file"); const kind = value(fd, "kind"); if (!(file instanceof File) || !["AUDIO","IMAGE"].includes(kind)) redirect("/admin/content/media?error=INVALID_UPLOAD"); try { const asset = await ingestMedia({ storage: new R2MediaStorage(), repository: new DrizzleMediaAssetRepository() }, { kind: kind as "AUDIO" | "IMAGE", accessScope: "CONTENT", mimeType: file.type, body: new Uint8Array(await file.arrayBuffer()) }); await db.insert(adminAuditLogs).values({ actorUserId, action: "MEDIA_UPLOADED", metadata: { mediaId: asset.id, kind: asset.kind, byteSize: asset.byteSize } }); revalidatePath("/admin/content/media"); } catch (e) { redirect(`/admin/content/media?error=${encodeURIComponent(e instanceof Error ? e.message : "FAILED")}`); } redirect("/admin/content/media?uploaded=1"); }
