import Link from "next/link";
import { AdminNav } from "@/components/admin/admin-nav";
import { requireAdmin } from "@/lib/admin/authorization";
import { getContentOverview } from "@/lib/admin/content";
import { recommendContentCoverage } from "@/lib/admin/content-coverage";
import { getPreferences } from "@/lib/i18n/get-translations";

export default async function Page() {
  const actor = await requireAdmin("CONTENT_READ");
  const [prefs, d] = await Promise.all([getPreferences(actor.id), getContentOverview()]);
  const vi = prefs.interfaceLanguage === "vi";
  const parts = [
    { label: "Part 1", part: 1, count: `${d.listening.p1} / 6`, area: "Listening" },
    { label: "Part 2", part: 2, count: `${d.listening.p2} / 25`, area: "Listening" },
    { label: "Part 3", part: 3, count: vi ? `${d.listening.p3Groups} nhóm · ${d.listening.p3Questions} câu` : `${d.listening.p3Groups} groups · ${d.listening.p3Questions} questions`, area: "Listening" },
    { label: "Part 4", part: 4, count: vi ? `${d.listening.p4Groups} nhóm · ${d.listening.p4Questions} câu` : `${d.listening.p4Groups} groups · ${d.listening.p4Questions} questions`, area: "Listening" },
    { label: "Part 5", part: 5, count: vi ? `${d.reading.p5} câu` : `${d.reading.p5} questions`, area: "Reading" },
    { label: "Part 6", part: 6, count: vi ? `${d.reading.p6Groups} nhóm · ${d.reading.p6Questions} câu` : `${d.reading.p6Groups} groups · ${d.reading.p6Questions} questions`, area: "Reading" },
    { label: "Part 7 · Single", part: 7, setType: "single", count: vi ? `${d.reading.p7SingleGroups} nhóm · ${d.reading.p7SingleQuestions} câu` : `${d.reading.p7SingleGroups} groups · ${d.reading.p7SingleQuestions} questions`, area: "Reading" },
    { label: "Part 7 · Multiple", part: 7, setType: "multiple", count: vi ? `${d.reading.p7MultipleGroups} nhóm · ${d.reading.p7MultipleQuestions} câu` : `${d.reading.p7MultipleGroups} groups · ${d.reading.p7MultipleQuestions} questions`, area: "Reading" },
  ];
  const statuses = [["Listening Mock", d.listeningReady], ["Reading Mock", d.readingReady], ["Full Mock", d.ready]] as const;
  const recommendations = recommendContentCoverage([
    { part: 1, label: "Part 1", groups: d.listening.p1, questions: d.listening.p1, targetGroups: 6, targetQuestions: 6 },
    { part: 2, label: "Part 2", groups: d.listening.p2, questions: d.listening.p2, targetGroups: 25, targetQuestions: 25 },
    { part: 3, label: "Part 3", groups: d.listening.p3Groups, questions: d.listening.p3Questions, targetGroups: 13, targetQuestions: 39 },
    { part: 4, label: "Part 4", groups: d.listening.p4Groups, questions: d.listening.p4Questions, targetGroups: 10, targetQuestions: 30 },
    { part: 5, label: "Part 5", groups: d.reading.p5, questions: d.reading.p5, targetGroups: 30, targetQuestions: 30 },
    { part: 6, label: "Part 6", groups: d.reading.p6Groups, questions: d.reading.p6Questions, targetGroups: 4, targetQuestions: 16 },
    { part: 7, label: "Part 7 · Single", setType: "single", groups: d.reading.p7SingleGroups, questions: d.reading.p7SingleQuestions, targetGroups: 10, targetQuestions: 29 },
    { part: 7, label: "Part 7 · Multiple", setType: "multiple", groups: d.reading.p7MultipleGroups, questions: d.reading.p7MultipleQuestions, targetGroups: 5, targetQuestions: 25 },
  ]);

  return <main className="min-h-screen bg-slate-50 px-4 py-6 text-slate-900"><div className="mx-auto max-w-6xl"><AdminNav locale={prefs.interfaceLanguage}/>
    <header className="mt-8 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-black">{vi ? "Ngân hàng câu hỏi" : "Question Bank"}</h1><p className="mt-1 text-slate-600">{vi ? "Độ phủ, trạng thái và quản lý nội dung TOEIC." : "TOEIC coverage, readiness and content management."}</p></div><div className="flex flex-wrap gap-2"><Link className="rounded-lg bg-teal-700 px-4 py-2 font-bold text-white" href="/admin/content/new">{vi ? "+ Tạo nội dung" : "+ Create content"}</Link><Link className="rounded-lg border bg-white px-4 py-2 font-bold" href="/admin/content/import">{vi ? "Nhập JSON" : "Import JSON"}</Link><Link className="rounded-lg border bg-white px-4 py-2 font-bold" href="/admin/content/questions">{vi ? "Duyệt và xuất JSON" : "Browse and export JSON"}</Link><Link className="rounded-lg border bg-white px-4 py-2 font-bold" href="/admin/content/media">Media</Link></div></header>
    <section className="mt-8"><h2 className="text-sm font-black uppercase tracking-widest text-slate-500">{vi ? "Sẵn sàng tạo đề" : "Mock readiness"}</h2><div className="mt-3 grid gap-3 sm:grid-cols-3">{statuses.map(([label, ready])=><article className={`rounded-2xl border p-5 ${ready ? "border-emerald-300 bg-emerald-50" : "border-amber-300 bg-amber-50"}`} key={label}><h3 className="font-black">{label}</h3><p className="mt-2 font-semibold">{ready ? (vi ? "Sẵn sàng" : "Ready") : (vi ? "Chưa sẵn sàng" : "Not ready")}</p>{!ready && <p className="mt-2 text-sm text-slate-700">{vi ? "Chưa đáp ứng đủ cấu trúc đề và nhóm câu hỏi." : "The required blueprint and group structure are not yet satisfied."}</p>}</article>)}</div><details className="mt-3 rounded-xl border bg-white p-4 text-sm"><summary className="cursor-pointer font-bold">{vi ? "Chi tiết kiểm tra Part 7" : "Part 7 feasibility details"}</summary><p className="mt-2">Single: {d.reading.p7SingleGroups} groups / {d.reading.p7SingleQuestions} questions · {d.reading.p7SingleFeasible ? "Ready" : "Not feasible"}</p><p>Multiple: {d.reading.p7MultipleGroups} groups / {d.reading.p7MultipleQuestions} questions · {d.reading.p7MultipleFeasible ? "Ready" : "Not feasible"}</p></details></section>
    <section className="mt-8 rounded-3xl border border-amber-200 bg-gradient-to-br from-amber-50 via-white to-teal-50 p-5 sm:p-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[.18em] text-amber-700">{vi ? "Gợi ý bổ sung" : "Coverage suggestions"}</p><h2 className="mt-2 text-2xl font-black">{vi ? "Nên thêm câu hỏi cho Part nào?" : "Which Part needs more questions?"}</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600">{vi ? "Xếp hạng theo độ thiếu so với cấu trúc một đề TOEIC đầy đủ. Chỉ tính nội dung đã xuất bản." : "Ranked by the gap against one complete TOEIC mock blueprint. Published content only."}</p></div><Link className="rounded-xl bg-slate-900 px-4 py-3 text-sm font-black text-white" href="/admin/content/new">{vi ? "+ Tạo draft" : "+ Create draft"}</Link></div>{recommendations.length ? <div className="mt-5 grid gap-3 lg:grid-cols-3">{recommendations.map((item,index)=><article className="rounded-2xl border bg-white p-5 shadow-sm" key={`${item.part}-${item.setType??"all"}`}><div className="flex items-center justify-between gap-3"><span className="rounded-full bg-amber-100 px-3 py-1 text-xs font-black text-amber-900">#{index+1} {vi ? "ưu tiên" : "priority"}</span><span className="text-sm font-black text-slate-500">{Math.min(100,Math.round(item.coverage*100))}%</span></div><h3 className="mt-4 text-xl font-black">{item.label}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{vi ? `Còn thiếu ${item.questionDeficit} câu${item.groupDeficit ? ` trong ${item.groupDeficit} nhóm` : ""} để đạt mức tối thiểu.` : `Add ${item.questionDeficit} questions${item.groupDeficit ? ` across ${item.groupDeficit} groups` : ""} to reach the minimum.`}</p><div className="mt-4 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-amber-500" style={{width:`${Math.min(100,item.coverage*100)}%`}}/></div><Link className="mt-4 inline-block text-sm font-black text-teal-800 underline" href={`/admin/content/questions?part=${item.part}${item.setType?`&setType=${item.setType}`:""}`}>{vi ? "Xem nội dung hiện có →" : "Review current content →"}</Link></article>)}</div> : <div className="mt-5 rounded-2xl border border-emerald-200 bg-emerald-50 p-5 font-bold text-emerald-900">{vi ? "Ngân hàng đã đạt mức tối thiểu cho tất cả Part. Hãy tiếp tục đa dạng hóa kỹ năng và độ khó." : "Every Part meets the minimum blueprint. Continue diversifying skills and difficulty."}</div>}</section>
    <section className="mt-8"><h2 className="text-sm font-black uppercase tracking-widest text-slate-500">{vi ? "Câu hỏi theo Part" : "Questions by Part"}</h2>{["Listening", "Reading"].map(area=><div key={area}><h3 className="mt-5 text-xl font-black">{area}</h3><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{parts.filter(p=>p.area===area).map(p=><Link href={`/admin/content/questions?part=${p.part}${p.setType ? `&setType=${p.setType}` : ""}`} className="rounded-2xl border bg-white p-5 transition hover:border-teal-500 hover:shadow-sm focus-visible:outline-2 focus-visible:outline-teal-700" key={p.label}><span className="font-bold text-teal-800">{p.label} →</span><span className="mt-2 block text-lg font-black">{p.count}</span></Link>)}</div></div>)}</section>
    <section className="mt-8 rounded-2xl border bg-white p-5"><h2 className="font-black">{vi ? "Vòng đời nội dung" : "Content lifecycle"}</h2><div className="mt-3 flex flex-wrap gap-3">{[["draft",vi?"Bản nháp":"Draft"],["published",vi?"Đã xuất bản":"Published"],["archived",vi?"Đã lưu trữ":"Archived"]].map(([key,label])=><Link className="rounded-lg border px-4 py-3 font-semibold hover:border-teal-500" href={`/admin/content/questions?lifecycle=${key}`} key={key}>{label}: {d.lifecycle[key] ?? 0} →</Link>)}</div></section>
  </div></main>;
}
