import "server-only";
import { and, desc, eq, inArray, ne } from "drizzle-orm";
import { db } from "@/db";
import { adminAuditLogs, contentPosts, contentPostTags, contentTags, mediaAssets } from "@/db/schema";
import { POST_CATEGORIES, slugify, validatePost, type PostCategory, type PostInput } from "./core";
import { createMediaStorage } from "@/lib/media/storage";
import { EDITORIAL_POSTS, getEditorialPost } from "./editorial";

export class BlogAdminError extends Error { constructor(public code: string) { super(code); } }
export async function listAdminPosts() { return db.select().from(contentPosts).orderBy(desc(contentPosts.updatedAt)); }
export async function listAdminPostTags(){return db.select({postId:contentPostTags.postId,name:contentTags.name}).from(contentPostTags).innerJoin(contentTags,eq(contentPostTags.tagId,contentTags.id));}
export async function listPublishedPosts(limit = 50) {
  let databasePosts: typeof contentPosts.$inferSelect[] = [];
  try {
    databasePosts = await db.select().from(contentPosts).where(eq(contentPosts.status, "PUBLISHED")).orderBy(desc(contentPosts.publishedAt)).limit(limit);
  } catch {
    console.warn("Could not load CMS posts; serving the bundled editorial library.");
  }
  const databaseSlugs = new Set(databasePosts.map(post => post.slug));
  return [...databasePosts, ...EDITORIAL_POSTS.filter(post => !databaseSlugs.has(post.slug))]
    .sort((a, b) => (b.publishedAt?.getTime() ?? 0) - (a.publishedAt?.getTime() ?? 0)).slice(0, limit);
}
export async function getPostById(id: string) { const post=(await db.select().from(contentPosts).where(eq(contentPosts.id,id)).limit(1))[0]; return post ? { ...post, tags: await tagsFor(post.id) } : null; }
export async function getPublishedPost(slug: string) { const editorial=getEditorialPost(slug);if(editorial)return editorial;try{const post=(await db.select().from(contentPosts).where(and(eq(contentPosts.slug,slug),eq(contentPosts.status,"PUBLISHED"))).limit(1))[0];return post?{...post,tags:await tagsFor(post.id)}:null;}catch{console.warn("Could not load the requested CMS post.");return null;} }
async function tagsFor(postId:string){return db.select({name:contentTags.name,slug:contentTags.slug}).from(contentPostTags).innerJoin(contentTags,eq(contentPostTags.tagId,contentTags.id)).where(eq(contentPostTags.postId,postId));}
export async function listReadyCoverImages(){return db.select({id:mediaAssets.id,storageKey:mediaAssets.storageKey,imageWidth:mediaAssets.imageWidth,imageHeight:mediaAssets.imageHeight}).from(mediaAssets).where(and(eq(mediaAssets.kind,"IMAGE"),eq(mediaAssets.status,"READY"),eq(mediaAssets.accessScope,"CONTENT"))).orderBy(desc(mediaAssets.createdAt)).limit(100);}
export async function listPostSuggestions(id?:string){return db.select({id:contentPosts.id,title:contentPosts.title,slug:contentPosts.slug,category:contentPosts.category,seoTitle:contentPosts.seoTitle,seoDescription:contentPosts.seoDescription}).from(contentPosts).where(id?and(eq(contentPosts.status,"PUBLISHED"),ne(contentPosts.id,id)):eq(contentPosts.status,"PUBLISHED")).orderBy(desc(contentPosts.publishedAt)).limit(100);}

async function replaceTags(tx: Parameters<Parameters<typeof db.transaction>[0]>[0], postId:string, names:string[]){
  await tx.delete(contentPostTags).where(eq(contentPostTags.postId,postId));
  const cleaned=[...new Set(names.map(x=>x.trim()).filter(Boolean))].slice(0,12);
  for(const name of cleaned){const slug=slugify(name);if(!slug)continue;await tx.insert(contentTags).values({name,slug}).onConflictDoUpdate({target:contentTags.slug,set:{name}});const tag=(await tx.select({id:contentTags.id}).from(contentTags).where(eq(contentTags.slug,slug)).limit(1))[0];await tx.insert(contentPostTags).values({postId,tagId:tag.id});}
}
function normalized(input:PostInput):PostInput{return {...input,title:input.title.trim(),slug:input.slug.trim(),excerpt:input.excerpt.trim(),content:input.content.trim(),seoTitle:input.seoTitle?.trim()||undefined,seoDescription:input.seoDescription?.trim()||undefined,canonicalPath:input.canonicalPath?.trim()||undefined,coverMediaId:input.coverMediaId||undefined,coverAlt:input.coverAlt?.trim()||undefined,socialTitle:input.socialTitle?.trim()||undefined,socialDescription:input.socialDescription?.trim()||undefined,authorName:input.authorName?.trim()||undefined,targetTopic:input.targetTopic?.trim()||undefined,searchIntent:input.searchIntent?.trim()||undefined,tags:input.tags};}
export async function savePost(actorId:string,input:PostInput,id?:string){const data=normalized(input);const errors=validatePost(data);if(errors.length)throw new BlogAdminError(errors[0]);if(!POST_CATEGORIES.includes(data.category))throw new BlogAdminError("CATEGORY_INVALID");const values={title:data.title,slug:data.slug,excerpt:data.excerpt,content:data.content,category:data.category,seoTitle:data.seoTitle??null,seoDescription:data.seoDescription??null,canonicalPath:data.canonicalPath??null,coverMediaId:data.coverMediaId??null,coverAlt:data.coverAlt??null,socialTitle:data.socialTitle??null,socialDescription:data.socialDescription??null,authorName:data.authorName??null,targetTopic:data.targetTopic??null,searchIntent:data.searchIntent??null,noindex:Boolean(data.noindex)};try{return await db.transaction(async tx=>{let postId=id;if(id){const current=(await tx.select().from(contentPosts).where(eq(contentPosts.id,id)).limit(1))[0];if(!current)throw new BlogAdminError("NOT_FOUND");if(current.status==="PUBLISHED"&&current.slug!==data.slug)throw new BlogAdminError("PUBLISHED_SLUG_LOCKED");await tx.update(contentPosts).set({...values,updatedBy:actorId,updatedAt:new Date()}).where(eq(contentPosts.id,id));}else{postId=(await tx.insert(contentPosts).values({...values,createdBy:actorId,updatedBy:actorId}).returning({id:contentPosts.id}))[0].id;}await replaceTags(tx,postId!,data.tags);await tx.insert(adminAuditLogs).values({actorUserId:actorId,action:id?"SEO_POST_UPDATED":"SEO_POST_CREATED",metadata:{postId,slug:data.slug}});return postId!;});}catch(e){const cause=(e as {cause?:{code?:string}}).cause;if((e as {code?:string}).code==="23505"||cause?.code==="23505")throw new BlogAdminError("SLUG_TAKEN");throw e;}}
export async function setPostPublished(actorId:string,id:string,publish:boolean){await db.transaction(async tx=>{const post=(await tx.select().from(contentPosts).where(eq(contentPosts.id,id)).limit(1))[0];if(!post)throw new BlogAdminError("NOT_FOUND");if(publish){const errors=validatePost({title:post.title,slug:post.slug,excerpt:post.excerpt,content:post.content,category:post.category as PostCategory,seoTitle:post.seoTitle??undefined,seoDescription:post.seoDescription??undefined,canonicalPath:post.canonicalPath??undefined,coverMediaId:post.coverMediaId??undefined,tags:[]},true);if(errors.length)throw new BlogAdminError(errors[0]);}await tx.update(contentPosts).set({status:publish?"PUBLISHED":"UNPUBLISHED",publishedAt:publish?(post.publishedAt??new Date()):post.publishedAt,updatedBy:actorId,updatedAt:new Date()}).where(eq(contentPosts.id,id));await tx.insert(adminAuditLogs).values({actorUserId:actorId,action:publish?"SEO_POST_PUBLISHED":"SEO_POST_UNPUBLISHED",metadata:{postId:id,slug:post.slug}});});}
export async function deleteDraft(actorId:string,id:string){await db.transaction(async tx=>{const deleted=await tx.delete(contentPosts).where(and(eq(contentPosts.id,id),inArray(contentPosts.status,["DRAFT","UNPUBLISHED"]))).returning({id:contentPosts.id,slug:contentPosts.slug});if(!deleted.length)throw new BlogAdminError("PUBLISHED_DELETE_FORBIDDEN");await tx.insert(adminAuditLogs).values({actorUserId:actorId,action:"SEO_POST_DELETED",metadata:{postId:id,slug:deleted[0].slug}});});}
export async function publishedSitemapRows(){let databaseRows:{slug:string;updatedAt:Date}[]=[];try{databaseRows=await db.select({slug:contentPosts.slug,updatedAt:contentPosts.updatedAt}).from(contentPosts).where(and(eq(contentPosts.status,"PUBLISHED"),eq(contentPosts.noindex,false)));}catch{console.warn("Could not load CMS sitemap rows; using bundled editorial rows.");}const slugs=new Set(databaseRows.map(row=>row.slug));return [...databaseRows,...EDITORIAL_POSTS.filter(post=>!slugs.has(post.slug)).map(post=>({slug:post.slug,updatedAt:post.updatedAt}))];}
export function readingMinutes(content:string){return Math.max(1,Math.ceil(content.trim().split(/\s+/).length/220));}
export async function coverUrl(mediaId:string|null){if(!mediaId)return null;const asset=(await db.select({key:mediaAssets.storageKey}).from(mediaAssets).where(and(eq(mediaAssets.id,mediaId),eq(mediaAssets.kind,"IMAGE"),eq(mediaAssets.status,"READY"),eq(mediaAssets.accessScope,"CONTENT"))).limit(1))[0];return asset?createMediaStorage().createReadUrl(asset.key,3600):null;}
