"use server";
import { and, eq } from "drizzle-orm";
import { redirect } from "next/navigation";
import { db } from "@/db";
import { demoTestAnswers, practiceSessionQuestions, practiceSessions, questionOptions } from "@/db/schema";
import { getCurrentUser } from "@/lib/auth/session";
import { finalizeDemoTest } from "@/lib/demo-test/queries";
import { createReadingDemoTest } from "@/lib/demo-test/selector";
export async function startDemoTest() { const user = await getCurrentUser(); if (!user) redirect("/sign-in"); try { redirect(`/demo-test/${await createReadingDemoTest(user.id)}`); } catch (error) { if (typeof error === "object" && error && "digest" in error) throw error; console.error("Demo test start failed", error); redirect("/demo-test?error=content_unavailable"); } }
export async function saveDemoAnswer(sessionId: string, questionId: string, optionId: string, responseTimeMs?: number) { const user = await getCurrentUser(); if (!user) return { ok: false as const, error: "auth" as const }; try { return await db.transaction(async (tx) => { const [session] = await tx.select().from(practiceSessions).where(and(eq(practiceSessions.id, sessionId), eq(practiceSessions.userId, user.id), eq(practiceSessions.practiceType, "demo_test"))).for("update").limit(1); if (!session?.expiresAt || session.status !== "in_progress" || session.expiresAt <= new Date()) return { ok: false as const, error: "expired" as const }; const [[assignment], [option]] = await Promise.all([tx.select().from(practiceSessionQuestions).where(and(eq(practiceSessionQuestions.sessionId, sessionId), eq(practiceSessionQuestions.questionId, questionId))).limit(1), tx.select().from(questionOptions).where(and(eq(questionOptions.id, optionId), eq(questionOptions.questionId, questionId))).limit(1)]); if (!assignment || !option) return { ok: false as const, error: "invalid" as const }; await tx.insert(demoTestAnswers).values({ sessionId, userId: user.id, questionId, selectedOptionId: optionId, responseTimeMs: Number.isInteger(responseTimeMs) ? Math.min(Math.max(responseTimeMs!, 0), 86_400_000) : null }).onConflictDoUpdate({ target: [demoTestAnswers.sessionId, demoTestAnswers.questionId], set: { selectedOptionId: optionId, updatedAt: new Date() } }); return { ok: true as const }; }); } catch (error) { console.error("Demo answer save failed", error); return { ok: false as const, error: "save" as const }; } }
export async function submitDemoTest(sessionId: string, reason: "manual" | "time_expired") { const user = await getCurrentUser(); if (!user) return { ok: false as const, error: "auth" as const }; try { await finalizeDemoTest(sessionId, user.id, reason); return { ok: true as const, sessionId }; } catch { return { ok: false as const, error: "submit" as const }; } }
