import { describe, expect, it } from "vitest";
import { dashboardAction, dueVocabularyCards, partPracticeCommand, resultAccuracy, selectAnswer, shouldClearSession, shouldRetryNetwork, workoutBlocked } from "./model";
import { audioCacheIsFresh, queuedReviewResolution, safeNotificationPath } from "./retention-policy";

const dashboard = { progress: { answered: 0, correct: 0, accuracy: null }, completedQuestionsToday: 0, completedLearningSessions: 0, unresolvedMistakes: 0, recommendation: null, resumablePractice: null, goal: null, dailyGoal: { completedQuestions: 0, targetQuestions: 10, remainingQuestions: 10, percent: 0, complete: false }, streak: { currentDays: 0, bestDays: 0 }, lifecycle: "NEW" as const };
const entitlements = { effectivePlan: "FREE" as const, premiumExpiresAt: null, membershipStatus: "FREE" as const, isTrial: false, capabilities: {}, usage: { TODAYS_WORKOUT: { type: "LIMITED" as const, used: 1, limit: 1, remaining: 0, resetAt: "2026-10-03T17:00:00.000Z" }, MANUAL_PRACTICE: { type: "UNLIMITED" as const, used: 0, resetAt: null }, MASTERY_REVIEW: { type: "UNLIMITED" as const, used: 0, resetAt: null }, FULL_MOCK: { type: "UNLIMITED" as const, used: 0, resetAt: null } } };

describe("mobile view model", () => {
  it("maps dashboard next actions without recomputing recommendations", () => { expect(dashboardAction(dashboard)).toEqual({ kind: "START" }); expect(dashboardAction({ ...dashboard, resumablePractice: { id: "session", part: 5, questionCount: 10 } })).toEqual({ kind: "RESUME", sessionId: "session" }); });
  it("blocks a consumed quota but still permits resuming", () => { expect(workoutBlocked(entitlements, dashboard)).toBe(true); expect(workoutBlocked(entitlements, { ...dashboard, resumablePractice: { id: "session", part: 5, questionCount: 10 } })).toBe(false); });
  it("updates only the selected answer", () => { const session = { id: "s", status: "in_progress" as const, source: "custom", skillArea: "READING" as const, part: 5, questionCount: 1, groups: [], questions: [{ id: "q", number: 1, part: 5, text: "Q", skill: "grammar", subSkill: "verbs", passageSetId: null, selectedOptionId: null, options: [{ id: "a", key: "A", text: "A" }, { id: "b", key: "B", text: "B" }] }] }; expect(selectAnswer(session, "q", "b").questions[0].selectedOptionId).toBe("b"); });
  it("maps result, 401 and retry states", () => { expect(resultAccuracy({ id: "s", status: "submitted", scoreCorrect: 7, scoreTotal: 10, submittedAt: "2026-10-02T00:00:00.000Z", results: [] })).toBe(70); expect(shouldClearSession("UNAUTHENTICATED")).toBe(true); expect(shouldRetryNetwork("TIMEOUT")).toBe(true); expect(shouldRetryNetwork("FORBIDDEN")).toBe(false); });
  it("builds valid native Part 1–7 practice commands", () => { expect(partPracticeCommand(1)).toEqual({ kind: "CUSTOM", skillArea: "LISTENING", part: 1, questionCount: 5 }); expect(partPracticeCommand(3)).toMatchObject({ skillArea: "LISTENING", questionCount: 3 }); expect(partPracticeCommand(7)).toEqual({ kind: "CUSTOM", skillArea: "READING", part: 7, questionCount: 10 }); });
  it("selects only vocabulary cards due at the captured server-view time", () => { const cards = [{ id: "a", dueAt: "2026-10-04T00:00:00.000Z" }, { id: "b", dueAt: "2026-10-05T00:00:00.000Z" }] as never; expect(dueVocabularyCards(cards, Date.parse("2026-10-04T12:00:00.000Z")).map((item) => item.id)).toEqual(["a"]); });
  it("allows only known notification deep-link targets", () => { expect(safeNotificationPath("workout")).toBe("/workout"); expect(safeNotificationPath("result:00000000-0000-4000-8000-000000000001")).toBe("/result/00000000-0000-4000-8000-000000000001"); expect(safeNotificationPath("remediation:00000000-0000-4000-8000-000000000001")).toBe("/result/00000000-0000-4000-8000-000000000001"); expect(safeNotificationPath("https://evil.example")).toBeNull(); expect(safeNotificationPath("result:not-a-uuid")).toBeNull(); });
  it("expires cached audio after 24 hours", () => { const now = Date.parse("2026-10-04T12:00:00.000Z"); expect(audioCacheIsFresh(now - 1_000, now)).toBe(true); expect(audioCacheIsFresh(now - 24 * 60 * 60_000 - 1, now)).toBe(false); expect(audioCacheIsFresh(now + 1, now)).toBe(false); });
  it("retries offline reviews but drops authoritative conflicts", () => { expect(queuedReviewResolution("NETWORK_ERROR")).toBe("RETRY_LATER"); expect(queuedReviewResolution("TIMEOUT")).toBe("RETRY_LATER"); expect(queuedReviewResolution("CONFLICT")).toBe("DROP"); expect(queuedReviewResolution("INTERNAL_ERROR")).toBe("KEEP"); });
});
