import Link from "next/link";
import { AdminNav } from "@/components/admin/admin-nav";
import { requireAdmin } from "@/lib/admin/authorization";
import { getPreferences } from "@/lib/i18n/get-translations";
import { listAdminPayments } from "@/lib/payments/service";
import { money, paymentDate, productLabel, statusLabel, statusTone } from "@/lib/payments/admin-display";

type Query = { q?: string; status?: string; product?: string; days?: string; page?: string };
export default async function AdminPaymentsPage({ searchParams }: { searchParams: Promise<Query> }) {
  const actor = await requireAdmin("ADMIN_DASHBOARD_READ");
  const prefs = await getPreferences(actor.id), vi = prefs.interfaceLanguage === "vi", params = await searchParams;
  let data: Awaited<ReturnType<typeof listAdminPayments>> | null = null;
  try { data = await listAdminPayments({ ...params, page: Number.parseInt(params.page ?? "1") || 1 }); } catch { /* Safe retry state. */ }
  const qs = (page: number) => { const next = new URLSearchParams(); for (const key of ["q", "status", "product", "days"] as const) if (params[key]) next.set(key, params[key]); next.set("page", String(page)); return `?${next}`; };
  const count = (status: string) => Number(data?.summary[status] ?? 0);
  const hasOrders = data ? Object.values(data.summary).some(Boolean) : false;
  return <main className="min-h-screen bg-slate-50 px-4 py-6 text-slate-900 sm:px-6"><div className="mx-auto max-w-7xl"><AdminNav locale={prefs.interfaceLanguage}/><header className="mt-8"><h1 className="text-3xl font-black">{vi ? "Thanh toán" : "Payments"}</h1><p className="mt-2 text-slate-600">{vi ? "Theo dõi đơn hàng và trạng thái thanh toán Premium." : "Track Premium orders and payment status."}</p></header>
    {data && <section aria-label={vi ? "Tổng quan đơn hàng" : "Order overview"} className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[[vi?"Tổng đơn":"All orders",Object.values(data.summary).reduce((a,b)=>a+Number(b),0)],[vi?"Đã thanh toán":"Paid",count("PAID")],[vi?"Đang chờ":"Pending",count("PENDING")],[vi?"Cần xem xét":"Needs review",count("FAILED")+count("EXPIRED")+count("CANCELLED")]].map(([label,value])=><div key={label} className="rounded-2xl border bg-white p-4"><p className="text-sm text-slate-600">{label}</p><p className="mt-1 text-2xl font-black">{value}</p></div>)}</section>}
    <form method="get" className="mt-6 grid gap-3 rounded-2xl border bg-white p-4 sm:grid-cols-2 lg:grid-cols-[2fr_1fr_1fr_1fr_auto]"><label className="text-sm font-semibold">{vi?"Tìm kiếm":"Search"}<input name="q" defaultValue={params.q} maxLength={100} placeholder={vi?"Email hoặc mã đơn hàng":"Email or order code"} className="mt-1 min-h-11 w-full rounded-xl border px-3 font-normal"/></label><label className="text-sm font-semibold">{vi?"Trạng thái":"Status"}<select name="status" defaultValue={params.status??""} className="mt-1 min-h-11 w-full rounded-xl border px-3 font-normal"><option value="">{vi?"Tất cả":"All"}</option>{["PENDING","PAID","EXPIRED","CANCELLED","FAILED"].map(s=><option key={s} value={s}>{statusLabel(s,vi)}</option>)}</select></label><label className="text-sm font-semibold">{vi?"Gói":"Plan"}<select name="product" defaultValue={params.product??""} className="mt-1 min-h-11 w-full rounded-xl border px-3 font-normal"><option value="">{vi?"Tất cả":"All"}</option>{[30,90,365].map(days=><option key={days} value={`PREMIUM_${days}_DAYS`}>Premium · {days} {vi?"ngày":"days"}</option>)}</select></label><label className="text-sm font-semibold">{vi?"Thời gian":"Period"}<select name="days" defaultValue={params.days??""} className="mt-1 min-h-11 w-full rounded-xl border px-3 font-normal"><option value="">{vi?"Mọi thời gian":"All time"}</option>{[7,30,90].map(days=><option key={days} value={days}>{days} {vi?"ngày gần đây":"recent days"}</option>)}</select></label><button className="min-h-11 self-end rounded-xl bg-slate-900 px-5 font-bold text-white">{vi?"Áp dụng":"Apply"}</button></form>
    {!data ? <section role="alert" className="mt-6 rounded-2xl border bg-white p-8 text-center"><h2 className="font-bold">{vi?"Không thể tải dữ liệu thanh toán.":"Could not load payments."}</h2><Link className="mt-3 inline-block font-bold text-teal-700 underline" href="/admin/payments">{vi?"Thử lại":"Try again"}</Link></section> : data.rows.length === 0 ? <section className="mt-6 rounded-2xl border border-dashed bg-white p-10 text-center"><h2 className="text-xl font-bold">{hasOrders ? vi?"Không tìm thấy giao dịch phù hợp":"No matching payments" : vi?"Chưa có giao dịch":"No transactions yet"}</h2><p className="mt-2 text-slate-600">{hasOrders ? vi?"Thử điều chỉnh tìm kiếm hoặc bộ lọc.":"Try changing the search or filters." : vi?"Các đơn thanh toán Premium sẽ xuất hiện tại đây khi người dùng bắt đầu thanh toán.":"Premium payment orders will appear here when learners start checkout."}</p>{hasOrders&&<Link className="mt-4 inline-block font-bold text-teal-700 underline" href="/admin/payments">{vi?"Xóa bộ lọc":"Clear filters"}</Link>}</section> : <><div className="mt-6 overflow-x-auto rounded-2xl border bg-white"><table className="w-full min-w-[650px] text-left text-sm"><thead className="bg-slate-100"><tr>{[vi?"Đơn hàng":"Order",vi?"Người dùng":"Learner",vi?"Gói":"Plan",vi?"Số tiền":"Amount",vi?"Trạng thái":"Status",vi?"Ngày tạo":"Created",vi?"Chi tiết":"Details"].map(x=><th scope="col" className="p-4" key={x}>{x}</th>)}</tr></thead><tbody>{data.rows.map(row=><tr className="border-t" key={row.id}><td className="p-4 font-semibold"><Link className="text-teal-800 underline-offset-2 hover:underline" href={`/admin/payments/${row.id}`}>TG-{row.orderCode}</Link></td><td className="p-4 break-all">{row.email}</td><td className="p-4">{productLabel(row.productKey,vi)}</td><td className="p-4 whitespace-nowrap">{money(row.amount,row.currency,prefs.interfaceLanguage)}</td><td className="p-4"><span className={`rounded-full px-3 py-1 text-xs font-bold ${statusTone(row.status)}`}>{statusLabel(row.status,vi)}</span></td><td className="p-4 whitespace-nowrap">{paymentDate(row.createdAt,prefs.interfaceLanguage)}</td><td className="p-4"><Link className="font-bold text-teal-800 underline" href={`/admin/payments/${row.id}`}>{vi?"Xem":"View"}</Link></td></tr>)}</tbody></table></div><nav aria-label={vi?"Trang thanh toán":"Payment pages"} className="mt-5 flex items-center justify-between"><Link aria-disabled={data.page<=1} className={`rounded-lg border px-4 py-2 ${data.page<=1?"pointer-events-none opacity-40":""}`} href={qs(data.page-1)}>{vi?"Trước":"Previous"}</Link><span>{data.page} / {Math.max(1,Math.ceil(data.total/data.pageSize))}</span><Link aria-disabled={data.page*data.pageSize>=data.total} className={`rounded-lg border px-4 py-2 ${data.page*data.pageSize>=data.total?"pointer-events-none opacity-40":""}`} href={qs(data.page+1)}>{vi?"Sau":"Next"}</Link></nav></>}
  </div></main>;
}
