import Link from "next/link";
import { LearnerNav } from "@/components/competitive-learner-nav";
import { getCurrentUser } from "@/lib/auth/session";
import { getPreferences } from "@/lib/i18n/get-translations";
import { getGamificationSummary, getWeeklyLeaderboard } from "@/lib/gamification/queries";
import { GAMIFICATION_CATALOG } from "@/lib/gamification/catalog";
import { getChallengeHistory, listDiscoverableChallenges } from "@/lib/challenges/queries";
import { challengePhase } from "@/lib/challenges/policy";
import { getFullMockReadiness } from "@/lib/full-mock/service";

type Row = Awaited<ReturnType<typeof getWeeklyLeaderboard>>["top"][number];

function Player({ row, own, vi }: { row: Row; own: boolean; vi: boolean }) {
  const name = row.visibility === "PUBLIC" ? row.name : vi ? "Người học ẩn danh" : "Anonymous learner";
  const initials = row.visibility === "PUBLIC" ? (name ?? "?").split(/\s+/).slice(-2).map(part => part[0]).join("").toUpperCase() : "?";
  return <article className={`flex min-w-0 items-center gap-3 rounded-2xl border p-3 sm:p-4 ${own ? "border-teal-400 bg-teal-50 ring-1 ring-teal-200" : row.rank === 1 ? "border-amber-300 bg-amber-50" : row.rank === 2 ? "border-slate-300 bg-slate-100" : row.rank === 3 ? "border-orange-200 bg-orange-50" : "border-slate-200 bg-white"}`}>
    <strong className="w-10 shrink-0 text-lg tabular-nums">#{row.rank}</strong><span aria-hidden="true" className="flex size-10 shrink-0 items-center justify-center rounded-full bg-slate-900 text-xs font-black text-white">{initials}</span>
    <div className="min-w-0 flex-1"><div className="truncate font-bold">{row.visibility === "PUBLIC" && row.publicProfileId ? <Link className="hover:underline" href={`/learners/${row.publicProfileId}`}>{name}</Link> : name}</div>{own && <span className="text-xs font-black uppercase text-teal-800">{vi ? "Bạn" : "You"}</span>}{row.rank <= 3 && <span className="block text-xs text-slate-500">{row.rank === 1 ? (vi ? "Dẫn đầu" : "Leader") : `Top ${row.rank}`}</span>}</div><strong className="shrink-0 tabular-nums">{row.score} <span className="text-xs text-slate-500">RP</span></strong>
  </article>;
}

export default async function RankingPage({ searchParams }: { searchParams: Promise<{ week?: string; tab?: string }> }) {
  const [user, query] = await Promise.all([getCurrentUser(), searchParams]);
  const preferences = await getPreferences(user?.id);
  const vi = preferences.interfaceLanguage === "vi";
  const previous = query.week === "previous";
  const [board, summary, challenges, history, fullMock] = await Promise.all([getWeeklyLeaderboard(previous, user?.id), user ? getGamificationSummary(user.id) : null, listDiscoverableChallenges(), user ? getChallengeHistory(user.id) : [], getFullMockReadiness()]);
  const tabs = [["weekly", vi ? "Học tập tuần" : "Weekly learning"], ["READING_100", "Reading"], ["LISTENING_100", "Listening"], ...(fullMock.ready ? [["FULL_200", "Full Mock"]] as const : [])] as const;
  const tab = tabs.some(([key]) => key === query.tab) ? query.tab! : "weekly";
  const selected = challenges.filter(challenge => challenge.type === tab).sort((a, b) => {
    const order = (challenge: typeof a) => challengePhase(challenge) === "LIVE" ? 0 : challengePhase(challenge) === "UPCOMING" ? 1 : 2;
    return order(a) - order(b);
  })[0];
  const me = board.me;
  const target = me?.target;
  const nearby = board.around.filter(row => !board.top.some(topRow => topRow.userId === row.userId));
  const hours = Math.max(0, Math.ceil((board.window.end.getTime() - board.generatedAt.getTime()) / 3_600_000));
  const progress = target ? Math.max(0, Math.min(100, Math.round(me!.score / (target.score + 1) * 100))) : 100;
  return <main className="min-h-screen overflow-x-hidden bg-slate-50 px-4 py-6 pb-24 text-slate-900 sm:px-6 lg:pb-8"><div className="mx-auto max-w-6xl">
    <LearnerNav locale={preferences.interfaceLanguage} />
    <header className="mt-7 flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[.2em] text-teal-700">TOEICGym</p><h1 className="mt-2 text-3xl font-black sm:text-4xl">{vi ? "Bảng xếp hạng tuần" : "Weekly leaderboard"}</h1></div><p className="rounded-full bg-slate-900 px-4 py-2 text-sm font-bold text-white">{previous ? (vi ? "Kết quả tuần trước" : "Last week's results") : vi ? `Còn ${Math.floor(hours / 24)} ngày ${hours % 24} giờ` : `${Math.floor(hours / 24)}d ${hours % 24}h remaining`}</p></header>
    <nav aria-label={vi ? "Hạng mục xếp hạng" : "Ranking categories"} className="-mx-4 mt-6 flex max-w-full gap-2 overflow-x-auto px-4 pb-2 sm:mx-0 sm:px-0">{tabs.map(([key,label]) => <Link key={key} href={key === "weekly" ? "/ranking" : `/ranking?tab=${key}`} aria-current={tab === key ? "page" : undefined} className={`min-h-11 shrink-0 rounded-xl border px-4 py-3 text-sm font-bold focus-visible:outline-2 focus-visible:outline-offset-2 ${tab === key ? "border-teal-700 bg-teal-700 text-white" : "border-slate-200 bg-white text-slate-800 hover:border-teal-400"}`}>{label}</Link>)}</nav>
    {tab === "weekly" ? <><nav aria-label={vi ? "Chọn tuần" : "Select week"} className="mt-3 inline-flex rounded-xl bg-slate-200 p-1 text-sm font-bold"><Link href="/ranking" aria-current={!previous ? "page" : undefined} className={`min-h-11 rounded-lg px-4 py-3 ${!previous ? "bg-white shadow-sm" : ""}`}>{vi ? "Tuần này" : "This week"}</Link><Link href="/ranking?week=previous" aria-current={previous ? "page" : undefined} className={`min-h-11 rounded-lg px-4 py-3 ${previous ? "bg-white shadow-sm" : ""}`}>{vi ? "Tuần trước" : "Previous week"}</Link></nav>
      <div className="mt-5 grid gap-5 lg:grid-cols-[minmax(0,1fr)_20rem] lg:items-start"><div className="min-w-0 lg:order-2"><section aria-label={vi ? "Hạng của bạn" : "Your rank"} className="rounded-3xl bg-slate-900 p-5 text-white shadow-lg sm:p-6"><p className="text-sm font-black uppercase tracking-widest text-teal-300">{vi ? "Hạng của bạn" : "Your rank"}</p>{me ? <><div className="mt-3 flex items-end justify-between gap-3"><strong className="text-6xl font-black tabular-nums">#{me.rank}</strong><strong className="text-2xl tabular-nums text-teal-300">{me.score} RP</strong></div><p className="mt-3 font-semibold">{me.rank === 1 ? (me.tied ? (vi ? "Bạn đang đồng hạng #1" : "You're tied for #1") : (vi ? "Bạn đang dẫn đầu!" : "You're in the lead!")) : target ? (vi ? `Còn ${target.points} RP để lên #${target.rank}` : `${target.points} RP to reach #${target.rank}`) : (vi ? "Tiếp tục học để giữ vị trí" : "Keep learning to hold your place")}</p>{target && <><div role="progressbar" aria-label={vi ? "Tiến độ tới hạng kế tiếp" : "Progress to next rank"} aria-valuenow={progress} aria-valuemin={0} aria-valuemax={100} className="mt-3 h-2 overflow-hidden rounded-full bg-slate-700"><div className="h-full rounded-full bg-teal-400" style={{width:`${progress}%`}} /></div><p className="mt-2 text-xs text-slate-300">{vi ? `Mốc cần vượt: ${target.score} RP` : `Score to beat: ${target.score} RP`}</p></>}</> : <><p className="mt-4 text-xl font-bold">{vi ? "Bạn chưa có hạng trong tuần này" : "You have no rank this week yet"}</p><p className="mt-2 text-sm text-slate-300">{vi ? "Hoàn thành một bài học để bắt đầu tích điểm." : "Complete a learning activity to start earning points."}</p></>}{!previous && <Link className="mt-5 flex min-h-12 items-center justify-center rounded-xl bg-teal-400 px-4 py-3 text-center font-black text-slate-950 hover:bg-teal-300 focus-visible:outline-2 focus-visible:outline-offset-2" href="/practice">{vi ? "Luyện ngay để tăng hạng →" : "Practice to climb →"}</Link>}</section>
        {summary && <section className="mt-4 grid grid-cols-2 gap-2"><article className="rounded-2xl border bg-white p-4"><p className="text-sm text-slate-600">{vi ? "Tổng XP" : "Total XP"}</p><strong className="text-xl tabular-nums">{summary.xp}</strong><p className="mt-1 text-xs text-slate-500">{vi ? "Tích lũy lâu dài" : "Lifetime progress"}</p></article><article className="rounded-2xl border bg-white p-4"><p className="text-sm text-slate-600">{vi ? "Chuỗi học" : "Study streak"}</p><strong className="text-xl tabular-nums">{summary.currentStreak} {vi ? "ngày" : "days"}</strong><p className="mt-1 text-xs text-slate-500">{vi ? `Kỷ lục: ${summary.bestStreak} ngày` : `Best: ${summary.bestStreak} days`}</p></article></section>}
        <details className="mt-4 rounded-2xl border bg-white p-4"><summary className="cursor-pointer font-bold text-teal-800">{vi ? "Cách kiếm RP" : "How to earn RP"}</summary><p className="mt-3 text-sm leading-6 text-slate-600">{vi ? `Câu hỏi mới: ${GAMIFICATION_CATALOG.questionRankPoints} RP/câu (tối đa ${GAMIFICATION_CATALOG.questionDailyCap} câu/ngày). Ngày học: ${GAMIFICATION_CATALOG.studyDayRankPoints} RP; chuỗi học thêm tối đa ${GAMIFICATION_CATALOG.streakRankPointsCap} RP. Hoàn thành bài tập hằng ngày hoặc ôn câu sai có thể nhận thêm ${GAMIFICATION_CATALOG.workoutBonus.rankPoints} RP. Tổng RP tối đa ${GAMIFICATION_CATALOG.dailyRankPointsCap}/ngày. Một số hoạt động chỉ cho XP.` : `New questions: ${GAMIFICATION_CATALOG.questionRankPoints} RP each (up to ${GAMIFICATION_CATALOG.questionDailyCap} per day). Study day: ${GAMIFICATION_CATALOG.studyDayRankPoints} RP; streak bonus up to ${GAMIFICATION_CATALOG.streakRankPointsCap} RP. Completing a workout or mistake review can add ${GAMIFICATION_CATALOG.workoutBonus.rankPoints} RP. Daily cap: ${GAMIFICATION_CATALOG.dailyRankPointsCap} RP. Some activities award XP only.`}</p></details>
      </div><div className="min-w-0 lg:order-1"><section aria-label={vi ? "Bảng xếp hạng" : "Leaderboard"}><div className="mb-3 flex items-end justify-between gap-2"><h2 className="text-2xl font-black">{vi ? "Dẫn đầu tuần" : "Weekly leaders"}</h2><span className="text-xs text-slate-500">{vi ? "Cùng điểm, cùng hạng" : "Equal RP shares rank"}</span></div>{board.top.length ? <div className="grid gap-2">{board.top.map(row => <Player key={row.userId} row={row} own={row.userId === user?.id} vi={vi} />)}</div> : <div className="rounded-2xl border bg-white p-6"><p className="font-bold">{vi ? "Chưa có ai ghi RP trong tuần này." : "No one has earned RP this week yet."}</p><p className="mt-2 text-sm text-slate-600">{vi ? "Bắt đầu luyện tập để có tên trên bảng." : "Start practicing to appear on the board."}</p></div>}</section>{nearby.length > 0 && <section className="mt-7"><h2 className="mb-3 text-xl font-black">{vi ? "Vị trí của bạn" : "Around your position"}</h2><div className="grid gap-2">{nearby.map(row => <Player key={row.userId} row={row} own={row.userId === user?.id} vi={vi} />)}</div></section>}</div></div>
    </> : <section className="mt-5">{selected ? <Link className="block rounded-2xl border border-slate-200 bg-white p-5 hover:border-teal-400 sm:p-6" href={`/ranking/challenges/${selected.id}`}><h2 className="text-xl font-black sm:text-2xl">{vi ? selected.titleVi : selected.titleEn}</h2><p className="mt-2 text-sm text-slate-600">{challengePhase(selected) === "LIVE" ? (vi ? "Đang diễn ra" : "Live now") : challengePhase(selected) === "UPCOMING" ? (vi ? "Sắp bắt đầu" : "Upcoming") : challengePhase(selected) === "CLOSED" ? (vi ? "Đã kết thúc" : "Closed") : (vi ? "Đã hủy" : "Cancelled")} · {selected.startsAt?.toLocaleString(vi ? "vi-VN" : "en-US", {timeZone:"Asia/Ho_Chi_Minh"})} → {selected.endsAt?.toLocaleString(vi ? "vi-VN" : "en-US", {timeZone:"Asia/Ho_Chi_Minh"})}</p></Link> : <div className="rounded-2xl border bg-white p-6"><h2 className="text-xl font-black">{vi ? `Thử thách ${tab === "READING_100" ? "Reading" : tab === "LISTENING_100" ? "Listening" : "Full Mock"} chưa bắt đầu` : "No active challenge yet"}</h2><p className="mt-2 text-sm text-slate-600">{vi ? "Chưa có thử thách được công bố cho hạng mục này. Bạn vẫn có thể luyện tập để kiếm RP trên bảng tuần." : "No challenge has been published for this category. You can still practice for weekly RP."}</p><Link className="mt-4 inline-flex min-h-11 items-center rounded-xl bg-teal-700 px-4 font-bold text-white" href={tab === "FULL_200" ? "/full-mock" : "/practice"}>{vi ? "Xem bài luyện tập" : "Explore practice"}</Link></div>}</section>}
    {user && history.length > 0 && <section className="mt-8"><h2 className="text-2xl font-black">{vi ? "Lịch sử thử thách" : "Challenge history"}</h2><div className="mt-3 grid gap-2">{history.map(item => <Link className="min-w-0 break-words rounded-xl bg-white p-4" href={`/ranking/challenges/run/${item.runId}/result`} key={item.runId}>{vi ? item.titleVi : item.titleEn} · <strong>{item.total}/{item.type === "FULL_200" ? 200 : 100}</strong></Link>)}</div></section>}
  </div></main>;
}
