"use client";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { useActionState } from "react";
import { signInAction, signUpAction, type AuthActionState } from "@/app/auth/actions";
import type { InterfaceLanguage } from "@/lib/i18n/config";
const initial: AuthActionState = { ok: false };
function Shell({ children, title, intro }: { children: React.ReactNode; title: string; intro: string }) { return <main className="min-h-screen bg-slate-50 px-6 py-12 text-slate-900"><section className="mx-auto max-w-md rounded-2xl border border-slate-200 bg-white p-7 shadow-sm sm:p-8"><Link className="text-sm font-semibold text-teal-700" href="/">← Trang chủ</Link><h1 className="mt-6 text-3xl font-bold">{title}</h1><p className="mt-2 text-slate-600">{intro}</p>{children}</section></main>; }
function GoogleButton({ next }: { next?: string | null }) { return <Link className="mt-7 flex w-full justify-center rounded-lg border border-slate-300 px-4 py-3 font-semibold hover:bg-slate-50" href={`/api/auth/google${next ? `?next=${encodeURIComponent(next)}` : ""}`}>Tiếp tục với Google</Link>; }
function Message({ state, queryError }: { state: AuthActionState; queryError?: string | null }) { const googleErrors: Record<string, string> = { link_required: "Email này đã có tài khoản. Hãy đăng nhập bằng mật khẩu rồi kết nối Google trong Cài đặt.", rate_limited: "Bạn đã thử đăng nhập quá nhiều lần. Vui lòng chờ 15 phút rồi thử lại.", google_unavailable: "Đăng nhập Google chưa được cấu hình.", google_start_failed: "Không thể bắt đầu đăng nhập Google. Vui lòng thử lại sau.", oauth_callback_failed: "Google không thể xác minh phiên đăng nhập. Vui lòng thử lại." }; const error = queryError ? googleErrors[queryError] ?? "Không thể đăng nhập bằng Google." : state.error; return <>{error ? <p className="mt-5 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p> : null}{state.message ? <p className="mt-5 rounded-lg bg-emerald-50 p-3 text-sm text-emerald-800">{state.message}</p> : null}</>; }
export function SignInForm({ locale }: { locale: InterfaceLanguage }) { const params = useSearchParams(); const [state, action, pending] = useActionState(signInAction, initial); const vi = locale === "vi"; return <Shell title={vi ? "Đăng nhập" : "Sign in"} intro={vi ? "Dùng Google hoặc email và mật khẩu." : "Use Google or your email and password."}><GoogleButton next={params.get("next")} /><div className="my-5 flex items-center gap-3 text-xs text-slate-400"><span className="h-px flex-1 bg-slate-200" />hoặc<span className="h-px flex-1 bg-slate-200" /></div><form action={action} className="space-y-4"><input name="next" type="hidden" value={params.get("next") ?? ""} /><label className="block text-sm font-semibold">Email<input className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2.5" name="email" required type="email" autoComplete="email" /></label><label className="block text-sm font-semibold">{vi ? "Mật khẩu" : "Password"}<input className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2.5" name="password" required type="password" autoComplete="current-password" /></label><button className="w-full rounded-lg bg-teal-700 px-4 py-3 font-bold text-white disabled:opacity-60" disabled={pending}>{vi ? "Đăng nhập" : "Sign in"}</button></form><Message state={state} queryError={params.get("error")} /><div className="mt-5 flex justify-between text-sm"><Link className="text-teal-700" href="/forgot-password">{vi ? "Quên mật khẩu?" : "Forgot password?"}</Link><Link className="text-teal-700" href="/sign-up">{vi ? "Tạo tài khoản" : "Create account"}</Link></div></Shell>; }
export function SignUpForm({ locale }: { locale: InterfaceLanguage }) { const [state, action, pending] = useActionState(signUpAction, initial); const vi = locale === "vi"; return <Shell title={vi ? "Tạo tài khoản" : "Create account"} intro={vi ? "Đăng ký bằng Google hoặc email." : "Register with Google or email."}><GoogleButton /><div className="my-5 flex items-center gap-3 text-xs text-slate-400"><span className="h-px flex-1 bg-slate-200" />hoặc<span className="h-px flex-1 bg-slate-200" /></div><form action={action} className="space-y-4"><label className="block text-sm font-semibold">Email<input className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2.5" name="email" required type="email" /></label><label className="block text-sm font-semibold">{vi ? "Mật khẩu (ít nhất 10 ký tự)" : "Password (10+ characters)"}<input className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2.5" minLength={10} name="password" required type="password" /></label><label className="block text-sm font-semibold">{vi ? "Xác nhận mật khẩu" : "Confirm password"}<input className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2.5" minLength={10} name="confirmPassword" required type="password" /></label><button className="w-full rounded-lg bg-teal-700 px-4 py-3 font-bold text-white disabled:opacity-60" disabled={pending}>{vi ? "Tạo tài khoản" : "Create account"}</button></form><Message state={state} /><p className="mt-5 text-sm"><Link className="text-teal-700" href="/sign-in">{vi ? "Đã có tài khoản? Đăng nhập" : "Already registered? Sign in"}</Link></p></Shell>; }
