"use client";
import Link from "next/link";
import { useActionState } from "react";
import { activateAccountAction, forgotPasswordAction, resetPasswordAction, type AuthActionState } from "@/app/auth/actions";
const initial: AuthActionState = { ok: false };
function Wrap({ title, children }: { title: string; children: React.ReactNode }) { return <main className="grid min-h-screen place-items-center bg-slate-50 p-6"><section className="w-full max-w-md rounded-2xl border bg-white p-7"><h1 className="text-2xl font-black">{title}</h1>{children}<Link className="mt-6 inline-block text-sm font-bold text-teal-700" href="/sign-in">Về trang đăng nhập</Link></section></main>; }
function Status({ state }: { state: AuthActionState }) { return state.error ? <p className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{state.error}</p> : state.message ? <p className="mt-4 rounded-lg bg-emerald-50 p-3 text-sm text-emerald-800">{state.message}</p> : null; }
export function ForgotForm() { const [state, action, pending] = useActionState(forgotPasswordAction, initial); return <Wrap title="Quên mật khẩu"><form action={action} className="mt-5 space-y-4"><input className="w-full rounded-lg border px-3 py-2.5" name="email" placeholder="Email" required type="email" /><button className="w-full rounded-lg bg-teal-700 px-4 py-3 font-bold text-white" disabled={pending}>Gửi hướng dẫn</button></form><Status state={state} /></Wrap>; }
function PasswordForm({ token, activation = false }: { token: string; activation?: boolean }) { const [state, action, pending] = useActionState(activation ? activateAccountAction : resetPasswordAction, initial); return <Wrap title={activation ? "Kích hoạt tài khoản" : "Đặt lại mật khẩu"}><form action={action} className="mt-5 space-y-4"><input name="token" type="hidden" value={token} /><input className="w-full rounded-lg border px-3 py-2.5" minLength={10} name="password" placeholder="Mật khẩu mới (10+ ký tự)" required type="password" /><input className="w-full rounded-lg border px-3 py-2.5" minLength={10} name="confirmPassword" placeholder="Xác nhận mật khẩu" required type="password" /><button className="w-full rounded-lg bg-teal-700 px-4 py-3 font-bold text-white" disabled={pending}>Lưu mật khẩu</button></form><Status state={state} /></Wrap>; }
export const ResetForm = ({ token }: { token: string }) => <PasswordForm token={token} />;
export const ActivationForm = ({ token }: { token: string }) => <PasswordForm token={token} activation />;
