"use client";
import Link from "next/link";
import { useActionState } from "react";
import type { InterfaceLanguage } from "@/lib/i18n/config";
import { DAILY_STUDY_MINUTES, STUDY_DAYS_PER_WEEK, TARGET_SCORE_PRESETS, type GoalProfile } from "@/lib/goals/domain";
import { saveGoal, type GoalActionState } from "./goal-actions";

const initialState: GoalActionState = { ok: false };
const optionClass = "flex min-h-11 cursor-pointer items-center gap-2 rounded-xl border border-slate-300 px-4 py-2 has-checked:border-teal-700 has-checked:bg-teal-50 has-checked:ring-1 has-checked:ring-teal-700 focus-within:outline-2 focus-within:outline-offset-2 focus-within:outline-teal-700";

export function GoalForm({ goal, locale }: { goal: GoalProfile | null; locale: InterfaceLanguage }) {
  const [state, action, pending] = useActionState(saveGoal, initialState);
  const vi = locale === "vi";
  const preset = goal?.targetScore && TARGET_SCORE_PRESETS.includes(goal.targetScore as never) ? String(goal.targetScore) : goal?.targetScore ? "custom" : "";
  return <form action={action} className="mt-6 space-y-7">
    <p className="text-sm leading-6 text-slate-600">{vi ? "Thiết lập mục tiêu để TOEICGym hiểu kế hoạch học của bạn. Các lựa chọn này không thay đổi hạn mức gói hiện tại." : "Set a goal so TOEICGym understands your study plans. These choices do not change your current plan limits."}</p>
    <fieldset><legend className="font-bold">{vi ? "Mục tiêu TOEIC" : "Target TOEIC score"}</legend><p className="mt-1 text-sm text-slate-500">{vi ? "Điểm Listening & Reading từ 10 đến 990, theo bước 5 điểm." : "Listening & Reading total from 10 to 990, in 5-point steps."}</p><div className="mt-3 flex flex-wrap gap-2"><label className={optionClass}><input defaultChecked={!preset} name="targetChoice" type="radio" value="" /><span className="font-semibold">{vi ? "Chưa xác định" : "Not decided"}</span></label>{TARGET_SCORE_PRESETS.map(value => <label className={optionClass} key={value}><input defaultChecked={preset === String(value)} name="targetChoice" type="radio" value={value} /><span className="font-semibold">{value}+</span></label>)}<label className={optionClass}><input defaultChecked={preset === "custom"} name="targetChoice" type="radio" value="custom" /><span className="font-semibold">{vi ? "Khác" : "Custom"}</span></label><input aria-label={vi ? "Điểm TOEIC tùy chỉnh" : "Custom TOEIC score"} className="min-h-11 w-32 rounded-xl border border-slate-300 px-3 focus-visible:outline-2 focus-visible:outline-teal-700" defaultValue={preset === "custom" ? goal?.targetScore ?? "" : ""} inputMode="numeric" max={990} min={10} name="customTarget" placeholder="10–990" step={5} type="number" /></div></fieldset>
    <div><label className="font-bold" htmlFor="examDate">{vi ? "Ngày thi dự kiến" : "Expected test date"}</label><p className="mt-1 text-sm text-slate-500">{vi ? "Không bắt buộc. Để trống nếu bạn chưa xác định ngày thi." : "Optional. Leave blank if you haven't decided yet."}</p><input className="mt-3 min-h-11 w-full max-w-xs rounded-xl border border-slate-300 px-3 focus-visible:outline-2 focus-visible:outline-teal-700" defaultValue={goal?.examDate ?? ""} id="examDate" name="examDate" type="date" /></div>
    <fieldset><legend className="font-bold">{vi ? "Thời gian học mỗi ngày" : "Study time per day"}</legend><div className="mt-3 flex flex-wrap gap-2"><label className={optionClass}><input defaultChecked={!goal?.dailyStudyMinutes} name="dailyStudyMinutes" type="radio" value="" /><span className="font-semibold">{vi ? "Chưa chọn" : "Not set"}</span></label>{DAILY_STUDY_MINUTES.map(value => <label className={optionClass} key={value}><input defaultChecked={goal?.dailyStudyMinutes === value} name="dailyStudyMinutes" type="radio" value={value} /><span className="font-semibold">{value} {vi ? "phút" : "min"}</span></label>)}</div></fieldset>
    <fieldset><legend className="font-bold">{vi ? "Số ngày học mỗi tuần" : "Study days per week"}</legend><div className="mt-3 flex flex-wrap gap-2"><label className={optionClass}><input defaultChecked={!goal?.studyDaysPerWeek} name="studyDaysPerWeek" type="radio" value="" /><span className="font-semibold">{vi ? "Chưa chọn" : "Not set"}</span></label>{STUDY_DAYS_PER_WEEK.map(value => <label className={optionClass} key={value}><input defaultChecked={goal?.studyDaysPerWeek === value} name="studyDaysPerWeek" type="radio" value={value} /><span className="font-semibold">{value} {vi ? "ngày" : "days"}</span></label>)}</div></fieldset>
    {state.error ? <p className="rounded-xl bg-red-50 p-3 text-sm text-red-700" role="alert">{state.error === "invalid" ? (vi ? "Hãy kiểm tra điểm mục tiêu, ngày thi và lịch học." : "Check the target score, test date, and study schedule.") : (vi ? "Không thể lưu mục tiêu. Vui lòng thử lại." : "We couldn't save your goal. Please try again.")}</p> : state.ok ? <p className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-800" role="status">{vi ? "Đã lưu mục tiêu học tập." : "Learning goal saved."}</p> : null}
    <div className="flex flex-col gap-3 sm:flex-row sm:items-center"><button className="min-h-12 rounded-xl bg-teal-700 px-5 py-3 font-bold text-white disabled:opacity-60" disabled={pending} type="submit">{pending ? (vi ? "Đang lưu…" : "Saving…") : (vi ? "Lưu mục tiêu" : "Save goal")}</button>{!goal ? <Link className="inline-flex min-h-11 items-center justify-center px-3 font-semibold text-slate-600" href="/dashboard">{vi ? "Bỏ qua lúc này" : "Skip for now"}</Link> : null}</div>
  </form>;
}
